### ISSUE TITLE
Make "mouse" events work on mobile devices

### ISSUE THREAD

**Issue by almarklein** [flexxui/flexx#149]
Many interactions do not work on a touchscreen. This might mean we'd rename some of our standard widget events. So important to get this in before we enter "beta".

**Comment by Korijn** [comment]
Might I suggest Pointer Events? It would be nice to have a unified event system for touch, mouse and pen. See also:

* https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events
* http://www.html5rocks.com/en/mobile/touchandmouse/

**Comment by almarklein** [comment]
Marking this for 0.5, since this might introduce backward incompatibilities (better do it sooner than later).
