### ISSUE TITLE
No example to redirect a new page and open a new page 

### ISSUE THREAD

**Issue by FunnyAlex** [flexxui/flexx#169]
I study all the doc and try all example on http://flexx.readthedocs.io/, but I don't find a way to redirect a new page and open a new page, I think, it is a common usage for desktop app and web app.
Please give some sample.

**Comment by almarklein** [comment]
Related to #189

**Comment by almarklein** [comment]
Made an example: https://github.com/flexxui/flexx/blob/master/flexxamples/howtos/redirect.py (visible as soon as #486 is merged)
