### ISSUE TITLE
Switching out widgets at runtime example

### ISSUE THREAD

**Issue by Korijn** [flexxui/flexx#182]
Using e.g. radio buttons to switch out the "active widget" is possible, but an example in the docs would be very helpful!

It's not very obvious that you need to use the following pattern:

``` python
def init(self):
    with ui.VBox() as self.vbox:
        self.some_widget = SomeWidget()

def switch_widget(self):
    self.some_widget.parent = None  # detach old widget
    with self.vbox:
        self.some_widget = SomeOtherWidget()
```

Or the following pattern that clears out a widget's children:

``` python
while len(self.my_container.children):
    el = self.my_container.children[-1]
    el.parent = None
```

**Comment by almarklein** [comment]
I know that I've written this pattern somewhere, but it does not look very elegant ...

For widgets that should be re-selectable, its better to use the `StackPanel`. Maybe we need a new layout widget, or feature of `StackPanel` to allow for "disposable" widgets.

**Comment by Korijn** [comment]
#189 is related in my opinion, as a `Router` widget is capable of switching out it's children (e.g. when you click on a `Link` widget).

**Comment by almarklein** [comment]
A somewhat related use-case that recently popped up: say we have a BoxPanel with multiple widgets, it would be nice to be able to hide (as in collapse) some of these widgets.

**Comment by Korijn** [comment]
I thought that particular case might be solvable by just hiding some of the widgets so that the remaining ones can grow to fill the container. But there is no hiding mechanism either. :)

**Comment by almarklein** [comment]
Phosphor widgets have a `hide()` and `show()` method, which eventually set `display: hidden`, so exposing that in Flexx should make that work.

**Comment by Korijn** [comment]
When I used a CSS class to apply `display: none` Flexx actually started raising errors.

**Comment by Korijn** [comment]
I've started work on a Router widget, but it's grinded to a halt when some internal priorities came up. I'll pursue it again sometime soon. Here's my branch: https://github.com/zoofIO/flexx/compare/master...Korijn:router

**Comment by coolsnake** [comment]
Hi, Korijn

Can you update the router based on the latest version?

**Comment by Korijn** [comment]
Sorry, I'm no longer pursuing this effort.
