### ISSUE TITLE
Minify JS with source map

### ISSUE THREAD

**Issue by Korijn** [flexxui/flexx#201]
To reduce JS size and increase page load times, you can use projects like UglifyJS to minify JS and let it output sourcemaps to continue to provide a pleasant debugging experience.
- https://github.com/mishoo/UglifyJS2
- http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

There are many ways to do it, but it can be very simple:

``` js
var result = UglifyJS.minify({"file1.js": "var a = function () {};"}, {
  outSourceMap: "out.js.map",
  fromString: true
});

// or

var result = UglifyJS.minify([ "file1.js", "file2.js", "file3.js" ], {
  outSourceMap: "out.js.map"
});
```

**Comment by almarklein** [comment]
The problem with these is that they rely on nodejs, and I don't want to make that a dependency of Flexx. Ideally we'd use a pure-Python minifier (Flexx includes a very minimalist one that removes comments etc. but keeps the code readable (because it does not do sourcemaps). Another option might be to make nodejs an optional dependency.

**Comment by almarklein** [comment]
Maybe there is stuff that we can use from https://github.com/django-compressor/django-compressor/tree/develop/compressor

**Comment by almarklein** [comment]
Another option is to generate minified JS by the parser itself. It already has AST, so it should be well-capable to e.g. shorten variable names.

**Comment by Korijn** [comment]
Did you see the section "Building for the browser"?

http://lisperator.net/uglifyjs/

Maybe you can vendor it?

**Comment by almarklein** [comment]
But then Flexx would first need to spin up a (local) browser send it the JS, get the JS back, and then spin up the actual browser with the app?

**Comment by Korijn** [comment]
You raise a good point! I stand corrected. :)

**Comment by almarklein** [comment]
Source maps explanation: https://www.schneems.com/2017/11/14/wtf-is-a-source-map/

**Comment by almarklein** [comment]
Issue moved to [flexxui/pscript #10](https://github.com/flexxui/pscript/issues/10) via [**ZenHub**](https://www.zenhub.com/)
