### ISSUE TITLE
Passing arguments to custom objects

### ISSUE THREAD

**Issue by nuno-andre** [flexxui/flexx#249]
I've found a strange behaviour subclassing a widget with children to provide arguments. If I don't create the the object before the instantiation, the compound widget doesn't render correctly.

For example, if I replace `A()` with `B()` in this code I get a different layout.

```
class A(ui.Widget):
    def init(self):
        ui.Label(text='foo')


class B(ui.Widget):
    def __init__(self, **kwargs):
        super().__init__()
        ui.Label(text='foo')


class Main(ui.Widget):
    def init(self):
        with ui.VBox():
            A()
            ui.Label(text='bar')


if __name__ == '__main__':
    app.launch(Main, 'xul')
    app.run()
```

I have to create the object before instantiate it:

```
class B(ui.Widget):
    def __new__(self, **kwargs):
        ui.Label(text='foo')
```

Am I missing something here?

**Comment by almarklein** [comment]
The way you write it with `class A` is the correct version; the `init()` method gets called at a moment when all properties are initialized, and the  `init()` is also called "in the context of the instance"; as you wrote it in `class B`, the label won't be a child of the `B` object.

**Comment by nuno-andre** [comment]
So which is the correct way to pass kwargs to a subclassed compound widget?

I've tried it replacing

        for name, value in property_values.items():
            if name in self.__properties__:
                setattr(self, name, value)  # should raise error whith readonly
            else:
                cname = self.__class__.__name__
                raise AttributeError('%s does not have a property %r' % (cname, name))

with 

        for name, value in property_values.items():
            setattr(self, name, value)  # should raise error whith readonly

in `event/_hasevent.py` so I can pass kwargs by:

    class A(ui.Widget):
        def __new__(self, **kwargs):
            for name, value in kwargs.items():
                setattr(self, name, value)
            self.init(self)

        def init(self):
            ui.Label(text='foo')

and it seems to work correctly.

Is this the right way? Can it cause any side effect?

**Comment by almarklein** [comment]
Well, you should not have to modify the source of Flexx. Also, you should not call the `init()`, Flexx takes care of calling it at the right moment.

There is not really a good way to send kwargs to a `Model`, because the kwargs are reserved for properties. You can pass positional `args` though:

```py
class A(ui.Widget):
    def init(self, foo, bar):
          ...

A(3, 4)  # foo=3, bar=4
```

If you *really* must use kwargs, you could do this:
```py
class A(ui.Widget):
    def __init__(self, *args, foo=3, bar=5, **kwargs):  
        super().__init__(self, *args, **kwargs)
        ... do something with foo and bar

     def init(self):
          ...
```

**Comment by nuno-andre** [comment]
Yes, passing them to `init` in a dict as a positional arg seems the best option. Something like:

    class A(ui.Widget):
        def init(self, kwa):
            self.__dict__.update(kwa)
            ...

Thanks!

Anyway, trying the second approach I get this exception:

	Traceback (most recent call last):
	  File "E:\Hermes\GUI\test.py", line 61, in <module>
	    app.launch(Main, 'xul')
	  File "C:\Anaconda3\lib\site-packages\flexx-0.4.1.dev0-py3.5.egg\flexx\app\funcs.py", line 339, in launch
	    session = manager.create_session(name)
	  File "C:\Anaconda3\lib\site-packages\flexx-0.4.1.dev0-py3.5.egg\flexx\app\session.py", line 128, in create_session
	    app = cls(session=session, is_app=True, **properties)  # is_app marks it as main
	  File "C:\Anaconda3\lib\site-packages\flexx-0.4.1.dev0-py3.5.egg\flexx\ui\_widget.py", line 123, in __init__
	    Model.__init__(self, *init_args, **kwargs)
	  File "C:\Anaconda3\lib\site-packages\flexx-0.4.1.dev0-py3.5.egg\flexx\app\model.py", line 399, in __init__
	    self.init(*init_args)
	  File "E:\Hermes\GUI\test.py", line 56, in init
	    A(foo='baz', bar='qux')
	  File "E:\Hermes\GUI\test.py", line 47, in __init__
	    super().__init__(self, *args, **kwargs)
	  File "C:\Anaconda3\lib\site-packages\flexx-0.4.1.dev0-py3.5.egg\flexx\ui\_widget.py", line 123, in __init__
	    Model.__init__(self, *init_args, **kwargs)
	  File "C:\Anaconda3\lib\site-packages\flexx-0.4.1.dev0-py3.5.egg\flexx\app\model.py", line 399, in __init__
	    self.init(*init_args)
	TypeError: init() takes 1 positional argument but 2 were given

**Comment by Korijn** [comment]
This is something we've found to be confusing as well. It would be really neat if we could somehow just use regular constructors with args and kwargs, instead of having to memorize a framework-specific API.

**Comment by nuno-andre** [comment]
Maybe saving the arguments not found at `property_values` in `HasEvents` and updating the properties at initialization?

**Comment by almarklein** [comment]
Woops, should not pass self if using super: ``super().__init__(*args, **kwargs)``. Updated above.

**Comment by almarklein** [comment]
Well, you can use regular constructors if you want to (as in the second example above). However, de `init()` provides a place that is generally better do do initialization:
* Initial property values have been set.
* The instance is the "active" instance (so widgets created in `init()` become children of the instance.
* You can emit events here.
* Probably more

For the above to work, it is crucial that `init()` is called at the right moment in the initialization procedure ,e.g. also w.r.t. preparing the JS side. Therefore, the `init()` should be the preferred place to do initialization.

So overloading ``__init__`` is fine in special cases, as long as you correctly call `super().__init__`.

**Comment by almarklein** [comment]
I'd like to add, the rule for args is pretty simple: keyword args are used to initialize properties, positional args are passed to `init()`.
