### ISSUE TITLE
Text property (of Button, LineEdit, etc.) is interpreted as HTML

### ISSUE THREAD

**Issue by almarklein** [flexxui/flexx#293]
As a consequence, setting the text to e.g. `"<empty>"` or `repr(ob)` will give odd results. It can also be an advantage though, e.g. to include a small image or use markup like `<b>`.

Affected widgets: `Button`, `RadioButton`, `CheckButton`, `LineEdit`, `Label.text` (has probably many cases where HTML is deliberately used). `Widget.title` in some places, `TreeItem.text` and `TreeItem.title`, `ComboBox.items`, `ui.html.XX.text` is deliberately html.

Questions:

* Should we sanitize the input of this prop?
* If not, should we sanitize some of them? E.g. `.title`
* How hard is it to do this in JS? -> easy, look at `html.escape()`, though not sufficient in light of [this](http://wonko.com/post/html-escaping)
* If we sanitize, should we also have a `html` prop?

cc @Maxyme

**Comment by almarklein** [comment]
Maybe a magic prefix, like `widget.text = '/plain/<haha>'`. Something like this would avoid synchronization issues (sanitizing in JS *and* Py), and backwards incompatibility.

**Comment by Korijn** [comment]
Note that we depend on this functionality in some places by now.

**Comment by Maxyme** [comment]
I think having a deliberate html property would solve most of this problem, where text is always escaped, and html a property that can have dynamic html and where it gets sanitized.

**Comment by almarklein** [comment]
I am a little worried about backwards compatibility, and not enthousiastic about a `text` and `html` prop side-by-side. What about an easy to access function to escape the text where needed. Something like:
```py
from flexx.ui import escape   # works in JS and py
x.text = escape(...)
```

**Comment by Maxyme** [comment]
makes sense. We could have a import sanitize as well for user inputs from the client.

**Comment by almarklein** [comment]
You mean sanitize as in removing `<` and `>`?

**Comment by Maxyme** [comment]
no, this is a good read:
http://wonko.com/post/html-escaping

**Comment by Korijn** [comment]
Mostly to avoid XSS attacks I guess?

**Comment by almarklein** [comment]
We should probably `node.textContent` is some places: https://developer.mozilla.org/en/docs/Web/API/Node/textContent

**Comment by almarklein** [comment]
The new `_render_dom()` is also relevant in this discussion. I think we should avoid users from opening up possibilities for XSS attacks, and provide means to insert plain HTML in some places, with warning signs.
