### ISSUE TITLE
PyScript glitches

### ISSUE THREAD

**Issue by almarklein** [flexxui/flexx#332]
This is an issue to collect "glitches" in PyScript, because it's so easy to forget about them. We'll have to see whether to fix or document each one individually.

* `if x`, with x an object can resolve to `False` if that object has a `length` property.
* IIRC `x = x or 0` does not work, since `truthy()` returns `False` on a non-truthy and the original object otherwise.
* `elif this_is_js():` produces syntactically invalid JS.
* using `range()` brings in the `pyfunc_range()` even if used in for-loop.
* `assert x` does not use `truthy()`
* List comprehensions do not work with float arrays #396

**Comment by Winand** [comment]
pyscript allows "def catch():" and "this = ..." and produces invalid js

**Comment by Winand** [comment]
```
class Translator():
    langs, q = {}, None
```
produces invalid js source (variables are defined globally):
```
stub2_ = [{}, null];
langs = stub2_[0];q = stub2_[1];
```

**Comment by almarklein** [comment]
Issue moved to [flexxui/pscript #7](https://github.com/flexxui/pscript/issues/7) via [**ZenHub**](https://www.zenhub.com/)
