### ISSUE TITLE
button css margins.

### ISSUE THREAD

**Issue by drafter250** [flexxui/flexx#339]
Hi, first time posting an issue on flex, thanks for all the great work!

I was Trying to create something like a menu-bar by stacking buttons together in a ui.HBox.

However to get that "menu-bar look" I don't want any space between them. In the CSS for the button I am setting both margin and margin-left to 0px, however when I create them in the context of the HBox no matter what I do every button but the first one still has in it's style, "margin-left: 5px"

This is the basic code, I am not very far along:

``` python
from flex import ui, event, app
from IPython.display import display
app.init_notebook()

class MenuButton(ui.Button):
    CSS=".flx-MenuButton {padding:3px; margin-left: 0px}"

    def init(self):
        self.flex =(1.,1.)

class Menu(ui.HBox):
    CSS = ".flx-Menu {background:light-gray; height:40px}"
    
    def init(self):
        self.b_view = MenuButton(text='View')
        self.b_file = MenuButton(text='File')
        self.b_settings = MenuButton(text='Settings')

menu_bar = Menu()
display(menu_bar)
```

maybe it's just some css nuance? I don't have a ton of experience.

**Comment by almarklein** [comment]
The HBox is probably overloading the styling; try setting the hbox `spacing` to 0.

**Comment by drafter250** [comment]
Didn't seem to have an effect.

when I look at the computed tab in the developer tools for firefox for the button element there are a list of css attributes under margin-left, at the top is 'this.style' : 5px and below that is the '.flx-MenuButton' which is crossed out.

Oh and I am running version 4.1 on windows, and seeing this on both firefox and IE 11.

**Comment by almarklein** [comment]
oh, please use the bleeding edge version of Flexx. If I recall correctly, these 5px was hardcoded while it should use the spacing.

**Comment by almarklein** [comment]
Closing, as its likely fixed. Please re-open if not.
