### ISSUE TITLE
Clarify what versions of browsers are supported

### ISSUE THREAD

**Issue by almarklein** [flexxui/flexx#341]
A: In the documentation.

B: Maybe we can do browser detection for the purpose of showing a warning for unsupported browsers.

**Comment by Korijn** [comment]
You'd be better off doing feature detection, to show a warning for unsupported browsers.

Browser detection is notoriously unreliable. :)

**Comment by almarklein** [comment]
Yeah, I know that browser detection os nasty. I was hoping its relatively easy to reliably spot *old* browsers though. Its ok if we miss new ones, because these are likely to work anyway. 

Though perhaps its easier to check a few things like `Array.isArray` and others JS features that we know do not exist in unsupported browsers.

**Comment by Korijn** [comment]
I recommend Modernizr as a source of reference: https://modernizr.com/
