### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by pohmelie** [flexxui/flexx#373]
It looks like there is cheap way to use asyncio with flexx. But I'm not sure how it will work with many connections from browser, since I'm not familiar with flexx internals. More than one event loop? Threads?
``` python
import asyncio

from flexx import app, ui

import tornado.ioloop


tornado.ioloop.IOLoop.configure('tornado.platform.asyncio.AsyncIOLoop')


@app.serve
class Example(ui.Widget):

    def init(self):
        with ui.HBox():
            ui.Button(flex=1, text="hello")
            ui.Button(flex=1, text="world")

        asyncio.ensure_future(self.yoba())

    async def yoba(self):
        while True:
            loop = asyncio.get_event_loop()
            print(id(loop), loop)
            await asyncio.sleep(1)


app.start()
```
I'm asking core devs to inspect this code and check corner cases. It will be very nice, if flexx will support asyncio officially and documentation takes paragraph about it.

**Comment by pohmelie** [comment]
Hm, it looks like this does not work with current master. But works fine with pypi version.

**Comment by pohmelie** [comment]
Ok, more canonical example from documentation works fine on python 3.4.6 with current master.
http://www.tornadoweb.org/en/stable/asyncio.html#tornado.platform.asyncio.AsyncIOMainLoop
``` python
import asyncio

from flexx import app, ui

from tornado.platform.asyncio import AsyncIOMainLoop


class Example(ui.Widget):

    def init(self):
        with ui.HBox():
            ui.Button(flex=1, text="hello")
            ui.Button(flex=1, text="world")

        asyncio.ensure_future(self.yoba())

    @asyncio.coroutine
    def yoba(self):
        while True:
            loop = asyncio.get_event_loop()
            print(id(loop), loop)
            yield from asyncio.sleep(1)


AsyncIOMainLoop().install()
app.serve(Example)
app.start()

```

**Comment by almarklein** [comment]
>  But I'm not sure how it will work with many connections from browser, since I'm not familiar with flexx internals. More than one event loop? Threads?

Multiple connections are simply handled as events. There is exactly one event loop (in a single thread).

Leaving this open as a todo to document the usage. Also related to #142

**Comment by almarklein** [comment]
#408 implements Flexx' event loop on top of asyncio, also see #413 to take this further.
