### ISSUE TITLE
Bokeh figure does not show using BokehWidget

### ISSUE THREAD

**Issue by andyneer** [flexxui/flexx#397]
Considering [this example](http://flexx.readthedocs.io/en/stable/ui/examples/with_bokeh_src.html) of Flexx using BokehWidget, when the "sizing_mode" is changed for "fixed", "scale_height", "scale_both", and "stretch_both", the bokeh figure does not show (I'm using Jupyter). However, when using "scale_width", the bokeh figure shows up. 
For example, I'd rather use the "scale_both" sizing mode. Does anyone have an ideia about this?
Thank you!

Best regards,
Andy

**Comment by almarklein** [comment]
I suspect that Bokeh has changed somewhat with how it does it sizing (it was sort of a work in progress when I wrote the BokehWidget). Needs updating.

**Comment by almarklein** [comment]
I can confirm that the Bokeh widget was broken. It has been fixed with #408. Keep an eye out for the release.
