### ISSUE TITLE
How you can use external css libraries within flexx?

### ISSUE THREAD

**Issue by drorhilman** [flexxui/flexx#410]
Question: 
Can you use external css libraries such as Materialzie.css in flexx (mainly based on assigning classes to elements to change their appearance)?

**Comment by Korijn** [comment]
Many css frameworks require you to use specific HTML structures, and that in particular is hard to combine with Flexx widgets.

**Comment by almarklein** [comment]
Indeed, it depends on the situation. You can assign css classes to Flexx widgets, and use `ui.html` for more control, but it might now always work well.

**Comment by almarklein** [comment]
See the new `with_bootstrap.py` [example](https://github.com/flexxui/flexx/blob/master/flexx/ui/examples/with_bootstrap.py).
