### ISSUE TITLE
cannot use the 'html' object of the ui API

### ISSUE THREAD

**Issue by drorhilman** [flexxui/flexx#411]
The doc example:
```
from flexx import app, ui
class Example(ui.Widget):
    def init(self):
        with ui.html.UL():
            ui.html.LI(text='foo')
            ui.html.LI(text='bar')
```
returns:

**> module 'flexx.ui' has no attribute 'html'**

**Comment by almarklein** [comment]
Are you using the bleeding edge version from the repo?

Also, please be aware that we're refactoring Flexx quite a bit right now, and the of writing widgets is likely to change somewhat.

**Comment by drorhilman** [comment]
Thanks, 
This seems an amazing library, but I can't get it to run soem of the examples, and also find it 
a bit hard to customize. 
(also the 'associate_asset' functionality seems to be absent.)

I am currently using version 0.4.1
How can I get the "bleeding edge" version ?

**Comment by almarklein** [comment]
`pip install git+https://github.com/zoofio/flexx.git`, or download the latest and run `setup.py install`.

**Comment by drorhilman** [comment]
Thanks!

**Comment by almarklein** [comment]
The `ui.html` has been removed with #408. Use `Widget._render_dom()` for a similar degree of control.
