### ISSUE TITLE
How critical is support for Internet Explorer (IE)?

### ISSUE THREAD

**Issue by almarklein** [flexxui/flexx#412]
The use of IE is in its [decline](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers#/media/File:StatCounter-browser-ww-monthly-200901-201707.png). To what extend is still necessary to support it? There are several features that we can't use, making the PyScript bulkier/slower and even prevents certain functionality.

My feeling is that we should probably keep supporting it for now, but this issue will become increasingly relevant.

Examples:

* Variable destructuring: `[a, b] = ....`, though this also fails on Safari.
* We cannot do `a = 'foo'; {a: 3}`. Well, we  *could* translate that to `a = 'foo'; {[a]: 2}`, but that does not work on bloody IE.

**Comment by almarklein** [comment]
For the second bulletpoint, the implication is that we cannot do something like this in Flexx.:
```py
key = 'keyname'
new_dict = {key: 42}
```

**Comment by almarklein** [comment]
Also see flexxui/pscript#3

**Comment by ivoflipse** [comment]
As a data point: We don't have a need for supporting IE

**Comment by almarklein** [comment]
I just closed the corresponding issue for PScript: I intend to keep PScript working for IE. But my feeling is that we should not try too hard to do this for Flexx ...

**Comment by almarklein** [comment]
With #484, we do support IE10 and up, but the page will show a warning (in the spinner) for 2 seconds first. This makes that someone on IE giving this a look will at least get something, but will understand if it looks a bit bad at times (e.g. I've dropdown menus not being visible outside of the parent widget).
