### ISSUE TITLE
Example monitor.py fail to start

### ISSUE THREAD

**Issue by sylvchev** [flexxui/flexx#415]
When starting [monitor.py](http://flexx.readthedocs.io/en/stable/ui/examples/monitor_src.html#monitor-py), the script fails with the following error:
`RuntimeError: Class methods can only be made handlers using @event.connect() (handler '_push_info')`

I did not encounter this error a year ago, the monitor example was working perfectly. I tried to fix this issue without success. If you have some hint on how to solve this issue, I could try to propose a solution.

**Comment by almarklein** [comment]
Are you using the latest version of Flexx? The last release is rather outdated.

Also, please be aware that we're currently doing a big refactoring of Flexx, which will improve it in many ways, but also change how apps will be written (e.g. no more nested JS classes).

**Comment by almarklein** [comment]
Should work in lastest tip. We're moving towards a release now.
