### ISSUE TITLE
When passing an initial value to a Component, should the setter be used?

### ISSUE THREAD

**Issue by almarklein** [flexxui/flexx#423]
At the time of writing, the current stage of refactoring (#408), when an initial value for a property is given to a `Component`, it is simply set, and *not* passed through its setter. The reasoning was that the user knows what he/she is doing, and it allows setting the initial value of read-only properties.

However, when a setter is available that does some normalization to the value, it feels unexpected that this normalization does not occur when passing a property value to the `Component` constructor. E.g. with `foo` an int constrained between 0 and 9.
```py
>>> c = SomeComponent(foo=12)
>>> c.foo  # 12
>>> c = SomeComponent()
>>> c.set_foo(12)
>>> c.foo  # 9
```

Things to consider:

* If we would make use of the setter, the properties are not directly set at initialization time, because the setters are actions.
* Unless the constructor is an action? I don't think that can work.
* Initial values for read-only properties can be supplied via positional properties if needed.

Let's explore the options (I'll edit as I get more ideas):

* A) current situation, initial values are set (directly mutated), bypassing the setter (if available).
* B) Mutate the property to the given value, but also pass to the setter action if there is one. This would still result in "weird values" in the `init()`.
* C) Allow processing actions at initialization time; actions being invoked from a `set_xx` action will then also be applied directly.
* D) Allow processing very specific actions. Other actions being invoked will pend as usual.

This needs more thought. I consider this a blocker for #408.

**Comment by ivoflipse** [comment]
"What would <insert other framework> do?"

**Comment by almarklein** [comment]
The conclusion after a discussion is mainly that custom set actions should probably not be used for validation/normalization of property values. The best would be to write a custom Property class so that the validation is performed when the value is *mutated* (i.e. also when passed to the constructor). When this seems overkill, one can still use a custom setter action, but ensure to invoke it in the `init()` like so: `self.set_foo(self.foo)`.

**Comment by almarklein** [comment]
Update:

I've just made some changes in #453 that makes mutations to a component possible during its `init()`. This allows initializing properties, and have the effect immediately (a thing for which we had to do ugly workarounds before). This also makes it possible to initialize all properties using the setter when it is available.
