### ISSUE TITLE
Spin off (some of the) sub-packages

### ISSUE THREAD

**Issue by almarklein** [flexxui/flexx#428]
Flexx' subpackages have been designed to be relatively independent. Especially pyscript, dialite, webruntime and maybe event might also be valuable on their own. The app and ui subpackages rely on other subpackages, and are really specific to the main goal of Flexx, so they should stay. 

Spinning these projects off would allow them to gain use outside of Flexx (e.g. PyScript is a very able competitor to TranScript). It would also make the documentation of Flexx itself leaner.

Things to consider:

* The common functionality in the util package.
* There is already a Python package called "pyscript". Though deprecated, it is on pypi.
* The name "webruntime" might be taken too?
* PyScript and webruntime also work on 2.7, the rest is Py3k only.

**Comment by almarklein** [comment]
Thoughts: All examples start with `from flexx import app, event, ui`. So let's keep these together. PyScript, webruntime and dialite can very well be spun off.

**Comment by almarklein** [comment]
Related: 

Although technically one can use `flexx.app` without `flexx.ui`, this is extremely rare. Same for the event system. I'd like to consider providing a single namespace that user can import and use. This also makes that people don't have to remember what is defined in what namespace.

Use Flexx:

```py
import flexx

class MyApp(flexx.Widget):
    foo = flexx.IntProp()
     ...
m = flexx.launch(MyApp)
flexx.run()
```

This name is a bit long, so maybe we can promote the use of a shorthand:
```py
import flexx as flx
...
```

Or provide a new namespace, giving the advantage that it's still possible to import event and app without importing ui:
```py
from flexx import flx
...
```

Maybe @korijn and @ivoflipse  have thoughts on this?

**Comment by ivoflipse** [comment]
The naming convention seems familiar like Maptlotlib's plt shorthand for pyplot, which bundles a lot of other functionality

**Comment by ivoflipse** [comment]
From browsing through the source, a lot of widgets in ui import app and/or events, so separating those would not be worthwhile, unless you think someone would be interested in app & event without the ui. In which case I don't know why they would be using flexx

**Comment by almarklein** [comment]
Indeed, ppl using `flexx.ui` are already using `event` and `app`, explicitly, or implicitly. And 99% of Flexx users do so for `flexx.ui`. Just wondering if we need an opening for ppl who want to e.g. build some sort of ui with `flexx.event` and Qt.

**Comment by almarklein** [comment]
Done in #458 and #459
