### ISSUE TITLE
AttributeError: module 'flexx.app' has no attribute 'App'

### ISSUE THREAD

**Issue by debanjanxy** [flexxui/flexx#432]
I am trying to run the following code 

from flexx import app, ui
from flexx.ui.examples.splines import Splines
from flexx.ui.examples.twente import Twente
from flexx.ui.examples.drawing import Drawing

class Demo(ui.Widget):

    def init(self):
        with ui.TabLayout():
            Splines(title='Spline demo')
            Twente(title='Temperature vis')
            Drawing(title='Drawing app')
            ui.YoutubeWidget(title='Video')

if __name__ == '__main__':
    m = app.App(Demo, title='Flexx demo').launch()
    app.run()

But whenever I am getting the following error while running 

Traceback (most recent call last):
  File "fl1.py", line 17, in <module>
    m = app.App(Demo, title='Flexx demo').launch()
AttributeError: module 'flexx.app' has no attribute 'App'

**Comment by almarklein** [comment]
Are you using a release or the latest master? The last release has been a while ago and is outdated. We're working towards a new release now.

**Comment by debanjanxy** [comment]
Release

**Comment by almarklein** [comment]
Ok, that explains it. You can either install the lastest master:
```
pip install https://github.com/flexxui/flexx/archive/master.zip
```
or wait til the next release.
