### ISSUE TITLE
module ... has no attribute ...

### ISSUE THREAD

**Issue by JTSvejda** [flexxui/flexx#440]
Hi,

I would like to create a GUI for some scientific calculations and flexx looks very well suited for my purposes.

But I'm having troubles with the very first examples like:
```
from flexx import app, ui

class Example(ui.Widget):

    def init(self):
        with ui.HSplit():
            ui.Button(text='foo')
            with ui.VBox():
                ui.Button(flex=1, text='bar')
                ui.Button(flex=1, text='spam')

app.export(Example, 'example.html')
```
I receive the following error massage by python:
`AttributeError: module 'flexx.ui' has no attribute 'HSplit'`

A similar error is produced if i try code with
`@event.reaction`
which leads to the error massage:
`AttributeError: module 'flexx.event' has no attribute 'reaction'`

On the other hand the 'hello world' program works well:
```
from flexx import app, ui

@app.serve
class Example(ui.Widget):
    def init(self):
        ui.Label(text='hello world')

#example = app.launch(Example)
app.export(Example, 'example.html')
```

I'm using the latest python version on a manjaro (arch) system as well as the latest flexx version. I've tried a ubuntu system in a virtual box with the same result. An installation of flexx via github also creates the same issue.

I hope you can help.

Kind regards
JTS

**Comment by almarklein** [comment]
The current release lags behind the latest documentation. Please either use the latest commit from the repo (see the readme how to do that using pip), or wait for the release which should be in a few weeks.

**Comment by almarklein** [comment]
> I would like to create a GUI for some scientific calculations and flexx looks very well suited for my purposes.

Happy to hear that! :)

**Comment by JTSvejda** [comment]
That was a fast response. Thanks :)

**Comment by superghm** [comment]
I am with the same problem. How to resolve? I noticed this happens with tornado version under 5.0. When tornado is up to date to the last version occurs a new problem saying "initialize() got an unexpected keyword argument 'io_loop'".

**Comment by almarklein** [comment]
@superghm Are you using the bleeding edge version from Github, as in `pip install https://github.com/flexxui/flexx/archive/master.zip`?

**Comment by superghm** [comment]
@almarklein I've installed with pip.

**Comment by almarklein** [comment]
Yeah, but I mean, did you do `pip install flexx` or `pip install https://github.com/flexxui/flexx/archive/master.zip`? :)

**Comment by superghm** [comment]
Sorry, pip install flexx.

**Comment by almarklein** [comment]
That installs the latest release, which is very old, which is what causes the problem.

**Comment by superghm** [comment]
Thanks! Installing from git it is exporting to html correctly. But in app.launch(Example) occured an erro saying: 
"lib\site-packages\webruntime\_manage.py", line 137, in get_pid_list
    out = subprocess.check_output(cmd).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 49: invalid continuation byte"

**Comment by almarklein** [comment]
Oh, you seem to have caught an interesting bug there.  Could you please try modifying that file by replacing the `.decode()` with `.decode(errors='ignore')`? If that works, we can fix it in the webruntime package.

**Comment by superghm** [comment]
@almarklein Today, misteriously that error did not happened more. After I tried again I did the replace you reccomended, seems works fine.

The prompt show:
```
[I 10:14:10 flexx.app] Asset store collected 2 new modules.
[I 10:14:12 flexx.app] Serving apps at http://localhost:49190/
[I 10:14:12 flexx.app] Asset store collected 23 new modules.
```
But when run "example = app.launch(Example)" shouldn't show any screen with application?
I tried access a tab with http://localhost:49190/ but there was no nothing there.

**Comment by almarklein** [comment]
> But when run "example = app.launch(Example)" shouldn't show any screen with application?

Yes, an app should pop up. Depending on the OS you may have to select it first. 

You also have `flx.run()` or `app.run()` below that?

**Comment by superghm** [comment]
Thanks! Everything is ok now, was missing the `app,run()`
