### ISSUE TITLE
Does flexx leverage binary websocket transmission?

### ISSUE THREAD

**Issue by Korijn** [flexxui/flexx#444]
I learned today that it is possible to transmit Blob and ArrayBuffer objects over websockets. This means you can avoid serializing to base64 strings. Is this leveraged by flexx?

**Comment by almarklein** [comment]
Of course! All messages passed between Py and JS are BSDF objects and send in binary form!

**Comment by almarklein** [comment]
When writing a speed test example today, I found that there is a limit to the size of the websocket messages. So we may need to add some support to cut messages in pieces.
