### ISSUE TITLE
how to track event like lost focus?

### ISSUE THREAD

**Issue by apdd2003** [flexxui/flexx#447]
Hi,
I am new to flexx and going through http://flexx.readthedocs.io for examples.
Here in http://flexx.readthedocs.io/en/latest/ui/button.html has event for mouse_click (button), checked (radio/toggle button) etc.
Whereas LineEdit has only one -submit().
I want to check the data when LineEdit loses focus. Is there a way to achieve this?

e.g. I want LineEdit ui to hold only interges greater than 5000

**Comment by almarklein** [comment]
The LineEdit 'submit' event gets emitted when it loses focus or when enter is pressed. Do you mean that you do not want to trigger when enter is pressed?

**Comment by apdd2003** [comment]
I want to get behavior equivalent of javascript's onblur() or onfocusout() in flexx.
I tried with 'submit' event, it is only triggered when Enter key is press but not triggered when user moves out of element.

code:


flexx import app, event, ui

class Example(ui.Widget):

    def init(self):
        with ui.FormLayout():
            ui.Widget(flex=.2)
            self.t1 = ui.LineEdit(title='Amount:',style='width:30%;')
            ui.Widget(flex=.2)
            self.l2 = ui.Label(title='Note:')
            ui.Widget(flex=3)  

    @event.reaction('t1.submit')
    def _lineEdit_events(self, *events):
        ev = events[-1]
        self.l2.set_text('Lost focus')
app.export(Example,'test.html')

**Comment by almarklein** [comment]
I stand corrected; it does not emit "submit" when losing focus. The line edit in the combobox does, but not the normal one. I'd need to re-think to see what makes sense. Can you explain a bit about your use-case? Would it work for you if "submit" would also trigger on losing focus?

For the time being, you can make your example work by adding this line to the `init()`:
```py
    self.t1.node.onblur = self.t1.submit
```

**Comment by apdd2003** [comment]
thanks for reply.   your suggestion/trick will do as of now. 
my use-case is:  I want user to only enter integers greater than say 5000 in line-edit. If user enters string or any other value and then moves on to other fields of the form, I want to alert user to get alert message

One more thing,  In http://flexx.readthedocs.io/en/latest I could not find any material regarding DOM node or tricks of assigning JS events to flexx events. Please share link if it is there.

**Comment by almarklein** [comment]
Thanks for the clarification.

Yes, you are right; the docs of `ui` or `Widget` should explain about `Widget.node`.  I will add it to the list of things to do before the release.

**Comment by apdd2003** [comment]
can I create custom event for line-edit? and then assign JS event to it as you suggested in previous post. That will be great if possible.

**Comment by almarklein** [comment]
Yes. There's two possibilities. In the simplest form, just change the line a bit to emit an event with a custum name. Note the "!" added in the reaction; it is there to suppress the warning the Flexx will give because it does not know that event.
```py 
        self.t1.node.onblur = lambda: self.t1.emit('myblurevent', {})

@event.reaction('!t1.myblurevent')
def _lineEdit_events(self, *events):
   ...
...
```

Or do it the "proper" way by subclassing and adding an emitter:
```py
class MyLineEdit(LineEdit):
    @emitter
    def myblurevent(self):
        """ docs here ..."""
        return {}
```

**Comment by apdd2003** [comment]
great! I got the behavior I wanted with the first method.

[test .txt](https://github.com/flexxui/flexx/files/1751824/test.txt)

I could not get it second subclassing method. Can you explain/wirte it with my code i am attaching here. Sorry if I  am bothering you too much, I am just keen to learn flexx.

**Comment by almarklein** [comment]
```py
from flexx import app, event, ui

class MyLineEdit(ui.LineEdit):
    
    def init(self):
        self.node.onblur = self.myblurevent
    
    @event.emitter
    def myblurevent(self):
        """ docs here ..."""
        return {}

class Example(ui.Widget):

    def init(self):
        with ui.FormLayout():
            ui.Widget(flex=.2)
            self.t1 = MyLineEdit(title='Amount:',style='width:30%;')
            ui.Widget(flex=.2)
            self.l2 = ui.Label(title='Note:')
            ui.Widget(flex=3)  

    @event.reaction('t1.myblurevent')
    def _lineEdit_events(self, *events):
        ev = events[-1]
        self.l2.set_text('Lost focus')

app.launch(Example)
app.run()
```

**Comment by almarklein** [comment]
I'd say the second method is preferred if you or other people are using this functionality in other places. Otherwise the first method is simply less code.

**Comment by apdd2003** [comment]
Thanks a lot. You can close this now. 
Off to build some flexx web apps now. Will post new issue if I get stuck....

Thanks again

**Comment by almarklein** [comment]
I'm leaving this open for now, since I think maybe LineEdit should submit on losing focus. 

> Will post new issue if I get stuck....

Please do :)

**Comment by apdd2003** [comment]
> I think maybe LineEdit should submit on losing focus.
That might conflict with form's submit button. Generally users click submit button after entering all details. If there are mulitiple LineEdits it may create problems. I may be wrong though.

**Comment by almarklein** [comment]
There are a few string methods that are not supported by PyScript, like encode/decode (because bytes are not supported), and also isdecimal and isdigit. I do not remember exactly why this is :/ If you really miss this method, please make a separate issue and I will look into it more closely.

**Comment by almarklein** [comment]
Closing. The `LineEdit` emits a `user_done` event when it loses focus. One can react to this event in addition to submit if necessary.
