### ISSUE TITLE
Fixed layout or responsive design?

### ISSUE THREAD

**Issue by Benoit9** [flexxui/flexx#456]
There is a mention of using ui.Div element to let "web developers do their thing" in [#177](https://github.com/flexxui/flexx/issues/177)

Is that the preferred or only way to achieve responsive design, with fixed layouts being the norm?

Or is there a plan to let the default widgets generate responsive html+css?

Thank you!

**Comment by almarklein** [comment]
That idea has been removed with the recent refactoring. Users who want a more web-dev way of working should implement the [`Widget._render_dom()`](http://flexx.readthedocs.io/en/latest/ui/widget.html#flexx.ui.Widget._render_dom) method.
