### ISSUE TITLE
i got problem before i  packet .py to .exe

### ISSUE THREAD

**Issue by ub3132003** [flexxui/flexx#472]
dose anyone packet this module to .exe . it's always cue that error

**Comment by almarklein** [comment]
Sorry, but your message does not have any information that helps target was is going wrong. In any way, freezing is not yet officially supported (see #260 and #433).

**Comment by ub3132003** [comment]
thanks. that's very helpful supported.  I guess the errors from packet relationship. I may con't use cx_freez or pyinstall in rigth way.

**Comment by almarklein** [comment]
Duplicate of #260

**Comment by almarklein** [comment]
Not yet, but issue #260 described the same issue; we'll be using that to track progress, and I closed this as being a duplicate.
