### ISSUE TITLE
Attaching custom properties to a tree item

### ISSUE THREAD

**Issue by blapp12** [flexxui/flexx#475]
I am trying to attach additional properties to tree item widgets. I have tried several different approaches. However, I have had the same issue with all of them. The property or attribute seems to "disappear" after creating the tree item. Upon debugging, the MyTreeItem object that is made initially is in a different memory location than the MyTreeItem object that is selected. This may be a fundamental misunderstanding that I have with the interplay between the Python and JS sides. 

I have included a simple example of my issue. Basically, I am dynamically adding a custom tree item to the tree widget. It has the py_comp attribute when it is initialized (print statement 1). When I then select the created tree item, it no longer has the py_comp attribute (print statement 2). 

Is there some fundamental reason why the object is changing? Do you have any alternative suggestions for attaching custom properties to widgets?

```py
from flexx import app, event, ui, flx

class Example(app.PyComponent):
    
    selected_item = event.AnyProp(settable=True)
    
    count = event.AnyProp(settable=True)
    
    def init(self):
        
        self.tree = flx.TreeWidget(flex=1, max_selected=1)
        
        self.js = JS_Example(self.tree, self)
        
    def add_tree_item(self):
        if self.count is not 1:
            with self.tree:
                MyTreeItem(PyMyTreeItem(), text='test')
            
        self.step_count(1)
        
    @event.action
    def step_count(self, val):
        self._mutate_count(1)

    @event.reaction('tree.pointer_down')
    def on_pointer_down(self, event):
        self.add_tree_item()
            
    @event.action
    def change_selected(self, selected):
        # Print statement 2
        print(hasattr(selected,'py_comp'))
        self._mutate_selected_item(selected)
        
                                    
class JS_Example(app.JsComponent):
    def init(self, tree, py_app):

        self.tree = tree
        self.py_app = py_app
            
    @event.reaction('!tree.children**.selected')
    def on_event_select(self, *events):
        for ev in events:
            self.py_app.change_selected(ev.source)


class MyTreeItem(ui.TreeItem):
    
    def init(self, py_comp):
        self.py_comp = py_comp
        # Print statement 1
        print(hasattr(self,'py_comp'))
        
        
class PyMyTreeItem(app.PyComponent):
    
    thing = event.AnyProp(settable=True)
    
    @event.action
    def change_properties(self, thing):
        self._mutate_thing(thing)
        

if __name__ == '__main__':
    example = app.launch(Example, 'chrome-browser', title = 'Example')
    app.run()
```

**Comment by almarklein** [comment]
Hi,

The tree item does have the `py_comp` attribute. But only in JS, because it's a simple attribute and not a property. The representation of that tree item in Python (in `change_selected()`) is a "proxy component". Such components have all actions and props of the real item, but not common attributes.

Try opening the dev browser console using F12 and typing: `flexx.s1.instances.MyTreeItem_5.py_comp`

I understand that this is confusing.

**Comment by blapp12** [comment]
Thank you. Attaching the PyComponent as a property solved the initial problem. However, I am now having issues accessing the "thing" property on the attached PyComponent. In "change_selected," the selected item now has the "py_comp" property. The "py_comp" property is a StubComponent though. Therefore, I cannot access the "thing"  property. It appears that the sessions are different, which causes the StubComponent representation of py_comp. It's unclear to me why the sessions are different or how to fix the issue. Do you have any recommendations?

**Comment by blapp12** [comment]
The above problem remains, but I solved my specific problem by using setattr() on the tree item itself. This requires the most up-to-date flexx package though. It did not work on the package from about 2 months ago.

**Comment by almarklein** [comment]
The interaction between Python and JS is a bit of a gray area, where it's relatively easy to do things wrong (or in ways that are relatively fragile); it requires more discipline than usual to do the right thing... You should think carefully about what you need and where.

In this case, I think you only need that `PyMyTreeItem` in Python, so it's probably best to just set it as a plain attribute of the tree item, but in Python:

```py
def add_tree_item(self):
        if self.count is not 1:
            with self.tree:
                tree_item = MyTreeItem(text='test')
                tree_item.py_comp = PyMyTreeItem()
```

What happens in your original example, is that `PyMyTreeItem()` instantiates the object, but is also cleaned up by the garbage collector right away; you need to store it in Python somehow.
