### ISSUE TITLE
Too many asyncio loops in chatroom.py

### ISSUE THREAD

**Issue by tbnorth** [flexxui/flexx#480]
`_update_participants()` in `chatroom.py` is run two ways, on a 2 second loop using `asyncio` and in response to `@flx.manager.reaction('connections_changed')`.  `connections_changed` must be called straight away, because `_update_participants()` is being called twice every two seconds, and adding a listener increases that to five times, two for each client and one for the first client responding to `connections_changed`, etc.

I'd be happy to submit a PR to fix it, but there are two ways it could be done, either (a) just guard the `asyncio...call_later()` line with `if not event:` or (b) drop asyncio all together and broadcast name change events the same way message events are broadcast.  (a) is a smaller change and retains the demonstration of the use of `asyncio`.

**Comment by almarklein** [comment]
I guess (b) is cleaner; its arguably not the best use-case of asyncio :)  PR welcome, but I'll be away for 3 weeks so probably wont be able to merge it until September :)

**Comment by tbnorth** [comment]
I'll make a PR for (b), no worries on the timeline :)
