### ISSUE TITLE
Can't use tree.children**.pointer_click on flx.PyComponent?

### ISSUE THREAD

**Issue by tbnorth** [flexxui/flexx#481]
I'm too new to Flexx to know if this is a bug or not, but it seems inconsistent.

This code:
```python
from flexx import flx

class Main(flx.PyComponent):
    def init(self):
        with flx.HBox(title='Test'):
            self.btn_exit = flx.Button(text="Exit")
            with flx.TreeWidget(flex=1, max_selected=1) as self.tree:
                self.branch = flx.TreeItem(title='A')

    @flx.reaction("btn_exit.pointer_click")
    def do_exit(self, *events):
        print("Button clicked")
        exit()
    @flx.reaction('branch.pointer_click')
    def click(self, *events):
        print("Item clicked", events[0].source)
    # @flx.reaction("!tree.children**.pointer_click")
    def click2(self, *events):
        print("Item clicked in tree")

if __name__ == '__main__':
    a = flx.App(Main)
    a.launch()
    flx.start()
```
works as expected unless the commented line is uncommented, in which case it fails to start with:
```
RuntimeError: Could not connect to '!tree.children**.pointer_click'
```
So setting a reaction on the `TreeItem` directly works, but setting it through `tree.children**` does not, *however* `tree.children**` does work in a class descending from `flx.Widget`, rather than `flx.PyComponent`.  I'm trying to make a file selector widget, which is why I wanted the reactions in a `PyComponent`, which can see the file system on the host.

I'm guessing tree only has .children on the JS side of the line, but I'm not sure if that's intended.

**Comment by almarklein** [comment]
I understand the confusion. I must admit that I felt somewhat surprised at first too. The reason for this is that `Widget.children` is a `LocalPropery`; it is not accessible from Python. This is to avoid a whole widget tree from "leaking into Python" when the root is present in Python.
