### ISSUE TITLE
Python JS interaction?

### ISSUE THREAD

**Issue by jrversteegh** [flexxui/flexx#482]
Sorry if this seems silly, but after the refactor I can no longer figure out how to create python only code for a widget. I've seen PyComponent, but can only find examples where it is the root of the App. Can you provide an example of a widget with python only code that is self contained and can be used like any other widget?

I used to do this like:
```
class Foo(Widget):
  """ python code """
  class JS:
     """ JS code """
```

What's the pattern for doing this in v0.5?

**Comment by almarklein** [comment]
Hi @jrversteegh, good question! It is no longer possible for a component to both have Python and JavaScript logic; it is *either* a PyComponent, or a JsComponent. This was done to promote a clearer separation between the Python logic and JS logic.

One pattern that I think works well is to have one main Widget class, and instantiate that in your main component (which will be a PyComponent). You can then add other PyComponents. For instance a py-based datastore (that can also be accessed from JS components using `self.root.store`).

```py

from flexx import flx

class Main(flx.PyComponent):
    def init(self):
        self.widget = MyWidget()
        self.store = Store()


class Store(flx.PyComponent):
    
    foo = flx.IntProp(42)
    
    def init(self):
        pass


class MyWidget(flx.Widget):
    
    def init(self):
        # Create your JS-based widgets here
        self.x = flx.Button(text='hi')


m = flx.launch(Main)
flx.run()

```

**Comment by jrversteegh** [comment]
OK.  I am not sure I completely understand though. To be a little more specific: I have a dateslider component. The slider component itself is javascript, but it is very dumb. It's basically unaware of the data type. It's just given a list of "tick" strings and it displays a slider bar with these ticks. The actual handling of the date range and number of ticks to display is done on the python side. Partly because I like datetime handling in python (and I like flexx, because I'm not fluent with Javascript ;) ), but more importantly because the date range is determined by server side data. So, how do I now connect the events from the JS side of the slider and PY side of the slider in a generic way? i.e. that doesn't depend on it's location in the "init" tree.

**Comment by almarklein** [comment]
I see your point. I think what would work best is something like this:

```py
from flexx import flx

class Main(flx.PyComponent):
    def init(self):
        with flx.HBox():
            self.x = flx.Button(text='hi')
            self.y = PySpecialSlider()
     
class PySpecialSlider(flx.PyComponent):
    
    def init(self):
        self.slider = SpecialSliderJsPart()
    
    @flx.reaction
    def xx(self):
        print(self.slider.value)

class SpecialSliderJsPart(flx.Slider):
    pass

m = flx.launch(Main)
flx.run()
```

The Python part would listen for reactions of the JS part, and would invoke actions on the JS part. These actions you'd need to implement in `SpecialSliderJsPart`. This gives you a model where the Python is "in control". It would also be possible for the JS part to listen to events, but it would need a reference to the PyComponent that it needs to react to.

**Comment by jrversteegh** [comment]
Everything is obvious, once you know the answer ;) I think I get it now. As long as it's PyComponents all the way down, I'll be fine. Previously my dateslider was part of a "compound" Widget, which is the part that no longer works (no instantiation of PyComponents from JS).
So my compound widget should also become a PyComponent with a Widget leaf instead. I'll have a go at that. Thank you for this answer and your hard work on this fantastic project!

**Comment by almarklein** [comment]
Great. It's good to get questions like this, to see what kind of issues users struggle with :)

The refactoring made things a lot better, but there is still a lot of room for confusion. Flexx let's you be very flexible in where you run code (Python or JS) and how you tie them together. This means though, that this is something that users need to think about for themselves. And be explicit about it in their code. We need much more documentation about what kinds of different patterns can be used, and which make sense in what situation.

**Comment by jrversteegh** [comment]
I don't think I need this: "It would also be possible for the JS part to listen to events, but it would need a reference to the PyComponent that it needs to react to". 
But just out of curiosity, can you point to an example for this? I couldn't get it to work. In the chatroom example the JS reacts to a global Relay PyComponent, but I didn't manage to react to anything else but a global.

**Comment by almarklein** [comment]
The trick is to get the pycomponent available in the JsComponent. E.g.
```
class WrapperWidget(flx.PyComponent):
    def init(self):
          self.widget = MyWidget(self)  # or some other pyComponent

class MyWidget(flx.Widget):
    def init(self, pycomp):
        self._pycomp
```

Another option, and maybe a better design is to access the root PyComponent (or a PyComponent that it references using a property), as is done in this example:
https://flexx.readthedocs.io/en/stable/guide/patterns.html#lean-towards-python

**Comment by jrversteegh** [comment]
Ah, passing to init. Of course. I just tried to set a reference, which doesn't work. Is the circular reference created by this automatically broken by the GC that you know? or is some extra action required?

**Comment by almarklein** [comment]
Note that setting the `self._pycomp` attribute only happens in JS. Garbage collection in Python happens as usual. References to PyComponents in JavaScript (or the proxy component to be precise) are destroyed when the real component (in Python) is deleted. All JSComponents need to be explicitly destroyed.

**Comment by jrversteegh** [comment]
Ah yes, of course. And I read that somewhere. Thanks.

**Comment by jrversteegh** [comment]
[Site](https://sail.orca-st.com/) is running again on new flexx :D

**Comment by almarklein** [comment]
Thanks for the link, it's very nice to see Flexx usage in the wild like this!

It seems that I should be able to create a route, but I haven't found out how to do that, or is it a WIP?

**Comment by jrversteegh** [comment]
The routing is a C++/Python hobby project that is certainly a WIP ;) Next up with flexx is creating an interface for entering the boat performance. The data is 2D: boatspeed = f(windangle, windspeed) and is usually presented in a [polar plot](http://bit.ly/2CxdhMf). Should be editable, uploadable and downloadable as CSV and preferably be stored client side (in a cookie?), so it's still there when you come back. Should keep me busy for a bit!

**Comment by almarklein** [comment]
Nice! I would not mind getting an update on that if there's progress :)
