### ISSUE TITLE
flexx is awesome

### ISSUE THREAD

**Issue by Konubinix** [flexxui/flexx#488]
Just wanted to tell you how much I appreciate flexx.

I have created a lot of small programs to help me in my daily life: a pomodoro timer application, a MUA, a music player, a photos gallery, etc.

I did not make the step to update to use the action/reaction mechanisms, but so far, flexx fit perfectly with what I have been looking for a loooong time: a library to quickly create application interfaces, that does not annoy me with a lot of configurations, and that I can debug very easily.

Thanks guys for flexx.

**Comment by Konubinix** [comment]
Of course, feel free to close this issue that is not really one. I did not know how to tell you this.

**Comment by almarklein** [comment]
I prefer to cherish it for a bit before closing :)
