### ISSUE TITLE
trying to integrate a database / RuntimeError: Database2 needs a session!

### ISSUE THREAD

**Issue by zappfinger** [flexxui/flexx#489]
I am trying to connect a form to a database, a very common practice on the web.
If I understand the docs correctly, my database code should live in a PyComponent object. So my idea was to populate some flexx variables there so that they can send events to the GUI part.
I tried to start the database part first, like so:
`if __name__ == '__main__':
    dbp = Database()
    m = flx.launch(ThemedForm, 'chrome-app')
    flx.run()` 

But I get this error: RuntimeError: Database2 needs a session!
I must be doing something wrong here...

**Comment by almarklein** [comment]
What you want to do looks a bit like [this section in the guide](https://flexx.readthedocs.io/en/stable/guide/patterns.html#use-of-a-central-data-store). In short. PyComponents also must be created in the context of a session. Something like so:
```py
class Database(PyComponent):
    ...

class MyApp(PyComponent):
    def init(self):
        self.db = Database()
        self.ui = ThemedForm()

flx.launch(MyApp)
```

**Comment by zappfinger** [comment]
I tried to follow the example but it does not work for me. The button in the form should trigger a change in the 'command' text object (residing in the database class), but it does not.

```
class ThemedForm(flx.Widget):
    .........
   @flx.reaction('but1.pointer_click')
    def but1_clicked(self, *events):
        self.b4.set_text('clicked')
        self.root.database.set_command('but1')

class Database(flx.PyComponent):  # Lives in Python
    print('in database')
    # triggers the query
    command = flx.StringProp(settable=True)
    # result back to form
    iddb = flx.IntProp(0, settable=True)

    csdb = db()

    @flx.reaction('command.text')
    def do_query(self, *events):
        print(self.command)
        instr = csdb.select("select rowid from templates where name ='Single with effects'")
        self._mutate_iddb(instr[0]['rowid'])

# if I change the base type to flx.Widget I get
# "Cannot instantiate a PyComponent from JS. "
class MyApp(flx.PyComponent):
    database = flx.ComponentProp()

    def init(self):
        self.ui = ThemedForm()
        self._mutate_database(Database())
```

**Comment by zappfinger** [comment]
Ok, that seems to work. But now for the final part: How do I get the result of the query back to the form?

**Comment by zappfinger** [comment]
I got it...

```
# in the form:
    @flx.reaction('root.database.iddb')
    def get_result(self, *events):
        print(self.root.database.iddb)
        self.b5.set_text(str(self.root.database.iddb))

class Database(flx.PyComponent):  # Lives in Python
    # result back to form
    iddb = flx.IntProp(0, settable=True)

```

This is great!

**Comment by almarklein** [comment]
Exactly! And notice how the database component stays completely unaware about the UI :)
