### ISSUE TITLE
Flexx releases in wheel format

### ISSUE THREAD

**Issue by LewisNeal** [flexxui/flexx#512]
Is there a plan to release v0.6 and v0.7 as wheel files?

**Comment by LewisNeal** [comment]
Apologies; for a new system _pip install flexx_ installed v0.7.0

On another PC with an older version of flexx, running _pip list --outdated_ reports:
Package Version Latest Type
------- ------- ------ -----
flexx   0.4.1   0.7.0  sdist

I mistakenly thought 0.7.0 was not available.

**Comment by almarklein** [comment]
Still might be good to upload wheels to pypi though :)
