### ISSUE TITLE
Ace example fails for PyComponent

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#513]
Hello all.  Just discovered flexx.  It's a super tool.  It should be perfect for making [Leo a web app](https://groups.google.com/forum/#!topic/leo-editor/vzkmh7GhW9k). 

The [ace editor example](https://flexx.readthedocs.io/en/stable/examples/editor_ace_src.html#editor-ace-py) works fine for me.  [leoflexx.py](https://github.com/leo-editor/leo-editor/blob/skeleton/leo/plugins/leoflexx.py) is a stand-alone test. However, setting
`lean_python = True`
in leoflexx.py that is, replacing:
`class CodeEditor(flx.Widget):`
by:
`class CodeEditor(flx.PyComponent):`
fails with:
```python
File "c:\leo.repo\leo-editor\leo\plugins\leoflexx.py", line 113, in init
    self.ace = window.ace.edit(self.node, "editor")
NameError: name 'window' is not defined
```
If I then replace:
`global window`
with
`from pscript import window`
the end of the traceback is:
```python
 File "c:\leo.repo\leo-editor\leo\plugins\leoflexx.py", line 113, in init
    self.ace = window.ace.edit(self.node, "editor")
AttributeError: 'JSConstant' object has no attribute 'ace'
```
What should I do?

Edward

**Comment by almarklein** [comment]
Parametrizing whether a class is  PyComponent or a JsComponent (like a Widget) is probably a bad idea :)

By making it a PyComponent, the instance operates in Python; indeed there is no Window there. If you need to do things in Python, you want to draw a clear line between the Python and JS functionality. Python-side goes in one ore more PyComponent classes, and everything else using JsComponents (e.g. Widgets). Also see the last three sections in [this guide](https://flexx.readthedocs.io/en/stable/guide/patterns.html).

**Comment by almarklein** [comment]
BTW: Interesting take on moving Leo to the web :)

**Comment by edreamleo** [comment]
@almarklein The base_class parameter is only a convenience during prototype.  Eventually (soon) all classes will derive from object, flx.Widget or flx.PyComponent.

I was thinking of the Sensible Usage Patterns when I wrote this issue.  Leaning "away" from Python does work, but it's clumsy.  The hack that I have adopted is to use top-level functions to translate some of Leo's complex classes into serializable lists.  Using functions seems necessary.  Iirc, putting these functions into a class causes pscript to collect the class into JS, which then fails because JS can't access Leo's c class.

I was thinking that if there were a way to lean "towards" Python in a class (PyComponent) that _uses_ flx.Widgets the PyComponent class could encapsulate the required translations to/from python and JS.

One last try: is there any way to use rawJS to get a real JS window inside a PyComponent? From your reply, I suspect that this question doesn't make sense, maybe because PyComponent doesn't get turned into JS.

Thanks for your reply.  I'm super impressed with flexx and pscript.

**Comment by edreamleo** [comment]
[This post on leo-editor](https://groups.google.com/d/msg/leo-editor/qb_MTgt47dI/8054O36mAAAJ) summarizes what I think I know about flexx and pscript.  Any corrections would be greatly appreciated.

**Comment by almarklein** [comment]
>  is there any way to use rawJS to get a real JS window inside a PyComponent? From your reply, I suspect that this question doesn't make sense, maybe because PyComponent doesn't get turned into JS.

Indeed a PyComponent is not converted at all. But you can instantiate JsComponents and use their properties and actions. You could thus do something like this:
```py
class MyPyClass(flx.PyComponent):
    def init(self):
        self.widget = MyWidgetClass()
        self.myjs = MyJsComponent()
```

**Comment by almarklein** [comment]
> This post on leo-editor summarizes what I think I know about flexx and pscript. Any corrections would be greatly appreciated.

> No subclasses of flx.Widget can [...], because the code is actually JS.

Yeah ... this pinpoints Flexx' weak spot; it makes writing Js classes so familiar that confusion arises :/  I'd recommend to separate the two as good as you can. Be explicit in comments / docstrings. Probably don't mix the two in a single module.

> No subclasses of flx.Widget can possibly access Leo's c or p classes [...]

Well, not directly. A PyComponent could function as a sort of proxy.

**Comment by edreamleo** [comment]
Thanks for all your help and for flexx, pscript and pyzo.  I am going to close this issue.
