### ISSUE TITLE
Document direct calls to actions

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#518]
Imo, this is an urgent action item, for at least three reasons:

1. This is probably the single coolest feature I've ever seen in any piece of software.

Come on man.  I can't believe you have hidden this amazing feature.  It's way cooler than the init magic.

2. There is *no way* a newbie could discover this on their own.

Unless you count searching the issues ;-)

I spent most of yesterday messing with components, actions, reactions and emitters without coming close.  Indeed, **all the docs lead *away* from the answer**.  Recall that I mentioned in #516 that trying to use globals for communication was laughable.  Well, the laugh's on me, because direct calls to actions look like pretty much the same thing!

3. Even now, knowing that this feature *is* possible, I have no clue *how* it is possible.

Really.  Maybe the symmetry between proxies has something to do with it, but that's a guess.

**Summary**

Almar, you have managed to hide one of the coolest software features I have ever ever seen. You should be bragging about it wherever possible.

I would love to see a "Theory of operation" section somewhere in the the docs. If it only explained how direct calls to actions work it would be worth doing.

I have just updated the second comment in #517 to illustrate the working prototype that leoflexx.py uses.

**Comment by almarklein** [comment]
Haha, thanks for this feedback! I've added some points to #516. Keep it coming :)

**Comment by edreamleo** [comment]
On Mon, Nov 12, 2018 at 2:41 AM Almar Klein <notifications@github.com>
wrote:

> Haha, thanks for this feedback! I've added some points to #516
> <https://github.com/flexxui/flexx/issues/516>. Keep it coming :)
>
Glad to hear the feedback is useful for you.

Edward
