### ISSUE TITLE
flx.TreeWidget.highlight_get() fails

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#519]
Within a subclass of flx.TreeWidget, a call to self.highlight_get() fails:
```
JS: TypeError: this.highlight_get is not a function - stack trace in browser console (hit F12).
```
In the console:
```
TypeError: this.highlight_get is not a function
$LeoTree.populate_children @ http://localhost:49190/flexx/assets/shared/__main__.js:450:5
receive_children @ http://localhost:49190/flexx/assets/shared/__main__.js:479:5
```
This is a minor issue, because it is dead easy to track this and other tree-related data by hand.

**Comment by almarklein** [comment]
I cannot reproduce this. Could you perhaps provide a minimal example? Or could it perhaps be that you were calling this on a TreeItem instead of a TreeWidget?

**Comment by edreamleo** [comment]
On Mon, Dec 3, 2018 at 9:38 AM Almar Klein <notifications@github.com> wrote:

> I cannot reproduce this. Could you perhaps provide a minimal example? Or
> could it perhaps be that you were calling this on a TreeItem instead of a
> TreeWidget?
>
No way of telling now.  I have just managed to kill almost the entire git
history of the relevant branch.  Not sure how.  It's pretty upsetting.

Edward

**Comment by almarklein** [comment]
Ok, no rush!

**Comment by edreamleo** [comment]
I am going to close this.  `JS: TypeError: this.highlight_get is not a function` looks like a newbie mistake.
