### ISSUE TITLE
FYI: First draft of LeoWapp theory of operation

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#521]
It's [here](https://groups.google.com/forum/#!topic/leo-editor/1AD-2NWuDds). It discusses, at various levels of detail (and understanding!) everything I've done in the past week or so.  It will be pre-writing for LeoWapp's theory of operation.

Almar, I would appreciate any comments or corrections.

**Comment by edreamleo** [comment]
And [here](https://groups.google.com/forum/#!topic/leo-editor/HYQXVgmGFyA) and [here](https://groups.google.com/forum/#!topic/leo-editor/SbGoMnq6FKk) are two discussions of why flexx is important.  As you can see, there is great interest.

Any comments you might have would be most welcome here or on [leo-editor](https://groups.google.com/forum/#!forum/leo-editor).

**Comment by almarklein** [comment]
Thanks for the update. I know nothing of Leo's internals, so I have just a few comments:

* About publish subscribe: this pattern can be implemented either by making a property or emitter to represent the publisher, and reactions to represent the subscribers. Yes you can react to events from emitters across the boundary. Flexx keeps track of whether this is the case and only sends events over the websocket when there are listeners on the other side.
* About properties vs normal arguments: use properties if you want to be able to observe it (with reactions) or when you want to be able to access it across the boundary. Or maybe if you just want to make use of the value validation of Flexx properties.
* About passing things at startup: You probably want to take care of this inside the `init()` of the root component. BTW, you can pass arguments to `RootComp.init(a, b)` using `flx.App(RootComp, a, b).launch()`. See [the docs](https://flexx.readthedocs.io/en/stable/app/api.html#flexx.app.App).

**Comment by edreamleo** [comment]
@almarklein Thanks for these comments.  Most of them are consonant with the present leoflexx.py code base, but it's so useful to have your high-level overview. I'll play with flx.emitter soon.

"I know nothing of Leo's internals"

Heh.  Neither does the JS side of leoflexx.py!  The JS side only knows how to redraw the screen from dicts.  
These dicts contain other dicts (archived positions) representing nodes in Leo's tree. However, the JS side merely passes the archived position back to the Python side.
