### ISSUE TITLE
Better documentation of get_active_component()

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#522]
This class:
```python
class Root(flx.PyComponent):
    '''This class allows *plain* python classes to access *component* classes.'''
    def __getattr__ (self, attr):
        return getattr(self.root, attr)
```
allows *plain* (non-component) python classes to access flx.actions on either side of the Py/JS divide! Full details [here](https://groups.google.com/d/msg/leo-editor/NyORPl1G2xE/-81lAD1-BgAJ).

Imo, every flexx programmer should know about Root.  It will be an essential part of LeoWapp.

**Comment by almarklein** [comment]
I'm not sure I understand. plain classes have also been able to do that using `a_component_instance.root.xx`, right?

**Comment by edreamleo** [comment]
@almarklein Thanks for this comment.  I'm not sure you are completely correct.

If a plain class instantiates any component c, then yes, it can ( think) use it to access c.root.whatever.  However, the Root component is useful in those cases where it is not otherwise natural to instantiate a component.

Moreover, the Root component I gave appears to be the minimal flx.PyComponent that will get the job done.  For instance, this fails:
```python
class Root(flx.PyComponent):
    pass
```
The traceback is:
```python
[E 16:47:39 flexx.event] AttributeError: 'Root' object has no attribute 'select_p'
  File "c:\Anaconda3\lib\site-packages\flexx\event\_loop.py", line 327, in _process_actions
    action(*args)
  File "c:\Anaconda3\lib\site-packages\flexx\event\_action.py", line 154, in __call__
    res = func(ob, *args)
  File "c:\leo.repo\leo-editor\leo\plugins\leoflexx.py", line 99, in do_command
    self.gui.frame.tree.select(p)
  File "c:\leo.repo\leo-editor\leo\plugins\leoflexx.py", line 538, in select
    self.root.select_p(p)
```
Does this make sense to you?

**Comment by edreamleo** [comment]
I have just experimented with ways of avoiding the Root class.  All failed. Imo, Root is a great trick.

**Comment by almarklein** [comment]
> Does this make sense to you?

Sorry, no, I don't get it :) What you have written in the first comment is essentially a proxy to the root class, and I don't see the point. Can you maybe show how you instantiate and use that class?

**Comment by edreamleo** [comment]
> Sorry, no, I don't get it :) What you have written in the first comment is essentially a proxy to the root class, and I don't see the point. Can you maybe show how you instantiate and use that class?

No problem.  I'll explain in detail.

The short answer is that it isn't easy to pass a proxy at startup (init) time.  The Root class is the *only* answer I have found. 

**Background**

Like all apps, users affect gui widgets by their actions: mouse clicks, key presses, etc.  Unlike every other app I know of, all of Leo's gui widgets are programmable.  That is Leo *itself* (that is, code in Leo's core) can "drive" widgets: changing their contents, inserting or deleting them, etc.  In particular, Leo is the acid test of any Tree widget.  Flexx passes these tests with flying colors.

**Leo's wrapper classes**

Leo's core knows nothing about what gui is in effect.  Instead, Leo's core is written to the so-called High-Level API.  For each gui, Leo's **wrapper classes** implement the api for the particular gui. The wrapper classes *parallel* the actual flexx widgets.  There is a gui wrapper, a frame wrapper, and wrappers for each component of the frame.

**Leo's wrapper classes can not be flexx components**

Because flexx requires single inheritance, making wrapper classes would be horrible.  Wrappers would have to contain copies of all the code in the (chain of) super classes.  I actually did this before I realized that wrappers could use a proxy rather than being a flx.PyComponent.  With a proxy, Leo's wrapper classes are subclasses, so they contain just a few overrides.

**The problem is initialization**

Afaik, the Root class is the only way to create the proxies you speak of.  Initialization of the flx.Widgets is then completely separate from creating the wrappers.  Initialization can be done in any order.

Here, stripped to its essential, is LeoBrowserApp.init:
```python
class LeoBrowserApp(flx.PyComponent):
    main_window = flx.ComponentProp(settable=True)
    def init(self):
        self.gui = LeoBrowserGui()
            # Instantiates all wrappers
        main_window = LeoFlexxMainWindow(...)
        self._mutate('main_window', main_window)
```
The problem I have never solved is how to pass the main_window property to the *plain python* wrappers? In particular, it seems that we need an "after init" time, at which time all the flexx components will have been mutated.  But there is no such time.

**Summary**

I hit upon the Root class only after hours and hours of failed experiments.  If you know of an easy way to pass a proxy to the wrappers, please tell me.  However, I'm not looking for anything better than Root().

Edward

**Comment by almarklein** [comment]
Thanks for the clarification. I see your point now. Basically, you need some "global way" to get to that root object. The `Root` class helps, because when it instantiates, it is going to look it up. What it does (and what you could do) is use [flx.loop.get_active_component()](https://flexx.readthedocs.io/en/stable/event/api.html#flexx.event.Loop.get_active_component), and use `.root` on that to get the root object.

**Comment by almarklein** [comment]
I also see how this functionality is rather buried in the docs, so I should add some links in the right places, and make a not in the guide on how this works. Leaving this issue open for this.

**Comment by edreamleo** [comment]
On Wed, Nov 21, 2018 at 2:59 AM Almar Klein <notifications@github.com>
wrote:

> Thanks for the clarification. I see your point now. Basically, you need
> some "global way" to get to that root object.
>
Exactly.

> The Root class helps, because when it instantiates, it is going to look
> it up. What it does (and what you could do) is use
> flx.loop.get_active_component()
> <https://flexx.readthedocs.io/en/stable/event/api.html#flexx.event.Loop.get_active_component>,
> and use .root on that to get the root object.
>
Nice.  This looks straightforward enough.

Edward

**Comment by edreamleo** [comment]
On Wed, Nov 21, 2018 at 3:00 AM Almar Klein <notifications@github.com>
wrote:

> I also see how this functionality is rather buried in the docs, so I
> should add some links in the right places, and make a not in the guide on
> how this works. Leaving this issue open for this.
>
Yeah, flx.loop.get_active_component().root is a super important trick to
know.

I've replaced the Root class with a get_root helper that returns the root.
All is well.

Edward
