### ISSUE TITLE
How to put focus in a widget? Was: how to generate a pointer_click?

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#526]
Another item for the "things that confused this newbie" list.

In want to set the focus to a flx.Widget.  Alas, this does nothing except print the message:
```python
@flx.action
def set_focus(self):
    print('===== flx.log.set_focus')
    self.emit('pointer_click')
```
What should I do? Thanks.

**Comment by edreamleo** [comment]
Never mind.  emit is working just fine.  The problem is that the focus must be set to the ace editor, not the pane.  My apologies for the noise.

**Comment by edreamleo** [comment]
I am going to reopen this.  Although the answer for ace widgets is obvious, the answer for, say, a LineEdit, eludes me.  This is what I have tried:
```python
@flx.action
def set_focus(self):
    print('flx.minibuffer.set_focus', repr(self.widget))
        # self.widget is a flx.LineEdit.
    # https://flexx.readthedocs.io/en/stable/ui/widget.html#flexx.ui.Widget.pointer_click
    # See also: Widget._create_pointer_event.
    e = {
        'button': 0,
        'buttons': [],
        'modifiers': [],
        'page_pos': (0.0, 0.0),
        'pos': (0.0, 0.0),
        'touches': {-1: 1},
    }
    if 0: # Crashes.
        self.widget.pointer_click(e)
    else: # Doesn't work.
        self.widget.emit('pointer_click', e)
```
What should I do?

**Comment by almarklein** [comment]
I would not recommend simulating a pointer click. There is usually a better solution to your problem. If you want to bring focus to a widget, just use `somewidget.node.focus()`. Note that the `tabindex` property must be not `None` for this to work. Welcome to the world of JS :D

**Comment by edreamleo** [comment]
On Fri, Nov 23, 2018 at 4:59 AM Almar Klein <notifications@github.com>
wrote:

> I would not recommend simulating a pointer click. There is usually a
> better solution to your problem. If you want to bring focus to a widget,
> just use somewidget.node.focus().
>
Excellent!

> Note that the tabindex property must be not None for this to work.
> Welcome to the world of JS :D
>
Hehe. I don't believe I have ever been more excited in my programming life.

Edward
