### ISSUE TITLE
Server does not shutdown gracefully when interrupted (on Windows)

### ISSUE THREAD

**Issue by almarklein** [flexxui/flexx#529]
As reported in https://github.com/flexxui/flexx/issues/525#issuecomment-440926361, the running server, when interrupted either:

* stops like it should.
* stops with an error (File "..\python37\lib\selectors.py", line 314, in _select).
* does not stop until a connection is made, and then does the above.

(I am able to reproduce this with both `flx.run()` and `flx.start()`. Maybe something changed in Tornado or asyncio, breaking our use of it?

**Comment by maphew** [comment]
FYI, on Windows `ctrl-c` and `ctrl-break` are different, ([ms ref](https://docs.microsoft.com/en-us/windows/console/ctrl-c-and-ctrl-break-signals)). I didn't find what looks like an idiomatic python handling method. there is this though:

- https://stackoverflow.com/questions/24426451/how-to-terminate-loop-gracefully-when-ctrlc-was-pressed-in-python
- https://stackoverflow.com/a/1364409/14420
- https://mail.python.org/pipermail/python-dev/2017-August/148800.html (explains why it's not straightforward)
