### ISSUE TITLE
Document init pattern

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#531]
The following pattern eliminates the need for init args to be passed to flx.Widgets:
```python
do_init = flx.BoolProp(settable=True)

def init(self): # no need for args
    ...
    self._mutate('do_init', True)

@flx.reaction('do_init', mode="greedy")
def after_init(self):
    self.root.call_py_side_callback()
```
In effect, the after_init method defines an "after-init" time. It is the Yellow Box finishCreate pattern.

**Discussion**

The PY side typically has access to data not available to the JS side.  This pattern allows PY side callbacks to execute *after all flx.Widgets are fully inited*.  Each PY side callback calls JS side code to complete the initialization of a *single* flx.Widget. For example, LeoWapp's log pane widget uses this pattern to put the signon message into the log widget.

This pattern gives me great joy:

- It simplifies all init methods. They need no args that must be passed down the call chain. Pylint approves.

- PY side callbacks are simple and easy to understand.

- The app.init method now knows nothing about the flx.Widgets. Only the PY side callbacks know how to init the JS widgets.

Edward

P. S. As I write this, I see that a single PY side callback would suffice, called by the top-level flx.Widget.

EKR

**Comment by almarklein** [comment]
I understand the need for a pattern like this, and would like to document it somewhere. But the syntax now feels a bit awkward. Would `flx.loop.call_soon(self.after_init)` also work?

**Comment by edreamleo** [comment]
On Mon, Dec 3, 2018 at 9:44 AM Almar Klein <notifications@github.com> wrote:

> I understand the need for a pattern like this, and would like to document
> it somewhere. But the syntax now feels a bit awkward. Would
> flx.loop.call_soon(self.after_init) also work?
>
Yes, I suppose it would.  What's important is that people understand that
there is a way to execute code after all flx.Widget's have been inited.

I don't really understand why you say the syntax is awkward.  You could say
the _mutate *pattern* is awkward, but surely that can't be changed.

Edward

**Comment by Konubinix** [comment]
I do a very similar pattern in half my projects. It's good to know that it is not only my use case :-)

@edreamleo , I think it is ackward to, but more semantically. You create a variable but you won't use its value. It is only meant to trigger the event that the init is done.

I think you could also simply trigger the event, using something like this :+1: 
```
def init(self): # no need for args
    ...
    self.emit('do_init')

@flx.reaction('!do_init')
def after_init(self):
    self.root.call_py_side_callback()
```

I think this version convey more precisely what you want to do: run something after the init "action" step.
The main difference with the one suggested by @almarklein is that with events, you can put the reaction everywhere in your code, even in the JS side, while the call_soon indicate that this more a defering of the code of the init, not a real event.

**Comment by almarklein** [comment]
> I don't really understand why you say the syntax is awkward. 

Yeah sorry, I meant the higher level way of writing it down. @Konubinix put it much better :)

I like the `self.emit('do_init')` too, maybe better than `flx.loop.call_soon()` because its self-contained and would also work for JSComponents (even though you probably don't need it there).
