### ISSUE TITLE
How to get reactions from ace (or cm)

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#535]
~~This is a make or break issue for LeoWapp.~~ There is a good workaround: see the first comment below.

Given the code for the [ace demo](https://flexx.readthedocs.io/en/stable/examples/editor_ace_src.html#editor-ace-py), how can I get a changed event?  This never fires:
```python
@flx.reaction('change') # or 'changed' or 'onchange' or 'ace'
def editor_change(self, *events):
    print('===== Body: on changed')
```
Changing the selection string to any of the following creates a 'can not connect' error:
ace.change, ace.editor, ace.editor.change, on.change, editor.change, editor.session.change.

Any suggestions? Thanks.

**Comment by edreamleo** [comment]
I'd still like an answer, but a nifty workaround has appeared.

With both ace and cm, the JS editor's text has *already changed* when the key handler fires.  So the key handler _itself_ could be considered the desired reaction.

Similarly (not tested yet) an on-user-click handler should be able to update insert points.

**Comment by edreamleo** [comment]
This issue can be closed from my point of view.

However, it is shocking that the key_press and pointer_click reactions get called *after* the JS editor has been updated.  Marvelous, just what is wanted, but shocking.  Shouldn't this be documented?

**Comment by almarklein** [comment]
This is due to how the event system works in Flexx. A native JS key/pointer event emits a Flexx key/pointer event, and the reactions that are connected to this event always get processed asynchronously (i.e. later).

In cases where you need to take direct action, you should use the native JS events instead.

**Comment by almarklein** [comment]
So For Leo, I imagine that mos high level stuff can be dealt with using Flexx mechanics, but for the low-level stuff you probably want to use JS native mechanics directly.
