### ISSUE TITLE
is flexx restful?

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#537]
[Joe Orr](https://github.com/kaleguy) is one of Leo's most important users, and the author of [LeoVue](https://github.com/kaleguy/leovue). Scroll to the bottom for an amazing demo.  My goal with flexx has always been to meld LeoVue into LeoWapp. However, Joe suggests not using flexx because flexx isn't restful.

I know essentially nothing about restful web services, but from my untutored view it would seem that flexx can do anything that can be done in JS.  Furthermore, the restful requirements seem to apply to low-level interactions via sockets.  I don't understand how low-level problems would "bleed" into problems for flexx.

What do you suggest I say to Joe?  Thanks.

Edward

I have just created [this thread](https://groups.google.com/forum/#!topic/leo-editor/FcxMnHLHsGs) on leo-editor to discuss this question.

**Comment by Korijn** [comment]
Flexx is intended to build GUIs. It sounds like Joe is looking for a traditional WSGI or ASGI backend that exposes an API for LeoVue to integrate with. I don't think flexx was designed for that purpose.

**Comment by edreamleo** [comment]
On Sun, Dec 9, 2018 at 7:35 AM Korijn van Golen <notifications@github.com>
wrote:

> Flexx is intended to build GUIs. It sounds like Joe is looking for a
> traditional WSGI or ASGI backend that exposes an API for LeoVue to
> integrate with. I don't think flexx was designed for that purpose.
>
Thanks for your comment.  Time to look up WSGI and ASGI ;-)

Edward

**Comment by edreamleo** [comment]
On Sun, Dec 9, 2018 at 10:21 AM Korijn van Golen <notifications@github.com>
wrote:

> If you prefer learning by example, give this tutorial a go:
> https://blog.miguelgrinberg.com/post/designing-a-restful-api-with-python-and-flask
>

Thanks.  This look helpful.

Edward

**Comment by edreamleo** [comment]
@Konubinix Thanks for your comments, Samuel. They are most helpful.

The present LeoWapp project, based on flexx, is clearly the simplest thing that could possibly work.  I can say that with certainty because I have lots of experience with making gui's for Leo.

Joe is a JS guru, so I can't evaluate his thinking.  I'll press him to explain his reasoning before starting a second project based, say, on flask.  For sure, LeoWapp can stand on its own.

**Comment by almarklein** [comment]
I agree with @Konubinix's comments above.

It's worth noting that you can use Flexx *and* have a classic web API (Restful if you want). In such a scenario, you would write only the UI elements in Flexx. No server parts. Then you "export" that with `flx.App.dump()`, and serve these assets with a normal web server.

The advantage of this approach is that you have the much loser coupling of server and client, and it scales to many more simultaneous users. The downside is that you'll need to implement the communication between server and client yourself using `XMLHttpRequest` calls.

**Comment by edreamleo** [comment]
Thanks, Samuel and Almar, for your comments.  I am convinced that flexx is the proper platform for the LeoWapp project.  There will be some work involved in integrating what Joe Orr has done, but that's for later, and is not your concern.
