### ISSUE TITLE
Standardize logger line/output that indicates flexx is ready and serving app(s) 

### ISSUE THREAD

**Issue by aars** [flexxui/flexx#539]
We're running a Flexx application inside Electron by spawning a child process that runs python/Flexx in nodejs. We monitor Flexx logging output to determine if Flexx is ready and serving so we can navigate to it in our Electron wrapper. It looks like this:
```js
const flexxServerUrlRegExp = /Serving apps at (.+)/g; // Match Flexx log line containing server url.
python_process.stdout.on('data', (data) => {
  const line = data.toString();
  const match = flexxServerUrlRegExp.exec(line);
  if (match !== null) {
    // Flexx is ready!
    callback(url.parse(match[1]));
  }
});
```

It might be useful to standardize that output line so it can be relied upon across versions and releases.

**Comment by almarklein** [comment]
Fixed by #540
