### ISSUE TITLE
How to set Widget name for document.getElementByName?

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#541]
I am now trying to follow the suggestion in #535 to use JS key handlers rather than flexx handlers.

The following apparently does not set the name of the ace instance to "editor":
```python
ace = window.ace.edit(node, 'editor')
```
What should I do? Any other suggestions for creating JS key handlers?

Edward

**Comment by edreamleo** [comment]
Quite a bit of sleuthing reveals that getElementsByTagName("TEXTAREA") returns all ace widgets. The following, enclosed in RawJS, suffices to attach a handler:
```javascript
var x = document.getElementsByTagName("TEXTAREA");
for (var i = 0; i < x.length; i++) {
    x[i].onkeypress = function(){
        alert("KEY PRESSED");
    }
}
```
The next step will be to communicate (somehow!) the key press to the PY side.

**Comment by almarklein** [comment]
You mean this suggestion:

> This is due to how the event system works in Flexx. A native JS key/pointer event emits a Flexx key/pointer event, and the reactions that are connected to this event always get processed asynchronously (i.e. later).
>
> In cases where you need to take direct action, you should use the native JS events instead.

But now you say:

> The next step will be to communicate (somehow!) the key press to the PY side.

If you want to process the keys at the Python side, Python will receive the keys async by definition, and there is probably no need to use raw JS events. In fact, to send the key events to Python, I would suggest to create an emitter at the JS side to convert the raw events to Flexx events, such that you can connect to them in Python. But this is exactly what Flexx already does for its own key events :)

**Comment by edreamleo** [comment]
On Fri, Dec 14, 2018 at 3:41 AM Almar Klein <notifications@github.com>
wrote:

> You mean this suggestion:
>
> This is due to how the event system works in Flexx. A native JS
> key/pointer event emits a Flexx key/pointer event, and the reactions that
> are connected to this event always get processed asynchronously (i.e.
> later).
>
> In cases where you need to take direct action, you should use the native
> JS events instead.
>
> Yes.  That was the suggestion I meant.

> But now you say:
>
> The next step will be to communicate (somehow!) the key press to the PY
> side.
>
> If you want to process the keys at the Python side, Python will receive
> the keys async by definition, and there is probably no need to use raw JS
> events. In fact, to send the key events to Python, I would suggest to
> create an emitter at the JS side to convert the raw events to Flexx events,
> such that you can connect to them in Python. But this is exactly what Flexx
> already does for its own key events :)
>
Let me clarify what I am trying to do.

*The problem*

Leo's internal (Python) data model must match what is in the ace editor at
certain times.

*Always *keeping the model in sync would be best, but as I write this I see
there is a workaround.  See below.

To keep Leo's data model *always* in sync, it seems that I must do the
following:

1. Catch *all* ace keystrokes.  Afaik, the only way to do this is to
create, using RawJS, an onkeypress handler, as I described previously.

2. Have the onkeypress handler update the Python data model.  I have no
idea how to do this. Indeed onkeypress lives in a different world than
flexx components. So I am well and truly stuck.  If you know a way for
onkeypress to communicate with a flexx component, please let me know.

*Workaround*

As I write this reply, I see that synchronizing the Python data model with
the ace contents must be done *only at certain specific times*, for
example, when selecting a new outline node and when executing a Leo command.

Synchronization will involve a back and forth between actions on the PY and
JS sides of Leo's flexx widgets, similar to what already happens when
selecting a new node. This will complicate the code a little bit, but not
significantly.

*Summary*

I know of no way to keep Leo's data model up to date on a
keystroke-by-keystroke basis.

Happily, it should suffice to synchronize the data model only at a few
crucial times. This is what I'll attempt next.

Edward

**Comment by almarklein** [comment]
To answer the question in the title: every Flexx component has an `id`. You can type `window.flexx.s1.instances.xxx` in the browser console to see all objects by id. You could potentially also "recover" objects this way. One could also do `self.node.setAttribute("id", self.id)`, so that `document.getElementById(..)` would work.
