### ISSUE TITLE
Help needed: Flexx and watchdog

### ISSUE THREAD

**Issue by beeb** [flexxui/flexx#544]
Hello all,

I'm posting here since my [question on SO](https://stackoverflow.com/questions/55027872/flexx-for-python-how-to-get-pycomponent-instance-outside-of-the-app-context-wa) doesn't seem so popular and there is very little going on about flexx there (which is probably good!).

I hope this is allowed and if not, then feel free to delete this issue.

I am using [`watchdog`](https://github.com/gorakhargosh/watchdog) to monitor for new files inside a directory. This library calls for an event handler (subclass of their `FileSystemEventHandler`) which I inherit from. In my event handler method (which gets triggered when a new file is created), I would like to call a `PyComponent`'s method in order to mutate its state.

So far I've found that I can get a reference to the app's root component instance with `from flexx.app import manager; manager.get_connections('MyAppName')[0].app` but if I try to call one of its methods, I get the following trace:

	  File "myfile.py", line 37, in on_created
	    manager.get_connections('MyAppName')[0].app.update_verbose(False)
	  File "lib\site-packages\flexx\event\_action.py", line 150, in __call__
	    if loop.can_mutate(ob):
	  File "lib\site-packages\flexx\event\_loop.py", line 85, in can_mutate
	    active = self.get_active_component()
	  File "lib\site-packages\flexx\event\_loop.py", line 103, in get_active_component
	    if len(self._local._active_components) > 0:
	AttributeError: '_thread._local' object has no attribute '_active_components'

Note that `update_verbose` is decorated with `@flx.action`.

I tried a different approach where instead of subclassing `FileSystemEventHandler` I was subclassing `flx.PyComponent` and re-implementing the methods required for watchdog (and instantiating this event handler from my main `PyComponent`'s init function), but it didn't help, the stack trace was essentially the same.

Any help will be greatly appreciated! Thanks

**Comment by almarklein** [comment]
Yes, you are allowed and encouraged to post questions here :)

The direction that you are taking could work, but is probably not what you want. If you have a desktop application, it's easy:
```py
root = flx.launch(MyPyComponent)  # there is your instance!
```

If you are making more of a web server, it's probably easiest to make use of a regular `Component`. These are unaware of any Py-JS syncing, so they can be instantiated as a global object. But because they are components, they can be hooked up to PyComponents. Something like this:

```py
from flexx import flx

class GlobalComp(flx.Component):
    
    foo = flx.StringProp("hello", settable=True)


global_instance = GlobalComp()


class PyComp(flx.PyComponent):
    
    def init(self):
        
        self.label = flx.Label()
    
    @flx.reaction
    def _update_foo(self):
        self.label.set_text(global_instance.foo)

if __name__ == "__main__":
    flx.serve(PyComp)
    flx.run()
```

**Comment by beeb** [comment]
Hey, thanks for the quick reply! It's indeed a desktop app, so I tried getting the root instance from the `launch` call and the result is the same:

AttributeError: '_thread._local' object has no attribute '_active_components'

I think the core of the problem is that the `FileSystemEventHandler` is running on a different thread maybe? Is it weird that `self` in `self._local._active_components` is actually `_thread` or is that normal?

	  File "myfile.py", line 36, in on_created
	    root.update_test('asdf')
	  File "lib\site-packages\flexx\event\_action.py", line 150, in __call__
	    if loop.can_mutate(ob):
	  File "lib\site-packages\flexx\event\_loop.py", line 85, in can_mutate
	    active = self.get_active_component()
	  File "lib\site-packages\flexx\event\_loop.py", line 103, in get_active_component
	    if len(self._local._active_components) > 0:
	AttributeError: '_thread._local' object has no attribute '_active_components'

**Comment by almarklein** [comment]
Not `self` but the `_local` of a `Loop` object stores active components per thread.

> I think the core of the problem is that the FileSystemEventHandler [...] is running on a different thread maybe?

That's very likely. You'll need to invoke a call in the event loop. I think `flx.loop.call_soon()` can do this for you.

**Comment by beeb** [comment]
My man!! that did the trick very nicely! Calling `flx.loop.call_soon(root.my_action, 'foo')` from the `FileSystemEventHandler` instance totally works. Thanks!
