### ISSUE TITLE
 `outernode` and `node` documentation for developers

### ISSUE THREAD

**Issue by damienflament** [flexxui/flexx#552]
Hi.

I successfully implemented a table widget using the _Python way_ (by using a root `TableWidget` and multiple `TableEntry`) and the _web way_ (by using a single `Table` widget and a _data_ `ListProp`).

But I'm trying to understand the way `outernode` and `node` properties can be used.

Can I use the `outernode` for the `table` DOM element and the `node` for the `tbody`DOM  element (which will contain the children) ?

Broadly speaking, the documentation says about those properties:
> If you don’t understand what this is about, don’t worry; you won’t need it unless you are creating your own low-level widgets :)

OK. I think I need to understand what this is about. :wink: 

Thanks.

**Comment by almarklein** [comment]
Haha. I will update these docs to make the use more clear.

Basically, most widgets have the same value for `node` and `outernode`. However, in some cases it helps to distinguish between the semantic "actual node" and a wrapper. E.g. the `CanvasWidget` does it in order to be able to use absolute positioning, and the `TreeWidget` for similar reasons. If your `outernode` already semantically represents your widget, you should probably just use that. Internally, Flexx uses the `node` attribute for tab-index, and binding to mouse/touch/scroll/key events.

I can see how in your case the `tbody` can indeed be a better fit for `node`.

**Comment by damienflament** [comment]
I don't know if I use them correctly.

### Table.py
```python
class TableWidget(flx.Widget):

    def _create_dom(self):
        node = flx.create_element('tbody')
        outernode = flx.create_element('table', {}, [node])

        return [outernode, node]


class TableEntry(flx.Widget):

    def _create_dom(self):
        return flx.create_element('tr')


class TableEntryAttribute(flx.Widget):
    text = flx.StringProp(
        settable = True, doc = "The text shown for this attribute."
    )

    def _create_dom(self):
        return flx.create_element('td', {}, [self.text])
```

### Main widget
```python
class EstimatesView(flx.Widget):

    data = flx.ListProp(doc = "The data shown by the view.")

    def init(self):
        super().init()

        with widgets.TableWidget():
            for datum in self.data:
                with widgets.TableEntry():
                    widgets.TableEntryAttribute(text = datum.id)
                    widgets.TableEntryAttribute(text = datum.name)
                    widgets.TableEntryAttribute(text = datum.client)
                    widgets.TableEntryAttribute(text = str(datum.total))
        widgets.TableWidget()
```

### Rendered HTML

```html
<div class="flx-EstimatesView flx-Widget flx-current">
    <table class="flx-TableWidget flx-Widget">
        <tbody></tbody>
        <tr class="flx-TableEntry flx-Widget">
            <td class="flx-TableEntryAttribute flx-Widget">D-000255</td>
            <td class="flx-TableEntryAttribute flx-Widget">Culpa esse cupidatat id elit dolor adipisicing</td>
            <td class="flx-TableEntryAttribute flx-Widget">Aliqua ullamco</td>
            <td class="flx-TableEntryAttribute flx-Widget">2533.25</td>
        </tr>
        <!-- more <tr> -->
    </table>
</div>
```

Here, the point is that the `TableEntry` child nodes are inserted in the `outernode`, not the `node`.

Is it expected ? I expected them to be added to the `node` while the `outernode` is itself inserted in the parent of the `TableWidget`.

**Comment by almarklein** [comment]
This is expected. The default implementation of `_render_dom()` adds the `outernode` of the children` to its own outernode. You probably want to implement `_render_dom()` on your `TableWidget`:
```py
def _render_dom(self):    
    # todo: ... clear self.node's children
    for widget in self.children:
           self.node.appendChild(widget.outernode)
    return create_element("table", {},
        create_element("thead", {}, ...),
        self.node
    )
```

Actually, I think it may be easier to not use a different `node` and do:
```py
class TableWidget(flx.Widget):

    def _create_dom(self):
        return flx.create_element('table')
    def _render_dom(self):        
        return create_element("table", {},
            create_element("thead", {}, ...),
            create_element("tbody", {}, [widget.outernode for widget in self.children])
        )
```

**Comment by almarklein** [comment]
Also note that Flexx will soon have a `GridLayout` (#553)

**Comment by damienflament** [comment]
> Also note that Flexx will soon have a `GridLayout` (#553)

Good. But here, I'm using a `<table>` to display data and allow sorting/filtering them by attributes.
I consider a `GridLayout` more relevant for displaying data as "cards" in a grid.

About that, I think implementing that layout using a `<table>` is not semantically. I would rather have used the CSS `display` property with its values `table-row`, `table-column`, `table-cell`, etc.

**Comment by damienflament** [comment]
Thanks for your help.

**Comment by almarklein** [comment]
Indeed, in that case a table makes more sense.
