### ISSUE TITLE
 AttributeError: type object 'IOLoop' has no attribute '_current'

### ISSUE THREAD

**Issue by kg-2** [flexxui/flexx#555]
cpython 3.6.8
windows 10
flex 0.7.1
tornado 6.0.2

Hi,
   I was running the example from the docs [here]([url](https://flexx.readthedocs.io/en/stable/guide/widget_basics.html))

```
app.launch('browser')  # show it now in a browser
flx.run()  # enter the mainloop

```
and I ran into this:
> 
> Traceback (most recent call last):
>   File "C:\Users\kevin\python\projects\_Flexx_Apps\_experimental\_tutorial_examples\_1\widget_intro.py", line 8, in print_errors
>     return func(*args, **kw)
>   File "C:\Users\kevin\python\projects\_Flexx_Apps\_experimental\_tutorial_examples\_1\widget_intro.py", line 25, in run
>     app.launch('browser')  # show it now in a browser
>   File "C:\Users\kevin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flexx\app\_app.py", line 151, in launch
>     current_server()
>   File "C:\Users\kevin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flexx\app\_server.py", line 78, in current_server
>     create_server()
>   File "C:\Users\kevin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flexx\app\_server.py", line 59, in create_server
>     _current_server = TornadoServer(host, port, loop, **server_kwargs)
>   File "C:\Users\kevin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flexx\app\_tornadoserver.py", line 56, in __init__
>     super().__init__(*args, **kwargs)
>   File "C:\Users\kevin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flexx\app\_server.py", line 118, in __init__
>     self._open(host, port, **kwargs)
>   File "C:\Users\kevin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flexx\app\_tornadoserver.py", line 70, in _open
>     IOLoop._current.instance = None
> AttributeError: type object 'IOLoop' has no attribute '_current'

**Comment by almarklein** [comment]
Thanks for the report! Fortunately, this has been [fixed already](https://github.com/flexxui/flexx/commit/717e831c0bcbbc9d10a96917394a467efceacdc1#diff-e3f9c4b7702e1f472797170badf7d37e). A new release is expected early next week.
