### ISSUE TITLE
Doc Request: Form Submission

### ISSUE THREAD

**Issue by kg-2** [flexxui/flexx#556]
Love the project- thanks for your hard work on it. It would be nice to have an example of how flexx expects users to post form data (raw javascript or a builtin method?).  I currently use Flask and WTForms, but [this](https://flexx.readthedocs.io/en/stable/examples/themed_form_src.html#themed-form-py) seems like a prospective replacement.

**Comment by almarklein** [comment]
The concept of a form where the result is send to the server with a POST request is different of how Flexx works. Flexx is more like a widget toolkit. So you create a form (e.g. with the FormLayout) and upon submission you can collect the data and send it to the server with e.g. an action, or by setting a certain property.

**Comment by kg-2** [comment]
Maybe I need to re-read the docs, but I guess I'm confused how that works. Flexx transpiles the code to javascript, delivers the html/javascript to the client. The client fills out the form, hits submit, <INSERT MAGIC>, the form data is delivered back to the server.

**Comment by almarklein** [comment]
Well, it kinda depends on how you implement your application:
* If you write a desktop app, you can use (the new) `PyWidget` to implement your high-level widgets, and everything you write will simply be in Python.
* You can also use Flexx to [write the front-end of your website and don't use the server](https://flexx.readthedocs.io/en/stable/guide/running.html#export-to-a-static-web-page). In this case it's up to you to implement the storing of the form data. You could e.g. use a `XMLHttpRequest` or do a POST. The former can be written in Python (PScript) just fine.
* In the default scenario, however, the server and client communicate over a websocket, and you can invoke actions and listen to events from accross the Python-JS border.

**Comment by kg-2** [comment]
Thanks for the explanation. I'm gonna go read up on websockets
