### ISSUE TITLE
Questions re changes in flexx 0.8

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#563]
Flexx's [0.8 release notes](https://flexx.readthedocs.io/en/stable/releasenotes.html) do not clearly indicate that key handling has changed.  This, I think, broke some key-handling code in [leoflexx.py](https://github.com/leo-editor/leo-editor/blob/master/leo/plugins/leoflexx.py).

To be clear, I am not complaining about the changes themselves.  They may well be a very good thing.  However, it took a long time to discover why leoflexx.py had stopped working.

After determining that *none* of commits in leoflexx.py worked, it finally occurred to me to suspect that an update to flexx itself was the culprit.  At last I discovered the documentation for [Widget.key_press](https://flexx.readthedocs.io/en/stable/ui/widget.html#flexx.ui.Widget.key_press):

"In contrast to key_down, this event does not fire for the pressing of modifier keys, and some browsers will also not fire for the arrow keys, backspace, etc."

Well, this must be a change, because key_press used to deliver various modifier keys.

My questions:

1. Is this, in fact, what happened?  Has there been a major change to Widget.key_press?

2. If so, this broke existing code.  Shouldn't the 0.8 release notes have highlighted this change?

Edward

**Comment by edreamleo** [comment]
I am going to close this.  It appears I have been using flexx 0.6.2.  There is some pretty deep confusion on my end, for which I apologize.

**Comment by almarklein** [comment]
Hehe, if we changed the key event handling, it would be a long time ago, not in 0.8 AFAICT.

> There is some pretty deep confusion on my end, for which I apologize.

No problem. That happens :)
