### ISSUE TITLE
if condition always true

### ISSUE THREAD

**Issue by CostiCTI** [flexxui/flexx#567]
[here](https://github.com/flexxui/flexx/blob/master/flexx/resources/bsdf.js#L360])

compression variable is always 0 and else branch is never reached.

**Comment by almarklein** [comment]
You are correct that the compression is always 0. That branch was introduced, so that when the JS implementation of BSDF starts supporting compression, it's easier to fit it in and we don't forget the alignment part.

**Comment by almarklein** [comment]
Thanks for the heads-up though :)
