### ISSUE TITLE
PyWidget initialization error

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#569]
Using this code:
```python
from flexx import flx, ui, event

class Test(flx.PyWidget):
    def init(self):
        super().init()
        
        print("HERE")
        
        main_style = f"""
            left: 10px;
            top: 10px;
            background-image: url("image.png"); 
        """
        with ui.HBox(style=main_style):
            pass

if __name__ == '__main__':
    m = flx.launch(Test)
    flx.run()
```
`HERE` is printed twice and no error is shown in the console.
If line `background-image: url("image.png"); ` is removed, everything works fine.
Note that if `url(...)` is replaced by anything, even gibberish, it also works fine.

Am I missing something or is this a bug? Shouldn't there be at least a warning?

Im using Flexx `0.8.0` on Python `3.7.2`.

**Comment by almarklein** [comment]
This is because the image uirl is relative, so it becomes `http://localhost/Test/image.png` and this server considers this a request for the `Test` app. Instead use an absolute url. If the image was added via `flx.assets.add_shared_data()`, it would be `/flexx/data/shared/image.png`.
