### ISSUE TITLE
Is there a way to change css stylesheet at runtime?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#571]
Hi,

I have a button:
```python
class MyButton(flx.Button):
    CSS = f"""
    .flx-MyButton{{
        background: blue;
        color: white;
        width: 200px;
        height: 50px;
    }}
    .flx-MyButton:hover {{
        background: white;
        color: blue;
        width: 200px;
        height: 50px
    }}
    """
```
Is there a way to change this stylesheet at runtime for an instance of MyButton?
In my case, I would like to reverse the `non-active` and `hover` colors.

Thanks,
Matic

**Comment by jeffreyf** [comment]
I have been using Widget's `apply_style` for adjusting the CSS: [https://flexx.readthedocs.io/en/stable/ui/widget.html#flexx.ui.Widget.apply_style](url)

**Comment by matkuki** [comment]
Excellent, thanks @jeffreyf
