### ISSUE TITLE
Question for using flexx to create desktop app

### ISSUE THREAD

**Issue by peterhsu2018** [flexxui/flexx#574]
I want to create the desktop app by flexx, and the purpose is for usb device communication and record data, and upload the data to http server. Does it work for me?

**Comment by almarklein** [comment]
I suppose so. If you try to "stay in Python land" as much as possible by making use of `PyWidget`, Flexx should feel much like a regular desktop ui toolkit.

> upload the data to http server

What do you mean by that? Would this be an external server to post the data to?

**Comment by peterhsu2018** [comment]
Hi, @almarklein , PyWidget is a lib like PyQt? How it combine with Flexx?
>upload the data to http server
I want to create a desktop app as client and upload some file to the server by rest api..
Do both the purpose work on Flexx?

**Comment by almarklein** [comment]
I meant using `flx.PyWidget` instead of `flx.Widget`: https://flexx.readthedocs.io/en/stable/ui/widget.html#flexx.ui.PyWidget

If I understand correctly, you want to process a POST or PUT request with the same server that runs Flexx?

**Comment by peterhsu2018** [comment]
Actually i want to build a server by Django, this server is for database, and data management.
Additionally, build a desktop app by Flexx as client that can installed on any individual computer or laptop, and create the request to upload file or send data using JSON format to server.
If this is easily to implement by Flexx, i would be try it.

**Comment by almarklein** [comment]
Right, in that case you can just use e.g. the `requests` library to send the data to your server from a `PyComponent`'s action.

**Comment by almarklein** [comment]
Or using a `fetch()` in JS, of course :)

**Comment by peterhsu2018** [comment]
@almarklein , thanks!
Additionally, can i use pyserial with flexx to communication between usb device and the computer run with flexx?

**Comment by almarklein** [comment]
I don't see why not :)
