### ISSUE TITLE
How to transfer data between Sessions?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#575]
Hi,

I have a login system where the logged in user's level (integer) is stored in the session with `session.add_data("user_level", bytes([user_level]))`. But as the user logs in, it redirects to another served *App*, which creates a new session and the *user_level* data is lost. This is my *Redirect* class:
```python
class Redirect(flx.JsComponent):
    def init(self, dest):
        super().init()
        self.dest = dest

    @flx.action
    def go(self):
        global window
        window.location.replace(self.dest)
```

How can I *transfer* the user data from one session to another?

Thanks

**Comment by matkuki** [comment]
To clarify:
I'm trying to make a simple user system, that when a user logs into a session, the user's level is stored in the session, so that when various Widgets are instantiated, they are automatically hidden if the user's level is not high enough.

**Comment by matkuki** [comment]
Ok, so I remembered that the user level data can be transferred by using a cookie and that works great.
But now I don't know how to access this information from a Widget(JS). I could add both the widget's level and user's level as arguments on instantiation, but is there a way to access the user level data from the JS side? Calling `self.session.get_cookie` inside a Widget doesn't seem to work.

**Comment by matkuki** [comment]
Found that using the `Central data store` like in the example does the trick:
https://flexx.readthedocs.io/en/stable/guide/patterns.html#use-of-a-central-data-store

**Comment by matkuki** [comment]
I now have a new problem:
When creating my main widget and store object like this:
```python
class Store(flx.JsComponent):
    user_level = flx.IntProp(-1, settable=True)

class MyWidget(flx.PinboardLayout):
    def init(self):
        super().init()
       
        # Add some other widgets
        
        if self.root.store.user_level < 2: # <---- TypeError: this.root.store is null
            # do something
        else:
            # do something else

class MainPage(flx.PyWidget):
    store = flx.ComponentProp(None, settable=True)

    def init(self):
        super().init()
        self._mutate_store(Store())

        self.my_widget = MyWidget()
```
I get an error when `MyWidget` is being initialized in the `init` of *MainPage*.

Is there a way to get around this?

**Comment by almarklein** [comment]
your code seems to work for me, what error do you get?

**Comment by matkuki** [comment]
Hey @almarklein ,

The error is `TypeError: this.root.store is null`. This seems to happen only if `self.root.store.user_level` is used inside the `init` method.

**Comment by almarklein** [comment]
I suspect that the proxy component of the root has no been updated to have the `store` property. You could delay the init to work around this:

```py
    def init(self):
        super().init()

        # Add some other widgets
        window.setTimeout(self.init2, 0)
    def init2(self):

        if self.root.store.user_level < 2: # <---- TypeError: this.root.store is null
            with self:
                pass
        else:
            pass
        print("ok")

```

**Comment by matkuki** [comment]
Excellent, that will do nicely 👍
Thanks!
