### ISSUE TITLE
Is webruntime needed to use flexx just as a server?

### ISSUE THREAD

**Issue by ocobacho** [flexxui/flexx#576]
I want to use flexx without installing webruntime is this posible? I just need the server.

**Comment by almarklein** [comment]
Technically it would not have to be, but there's an `import webruntime` in `flexx/app/_app.py`, so you'd need it to be installed, currently. FWIW webruntime is quite small and pure Python.

**Comment by ocobacho** [comment]
Thanks for the quick reply. I put a try catch on the webruntime imports and manage to make it work. I made some progress but i have a different problem now. :) I am trying to make flexx work on android.
