### ISSUE TITLE
Slow page startup time?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#578]
Hi guys,

I have a page which holds about 10 buttons and a flx.StackLayout which itself holds a few widgets and images inside 10 layers (every button on the main page corresponds to a StackLayout page).
Every time this page is loaded, there is a large delay (about 4-5 seconds) when the application starts (`Starting Flexx app` is displayed while the progressbar is progressing).
I assume that the problem is that there are a large number of widgets on the page, but that is only my guess. But when the page loads, it works beautifully.

Is there a way to shorten this delay?

Thanks

**Comment by matkuki** [comment]
Found why the slow loading time happens.
I am loading all of the `flx.StackLayout` pages when the page loads inside the page's `init` function.
But if I try to load the page when each of the 10 buttons is pressed, I get an error from my background python worker (which is a `flx.PyComponent`) that is attached to the page:
```
RuntimeError: MyPyWorker needs a session!
```
Is there a way to load a page (which is a `flx.PyWidget`) on the fly at runtime?

**Comment by almarklein** [comment]
I think you need to instantiate the PyComponent under the context of an existing PyComponent so that flexx knows what session it belongs to usually:

```py
with self:
 SomeComponent()
```

On Sat, Jul 20, 2019, at 10:36, matkuki wrote:

> Found why the slow loading time happens.
>  I am loading all of the `flx.StackLayout` pages when the page loads inside the page's `init` function.
>  But if I try to load the page when each of the 10 buttons is pressed, I get an error from my background python worker (which is a `flx.PyComponent`) that is attached to the page:

> `RuntimeError: MyPyWorker needs a session!
`

**Comment by matkuki** [comment]
@almarklein 
Thanks, yes that does not throw an error anymore, but the component is not shown.
The code looks something like this:
```python
class MainPage(flx.PyWidget):

    @flx.reaction('button.pointer_click')
    def menu_button_click(self, *events):
        ev = events[-1]
        button = ev.source
        if button.name == "test":
             with self:
                  pywidget = MyPyWidget()
                  self.my_stack_layout.set_current(pywidget._jswidget)
```
This code creates the `pywidget` successfully (I have print statements that confirm this), but the `StackLayout` I put the widget into shows nothing, only a white background. This same procedure works if I use it inside the `init` function of the `MainPage`.

Any ideas?

**Comment by matkuki** [comment]
Ha, it works if I do this:
```python
class MainPage(flx.PyWidget):

    @flx.reaction('button.pointer_click')
    def menu_button_click(self, *events):
        ev = events[-1]
        button = ev.source
        if button.name == "test":
             with self.my_stack_layout: # <-- Here is the change
                  pywidget = MyPyWidget()
                  self.my_stack_layout.set_current(pywidget._jswidget)
```
Right, it has to be the correct context!
Thanks @almarklein !
