### ISSUE TITLE
Flexx logo?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#579]
This might be silly, but I like `Flexx` a whole lot and was wondering if there is an official logo that I could use to advertise it, something like `Powered by Flexx`?

**Comment by almarklein** [comment]
Yes, I think its in the repo. Or perhapd the webruntime repo... (No access to a conputer atm)

**Comment by matkuki** [comment]
Thanks, got it!
It's in `flexx/resources` for anyone looking for it also.
