### ISSUE TITLE
how I can do with flexx or PScript to load plotly.js from my local project document? Thank you very much.

### ISSUE THREAD

**Issue by seancug** [flexxui/flexx#584]
Hi @almarklein ,
I was developing an app with using the amazing software “flexx”. And there is good feature that there is plotlyWidget which is really useful for me to plot my scientific data. I read the PlotlyWidget code, there is only one function `Plotly.newplot(),`,  that is not enough for me. So I read a lot of mannual about “flexx” in order to create a new class which can satisfy my needs.

But there is a proplem which plague me a lot. Besides I know nothing about javascript programming, and I want write my code in python way.

- How to load plotly.js assset from local computer?The PlotlyWidget gets its plotly.js assset from remote url with the code `app.assets.associate_asset(__name__,’https://cdn.plot.ly/plotlylatest.min.js’)` . I want my app running independent with the internet, so I don’t want my code run that way. I download the file “plotly­latest.min.js” from the plotly website and place it under my project. I copy the PlotlyWidget code and change only one line `app.assets.associate_asset(__name__,'https://cdn.plot.ly/plotlylatest.min.js’)` to `app.assets.associate_asset(__name__,’plotly­latest.min.js’)`. But it does’t work. I do itin a lot of ways such as `app.assets.associate_asset(__name__,’my.js’, ’plotly­latest.min.js’)` and so on. All of it failed.

        

After all, how I can do with flexx or PScript to load plotly.js from my local project document? Thank you very  much.

**Comment by seancug** [comment]
find solution in example

**Comment by almarklein** [comment]
Can you please explain what you did, for future reference? :)

**Comment by matkuki** [comment]
I think he meant this example:
https://flexx.readthedocs.io/en/stable/examples/local_assets_src.html#local-assets-py
