### ISSUE TITLE
How to specify server and port when serving app?

### ISSUE THREAD

**Issue by gwingnhbc** [flexxui/flexx#589]
Hi,
Warning, newbie to flexx here :-)

Would it be possible to clarify how you can specify a server name and port when serving an app please? I've tried supplying parameters to app.serve() and flx.start() and had a read of issue #140 but can't actually find the mechanism to use.

Rgds,
Rob.

**Comment by matkuki** [comment]
Example:
```python
from flexx import config

# This makes the server accessible in a browser with url http://192.100.200.15:1234
config.hostname = '192.100.200.15'
config.port = 1234

# Rest of your code
flx.start()
```
Hope it helps.

**Comment by jrversteegh** [comment]
See also [Flexx Configuration](https://flexx.readthedocs.io/en/stable/configuration.html)

**Comment by gwingnhbc** [comment]
Thankee kindly, much appreciated.
