### ISSUE TITLE
ComboBox selection disappears

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#591]
Hi,

When creating `ComboBox` like so:
```python
flx.ComboBox(
    editable=True,
    options=my_list_of_options,
    selected_index=0,
)
```
and then:
- selecting an option
- clicking anywhere inside the `ComboBox` (with or without doing any editing)
- clicking outside the `ComboBox`

the text inside the `ComboBox` disappears!
Here is a video:
![2019-10-07_08-56-55](https://user-images.githubusercontent.com/10289651/66290866-a6c8b300-e8e0-11e9-96f9-9713b02a504f.gif)

This seems like a bug. Is this supposed to behave like this?

**Comment by almarklein** [comment]
Can reproduce it with Firefox. This is indeed a bug.
