### ISSUE TITLE
GroupWidget problem

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#592]
Using a normal `GroupWidget` works fine like this:
```python
        class Test(flx.Widget):
            def init(self):
                with flx.VBox(padding=20, spacing=20):
                    with flx.GroupWidget(title="TEST GROUPBOX", flex=0):
                        with flx.VBox():
                            flx.ComboBox(
                                editable=False,
                                options=["ENA", "DVA", "TRI"*10, "ŠTIRI"],
                                selected_index=0,
                            )
                    flx.Widget(flex=1)

        entry = flx.App(Test, title=title)
        entry.serve('')
```
... and it produces this:
![image](https://user-images.githubusercontent.com/10289651/66524331-6d679180-eaf2-11e9-9958-d0345b56fbc6.png)

But using a subclassed `GroupWidget` like so:
```python
        class GB(flx.GroupWidget):
            CSS = f"""
                .flx-GB legend {{
                    font-family: Helvetica;
                    font-size: 16px;
                    font-weight: bold;
                }}
            """

        class Test(flx.Widget):
            def init(self):
                with flx.VBox(padding=20, spacing=20):
                    with GB(title="TEST GROUPBOX", flex=0):
                        with flx.VBox():
                            flx.ComboBox(
                                editable=False,
                                options=["ENA", "DVA", "TRI"*10, "ŠTIRI"],
                                selected_index=0,
                            )
                    flx.Widget(flex=1)

        entry = flx.App(Test, title=title)
        entry.serve('')
```
.. produces this:
![image](https://user-images.githubusercontent.com/10289651/66525095-a43ea700-eaf4-11e9-8633-8c33dc73179b.png)
You can see that the top border line is missing and the combobox is moved down so only about half of it is showing.

Any ideas?

**Comment by jrversteegh** [comment]
Both look fine on firefox 69.0.1 / linux x86_64

**Comment by matkuki** [comment]
@jrversteegh 
You are right! I just tried it on another machine in the same browser (Firefox) and it works.
I need to check further, thanks! 

I'll leave this issue open until I find the specific problem with my machine.

**Comment by matkuki** [comment]
Found the problem.
Above the code shown above I import the `bootstrap` *css* assets like so:
```python
with open('css/bootstrap.min.css', 'r') as f:
    style = f.read()
flx.assets.associate_asset(__name__, css_file, style)
```
... which messes up the `GroupWidget` styling.
If I comment the last line shown above out, it works.
