### ISSUE TITLE
How to add a custom emitter to ComboBox?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#598]
Is it possible to add a `index_changed` emitter to the ComboBox?
If there is some other way instead of an emitter to do this is fine too.

I need a way to tell when the value changed, regardless if the user or code changed the index.

Thanks

**Comment by jrversteegh** [comment]
Property values are automatically emitted, I believe, so:
```
from flexx import flx

class Test(flx.Widget):
    def init(self):
        self.combo = flx.ComboBox(
            options=["ONE", "TWO", "THREE"],
            selected_index=0)

    @flx.reaction('combo.selected_index')
    def on_selected_index(self, *events):
        print(events[-1].new_value)
```
should just work.

**Comment by matkuki** [comment]
Excellent, I did not know that! Thanks!

**Comment by almarklein** [comment]
@jrversteegh small markdown tip: using `` ``` py `` will apply Python syntax highlighting to the snippet :)

**Comment by jrversteegh** [comment]
@almarklein thanks! Guess I should have read the fine manual again ;D
