### ISSUE TITLE
GroupWidget scrolling issue?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#599]
Hi,

I have a `GroupWidget`. If there is no set `max-height` for the widget like so:
```python
with flx.HBox(padding=0, spacing=0, flex=1):
    with flx.GroupWidget(title="TEST", style="overflow: scroll;") as self.gc:
        pass
```
... which I add `flx.Labels` to it at runtime. The problem is, the bottom part of the widget get's cut and the contents get covered on the right side by the scrollbar, like so:
![image](https://user-images.githubusercontent.com/10289651/66897527-762afc80-eff7-11e9-9039-7b77e0ddb6d1.png)
Setting the `max-height` to something lower than what can optically be judged on the screen fixes the bottom cutting out issue, but I do not wish to try to *eyeball* the height every time.

What is the correct way to use a `GroupWidget` with scrolling, so that these issues are are not a problem?

Thanks

**Comment by jrversteegh** [comment]
Imho a scrollable GroupWidget doesn't make any sense.  Why would you want that?

**Comment by matkuki** [comment]
I use it to show what reports were generated. And it looks quite nice.
Could I use something else and make it look like a `GroupWidget`, with the frame and title text?

**Comment by matkuki** [comment]
One way around this is to put a `flx.Widget` inside the `flx.GroupWidget`, and then adding all the labels to the `flx.Widget` instead of the `flx.GroupWidget`.
