### ISSUE TITLE
LineEdit: allow only number input?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#600]
Hi, 

Is there a way to allow only numbers to be added to a `flx.LineEdit`?

Thanks

**Comment by almarklein** [comment]
Not really, unless you write the code for this yourself. Browsers do have `<input type='number'>` ([docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number)), so it should not be too hard to wrap that - and maybe add it to `flexx.ui` :)

**Comment by matkuki** [comment]
Thanks, will try.
