### ISSUE TITLE
how to invoke js funciton in PyWidget?

### ISSUE THREAD

**Issue by steevenlee** [flexxui/flexx#602]
Hi,

I want to handle "Esc" key when switching to another panel, here is what I do:
Base_app(PyWidget):

    VBox(tabindex=0) as self._cont:

When switch:

    old_panel.set_parent(None)
    new_panel.set_parent(self._cont)

This works by reaction on key_down event for _cont, but nothing get focused after switching, so "Esc" key can't be captured.

From previous thread here, "node.focus()" should work, but how to invoke it from PyWidget? 

Thanks,
Steeven

**Comment by almarklein** [comment]
You cannot directly access the node attribute from Python. You should create an action on your JsWidget somewhere, that does what needs to be done, and then call that action from Python.

**Comment by steevenlee** [comment]
Great, the folowing code works:

class FocusBox(flx.VBox):
    @flx.action
    def focus(self):
        self.node.focus()
