### ISSUE TITLE
Widget for large data (X rows * Y columns) display?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#606]
Hi guys,

Anyone know of a widget or has perhaps made one for viewing large sets of data, for example 500 rows * 150 columns?
I have tried:
- `flx.GridLayout`: Would be ideal as it seems to render large numbers of widgets quite quickley, but it has weird behavior when putting it inside a container and setting the children's `maxsize=(w,h)` and `flex=0`. Example:
```python
from flexx import flx

class Test(flx.Widget):
    def init(self):
            with flx.HSplit():
                with flx.GridLayout(ncolumns=10):
                    for i in range(200):
                        flx.Button(text="T", maxsize=(25,25), flex=(0, 0))
        
test_app = flx.App(Test, title="TEST")
test_app.serve('')
flx.start()
```
produces this for me:
![image](https://user-images.githubusercontent.com/10289651/68888309-fc338380-071a-11ea-971c-0ed96aae46dd.png)

- Rows represented by a `flx.Hbox` inside a `flx.VBox`: Very slow for large number of widget's in a single row.

Anyone have any solutions for this?

Thanks

**Comment by gwingnhbc** [comment]
For the 'hbox inside a vbox' option I reduce the number of widgets by concatenating  the displayed data values and  then display that as a  single pre-formatted html label. Just using extra widgets on the row for any  'action' buttons needed. It is far from an ideal solution but it does extend the viability of this approach to a somewhat larger data set.

**Comment by matkuki** [comment]
@gwingnhbc 
Thanks for the idea with the single formatted label, I never thought of that. Will try it.

**Comment by almarklein** [comment]
Anything based on widgets will be hard to scale up due to the overhead that you get for each widget. I think it's feasible to implement a TableWidget that uses `<table>`, and should scale up really well. If you want to scale it even further, a more elaborate solution would be to use `<canvas>`, like [PhosphorJS datagrid](http://phosphorjs.github.io/examples/datagrid/)
