### ISSUE TITLE
Mutating a dict with "set" clears dictionary but does not set values.

### ISSUE THREAD

**Issue by TreyBoudreau** [flexxui/flexx#615]
I have not yet tested this, but it appears that attempting to mutate a DictProp via "set" only clears the dictionary:
https://github.com/flexxui/flexx/blob/801c679490862409faff8034e89f7a64941dc76c/flexx/event/_component.py#L632

I think the `elif mutation in ('set', 'insert', 'replace'):` should just read `if mutation ...`

**Comment by almarklein** [comment]
Eek ... it looks to me like that `elif` should have just been an `if`.

**Comment by almarklein** [comment]
Fixed :)
