### ISSUE TITLE
How to properly dispose a PyWidget?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#621]
Hi guys,

I have custom `PyWidget`, something like this:
```python
class CustomPyWidget(flx.PyWidget):
    frame = None
    
    def dispose(self):
        self.frame.dispose()
        self.frame = None
        super().dispose()
    
    def init(self, additional_style):
        with flx.VFix(flex=1, style=additional_style) as self.frame:
            pass
```
Now I put it into a `VFix` layout like so:
```python
with flx.VFix(flex=1) as self.frame_layout:
     self.custom = CustomPyWidget(
          "width: 100%; height: 100%; border: 5px solid black;", flex=1
     )
```
... and it works great.
So now I wish to remove it from the `frame_layout`, then add a new `CustomPyWidget` to the layout in place of it, like so:
```python
def delete_function():
    self.custom.dispose()
    self.custom = None
    with self.frame_layout:
         self.custom = CustomPyWidget(
              "width: 100%; height: 100%; border: 5px solid green;", flex=1
         )
```
But that gives me this:
![chrome_iGsG6tLUCO](https://user-images.githubusercontent.com/10289651/73854774-4f593600-4833-11ea-8e41-0415a4856163.png)

How do I properly delete a custom PyWidget?

Thanks,
Matic

P.S.:
Just tried changing the inheritance from `PyWidget` to `Widget`, and then it works!
But to use this in my application I would have to rewrite lots of custom Python code to be JS compatible. Would appreciate if there was a solution for the `PyWidget`.

**Comment by almarklein** [comment]
Full example, with the missing piece:
```py
from flexx import flx


class CustomPyWidget(flx.PyWidget):
    frame = None

    def dispose(self):
        self.frame.dispose()
        self.frame = None
        super().dispose()

    def init(self, additional_style="border: 3px solid red"):
        with flx.VFix(flex=1, style=additional_style) as self.frame:
            pass

class Example(flx.PyWidget):
    def init(self):
        with flx.VFix(flex=1) as self.frame_layout:
            self.custom = CustomPyWidget(
                "width: 100%; height: 100%; border: 5px solid black;", flex=1
            )
            self.but = flx.Button(text="swap it")

    @flx.reaction("but.pointer_click")
    def delete_function(self, *events):
        self.custom.dispose()
        self.custom._jswidget.dispose()  # <-- added
        self.custom = None
        with self.frame_layout:
            self.custom = CustomPyWidget(
                "width: 100%; height: 100%; border: 5px solid green;", flex=1
            )

m = flx.launch(Example)
flx.run()
```

So I think `PyWidget` needs a fix to dispose it's `_jswidget`.

**Comment by Konubinix** [comment]
Hi. I don't understand the need to put frame and custom to None in the examples. It is to help the garbage collector to avoid some memory leaks, to trigger some cleaning behavior in flexx or some other reason?

**Comment by almarklein** [comment]
In theory that should not be needed, but it can be good practice. You e.g. may just break a cyclic loop that would otherwise be hard for the gc to clean up. Also, you dismantle the internals of the object, so if some other code tries to use it, that will fail ;)
