### ISSUE TITLE
How to build flexx app to .exe?

### ISSUE THREAD

**Issue by ScottHuangZL** [flexxui/flexx#622]
**Simple Code:**
```
from flexx import flx

class Example(flx.Widget):
    def init(self):
        flx.Button(text = "hello")
        flx.Button(text = "world")
        flx.Button(text="!")


app = flx.App(Example)
app.launch()
flx.run()
```

It run ok in IDE.

Then I try to compile it to exe through PyInstaller: PyInstaller Example.py

And then run that exe, but it show up below error.
```
Traceback (most recent call last):
  File "site-packages\pscript\functions.py", line 77, in py2js_
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code

```

**Help Needed:**
1. How to successful build the exe and run?
2. I already setup venv, but the dist size still huge, anyway to thrink the size?

Thanks.

**Comment by ScottHuangZL** [comment]
According https://flexx.readthedocs.io/en/stable/freeze.html

At last I can build the app to .exe, and can run successfully.

However, it seems need copy the flexx source folder and **mywidgets** source file to that dist.

**Anyway to hide or _mix_ the widgets python source file?**   Thanks.

**Comment by almarklein** [comment]
Sorry, I don't understand that last question :)  You need to make sure that your source files are in the `/source` directory of the binary that you build with PyInstaller. Flexx has a convenience to copy modules there (`flexx.freeze.copy_module`), but you can copy your modules any way you like (including manually).

**Comment by ScottHuangZL** [comment]
But I don't want end user to so easily watch my source (exclude FlexxUI).  Anyway to compile the source to byte code?  Instead of the "human easy read text".py  thanks.

**Comment by almarklein** [comment]
The thing is that flexx itself *needs* the source code so it can compile it to JS. What you could do is split the code for flexx widgets from the server side stuff, and only add that to the `source` dir. This is will also help keep the code nicely separated, so it may help keep the code maintainable too ;)

**Comment by ScottHuangZL** [comment]
Thanks for feedback.  But this is desktop app. Not server/client app.
