### ISSUE TITLE
Splitting on ':' with css

### ISSUE THREAD

**Issue by Abeldewit** [flexxui/flexx#627]
When using `apply_style()` it splits on any occurence of `:` which makes it impossible to pass url's with `http://` in it. 
Simple fix is changing `key, val = part.split(':')` to  `key, val = part.split(':', 1)` in row 598 of _widget

**Comment by almarklein** [comment]
Nice catch! Would you mind submitting a PR? :)

**Comment by almarklein** [comment]
Closed by #628
