### ISSUE TITLE
Static CSS attribute problem?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#634]
Hi guys,

I have a base table class and a subclass with a CSS attribute that sets it header colors:
```python
class TabulatorTableBase(flx.Widget):
   ...

class TabulatorTableBaseYellow(TabulatorTableBase):
    CSS = """
        .flx-TabulatorTableBaseYellow .tabulator-header .tabulator-col {
            background-color: #ffc000;
            color: black;
        }
    """
```
This works great, but if I want to change the color to for example green, the base class needs to be subclassed again and just it's CSS attribute adjusted.

I don't know enough about `CSS`, but is there a way to achieve this without subclassing, maybe with `apply_style` after a base class instance has been instantiated?

I tried this, but it doesn't work:
```python
table = TabulatorTableBase()
table.apply_style("""
    .tabulator-header .tabulator-col {
            background-color: #ffc000;
            color: black;
    }
""")
```

Thanks

**Comment by matkuki** [comment]
@almarklein 
Any ideas?

**Comment by almarklein** [comment]
With `apply_style()` you target a specific element. You cannot use the CSS selectors (e.g. ".tabulator-header .tabulator-col"), but you directly use the stuff between curly braces (or a dict that represents the element style).

What you could do instead, is something like this:

```py
class TabulatorTableBase(flx.Widget):
    CSS = """
        .flx-TabulatorTableBaseYellow .tabulator-header .tabulator-col {
            background-color: #00ff00;
            color: black;
        }
        .flx-TabulatorTableBaseYellow.yellow .tabulator-header .tabulator-col {
            background-color: #ffc000;
            color: black;
        }
    """
   ...
```

And then in the instance that you want to make yellow, use `self.set_css_class('yellow')` to set additional [css class name(s))[https://flexx.readthedocs.io/en/stable/ui/widget.html#flexx.ui.Widget.css_class].

**Comment by matkuki** [comment]
Perfect, thanks!
