### ISSUE TITLE
GroupWidget doesn't display uppercase non-ascii characters in title

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#635]
The `flx.GroupWidget` doesn't seem to like uppercase non-ascii characters in it's title.
For example:
  - `Nemčija` is ok, but `NEMČIJA` turns into `NEMCIJA`.
![image](https://user-images.githubusercontent.com/10289651/79548225-661ed300-8095-11ea-94b7-a529651c2788.png)

  - `ŠČŽTESTŠČŽ` turns into `SCZTESTSCZ`    
![image](https://user-images.githubusercontent.com/10289651/79548092-31128080-8095-11ea-9b37-76bb50acbb74.png)

Any solution for this?

**Comment by matkuki** [comment]
For example, for a flx.Button's text this is not a problem:
![image](https://user-images.githubusercontent.com/10289651/79847864-9ed5e980-83c0-11ea-80b2-bc8f5d8a6dd2.png)

**Comment by almarklein** [comment]
I can reproduce this with:
```py
from flexx import flx

class Example(flx.Widget):

    def init(self):
        with flx.GroupWidget(title="Nemčija NEMČIJA"):
            with flx.TabLayout(minsize=100):
                with flx.Widget(title="Nemčija NEMČIJA"):
                    flx.Button(text="Nemčija NEMČIJA")
                    flx.Label(text="Nemčija NEMČIJA")

flx.launch(Example, "chrome-browser")
flx.run()
```
![afbeelding](https://user-images.githubusercontent.com/3015475/79849165-6800d300-83c2-11ea-8d18-3119dcdbbe6f.png)

I used the browser inspector (F12) to check the fonts: they are the same. So this looks like some odd browser feature to me :/

**Comment by matkuki** [comment]
Thanks for the information!
