### ISSUE TITLE
blankscreen with standalone app on Firefox engine

### ISSUE THREAD

**Issue by MikHulk** [flexxui/flexx#636]
Hello,

I am discovering Flexx. I am a complete new comer. I tried several of standalone app examples from documentation. This one by instance: https://flexx.readthedocs.io/en/latest/examples/circles_src.html#circles-py

For All example  get the same result on standalone app on my system: Debian 10 with FF 68.7.0esr (64 bits), a window with a black screen. 

I have some plugin on my FF as No script, u block. could these plugins bring problem ? I don't think but perhaps it's the case.

**Comment by MikHulk** [comment]
I have just tired with 'chrome-app' runtime and it works. I don't know why the example doesn't owrk with FF.

**Comment by almarklein** [comment]
Thanks for reporting this. It could be that the way that the "firefox app" works for some reasone fails on your OS. Have you tried "firefox-browser" instead? That way we can tell whether the problem is Firefox itself or the "making it look like an app" part.

**Comment by MikHulk** [comment]
Hello !

Thx for your reply.

It works with firefox-browser. I noticed however I need to allow JS in [no-script](https://noscript.net/). I don't know how this plugin works, but it's possible that no-script disallow JS in standalone engine too. What do you think about this ?

I can try with another profile, I will try this. Do you know a way to launch engine with a default profile or with a peculiar option directly from flexx or WebRuntime ?

**Comment by almarklein** [comment]
>  ... that no-script disallow JS in standalone engine too. What do you think about this ?

I'm not sure if plugins are loaded when running as Xul (as an app).

> Do you know a way to launch engine with a default profile or with a peculiar option directly from flexx or WebRuntime ?

That's currently not possible, unfortunately. So it may be easier to use a browser, chrome-app (if on Window) or nw-app.

**Comment by MikHulk** [comment]
Thank you. I will try firefox-app with default profile, see this resolves the issue. If not, I make my app with crome-app as I need a stand-alone app with my application.

I'll keep you up to date.

**Comment by MikHulk** [comment]
Hi,

I have just tried on a macbook pro and a FF 75 fresh install. Same problem. I get a blank screen and the app is frozen when I launch app with 'firefox-app' mode.

**Comment by MikHulk** [comment]
In the browser it works as expected in chrome and firefox. Only firefox-app have this issue. I think I am going to try with nw.js. I'll keep you up to date

**Comment by almarklein** [comment]
Thanks for keeing me posted. I'm starting to suspect that Firefox changed something, which is breaking our method.

**Comment by MikHulk** [comment]
Yest I think too.

**Comment by emilio** [comment]
The reporter asked on Mozilla's Riot and I had some time to help (such is isolation :P), so I took a look. Here's a PR that fixes this issue for me: https://github.com/flexxui/webruntime/pull/15

See the specific commits for the details.

**Comment by MikHulk** [comment]
It works for me with the webruntime patch https://github.com/flexxui/webruntime/pull/15

**Comment by almarklein** [comment]
Great! Lets leave this issue open for others facing the same problem. Will do a release next week.

**Comment by almarklein** [comment]
webruntime is released.
