### ISSUE TITLE
Layout with labels problem?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#638]
Hi guys,

I have this code:
```python
from flexx import flx

class MyLabel(flx.Label):
    CSS = f"""
        .flx-MyLabel {{
            font-family: Helvetica;
            font-size: 16px;
            font-weight: bold;
            text-align: center;
            display: table;
        }}
        
        .flx-MyLabel span {{
            display: table-cell;
            vertical-align: middle;
        }}
    """
    
    @flx.action
    def _set_text(self, text):
        self.set_html("<span>" + text + "</span>")
    
    @flx.action
    def hide(self):
        self.apply_style("visibility: hidden;")
    
    @flx.action
    def show(self):
        self.apply_style("visibility: visible;")
    
    
def create_label(text, additional_styling="", **kwargs):
    return MyLabel(
        html="<span>" + text + "</span>",
        style=additional_styling,
        **kwargs
    )

class Test(flx.Widget):
    
    def init(self):
        def cl(*args, **kwargs):
            label = create_label(*args, **kwargs)
            label.set_wrap(True)
            return label
        
        for i in range(5):
            with flx.HFix(flex=(0.0, 1.0)) as frame0:
                cl("TEST", "font-size: 16px; border: 1px solid black; max-width: 60px;", flex=0)
                
                with flx.HFix(flex=0) as frame1:
                    cl("TEST", "font-size: 16px; border: 1px solid black; min-width: 120px; max-width: 120px;", flex=1)
                    cl("TEST", "font-size: 16px; border: 1px solid black;", flex=1)
                
                with flx.HFix(flex=0) as frame2:
                    cl("TEST", "font-size: 16px; border: 1px solid black; min-width: 60px; max-width: 60px;", flex=0)
                    cl("TEST", "font-size: 16px; border: 1px solid black; min-width: 100px; max-width: 100px;", flex=0)
                    cl("TEST", "font-size: 16px; border: 1px solid black;", flex=0)
                
                with flx.VFix(flex=(0, 1)) as frame3:
                    for i in range(10):
                        with flx.HFix(flex=(0, 1)) as frame4:
                            cl("TEST", "font-size: 14px; border: 1px solid black; min-width: 60px; max-width: 60px;", flex=0)
                            cl("TEST", "font-size: 14px; border: 1px solid black; min-width: 100px; max-width: 100px;", flex=0)
                            cl("TEST " * 40, "font-size: 16px; border: 1px solid black;", flex=(0, 1))

app1 = flx.serve(Test)
flx.start()
```
This produces this on Chrome:
![image](https://user-images.githubusercontent.com/10289651/80184907-bbb22d00-860b-11ea-9fa9-a3149de4df33.png)

The label marked in `red` is not displayed entirely, the bottom part is cut off.
How do make the `blue` `HFix` (frame4 in the above code) always stretch vertically to show the entire contents of the `red` label?

Thanks

**Comment by matkuki** [comment]
It seems that the minimum `Label` height is always one font height.
Is there a way to force it to be as many lines as the `wrap` functionality divides it to?

**Comment by matkuki** [comment]
Also tried wrapping the red label in a `VBox` and `VFix`, but no changes.

@almarklein Any ideas?

**Comment by almarklein** [comment]
Using `VBox` for frame3 won't help if frame4 is a fixed layout. With a fixed layout, JS/Flexx takes control of the layout, and thereby you lose the information about the "natural required size" of the elements within. By using `HBox` for frame4 as well, the browser controls the layout from frame3, down to the elements.

There's a second problem, and that is that each of the boxes in the last column are oversized, so there is simply not enough space.

As an example, I tweaked the last few lines a bit:
```py
                with flx.VBox(flex=(0, 1)) as frame3:
                    for i in range(10):
                        with flx.HBox(flex=(0, 1)) as frame4:
                            cl("TEST", "font-size: 14px; border: 1px solid black; min-width: 60px; max-width: 60px;", flex=1)
                            cl("TEST", "font-size: 14px; border: 1px solid black; min-width: 100px; max-width: 100px;", flex=1)
                            cl("TEST " * (40 if i==0 else 2), "font-size: 16px; border: 1px solid black;", flex=1)
```

And I disabled the `display: table` because apparently together with Hbox it causes the labels to not take "their space". And then I got this:

![afbeelding](https://user-images.githubusercontent.com/3015475/80461789-16ae9180-8936-11ea-8280-65044613c701.png)

**Comment by matkuki** [comment]
Hey @almarklein ,
Thanks for the additional information.
But how do I make `frame0` stretch vertically, so that all labels created with the `cl` functions will always have all of their content visible?

**Comment by almarklein** [comment]
> But how do I make frame0 stretch vertically, 

Ah, you mean you create 5 `frame0`'s, and only one is shown. This is probably because they are not in a layout (you probably want to subclass from `VFix`, or add a root `with flx.VFix`. Also, the iteration variable is `i`, but the same is used further down.

**Comment by matkuki** [comment]
@almarklein 
Right, good catch with the duplicaton of the `i` variable.
Yes, if a main `with flx.VFix:` is added, then five `frame0` are created. But their dimensions change, some labels get "squished", with it's content cut from view. How do the layouts have to be created for that never to happen? How do I make a `frame0` that never has any of it's labels (no matter how nested they are) "squished"?

Because if I add you proposed changes, this happens (The last labels in `frame4` are "squished"):
![image](https://user-images.githubusercontent.com/10289651/80471692-0dc4bc80-8944-11ea-9936-0620e77e678b.png)

**Comment by almarklein** [comment]
Basically, you can't unless you used box layout all the way through to above frame0.

Fix layout and split layout work "top down". They take the available space and divide that space among their children. The box layout is "bottom up". They check what space each child needs, and divide the available space as good as possible. You can't have both. There's usually a point in your GUI where you go from the one approach to the other.

**Comment by gwingnhbc** [comment]
@almarklein
 "Fix layout and split layout work "top down". They take the available space and divide that space among their children",

Would you also include the tab layout in this list?

**Comment by almarklein** [comment]
Yes. The tab layout assigns all available space to just one of its children. It uses absolute positioning (of the child widgets), so info on "natural size" of widgets cannot bubble up.

**Comment by gwingnhbc** [comment]
Thanks, I now understand better some of the layout difficulties I had to find workarounds for when using the tab layout.
