### ISSUE TITLE
PinboardLayout example vanishes when placed inside Pywidget

### ISSUE THREAD

**Issue by Zulan** [flexxui/flexx#639]
I have issues getting the `PinboardLayout` to be visible when used inside of widget. This is best exemplified by a slight modification of the example:

```
from flexx import flx, ui

class Example(ui.Widget):
    def init(self):
        super().init()
        with ui.PinboardLayout():
            self.b1 = ui.Button(text="Stuck at (20, 20)", style="left:20px; top:20px;")
            self.b2 = ui.Button(text="Dynamic at (30%, 30%)", style="left:30%; top:30%; height:100px;")
            self.b3 = ui.Button(text="Dynamic at (50%, 70%)", style="left:50%; top:70%;")

class Wrapper(flx.PyWidget):
    def init(self):
        self.widget = Example()

app = flx.App(Wrapper)
app.launch("browser")
flx.run()
```
Note that `app = flx.App(Example)` works as expected.

Apparently the height of the `PinboardLayout` is 0, but I lack the detailed knowledge of HTML/CSS for further investigation.

Tested with:
- flexx version 0.8.0 / master (4561826)
- Firefox / Chromium

**Comment by almarklein** [comment]
When you have something like this:
```py
class ContainerWidget(ui.Widget):
    def init(self):
        super().init()
        with SomeLayout():
             Content1()
             Content2()
```

... then you can use this directly under the root or inside a layout. You then get:
`root/layout -> containerwidget -> somelayout -> content`

Flexx is able to deal with the situation where there is one "container widget" in between two layouts, and still connect the two layouts. However, in your example, there are 2 layers of container widgets, and then it does not work :)

A solution could be to use instead:
```py
class Example(ui.PinboardLayout):
    def init(self):
        super().init()
        self.b1 = ui.Button(text="Stuck at (20, 20)", style="left:20px; top:20px;")
        ...
```

BTW: I don't think this is specific to the PyWidget
