### ISSUE TITLE
Bokeh Widget broken

### ISSUE THREAD

**Issue by avivazran** [flexxui/flexx#641]
seems to be originated here:
`def make_bokeh_widget(plot, **kwargs):  
    Plot = components = None  
    exec("from bokeh.models import Plot")  # noqa - dont trigger e.g. PyInstaller  
    exec("from from bokeh.embed import components")  # noqa - dont trigger e.g. PyInstaller  
`
 tried to remove the second "from" but still no luck.
any chance to enable bokeh plot support again?

**Comment by almarklein** [comment]
Fixed, kinda. The layout is a bit iffy still ... could use some help to resolve that; I haven't been using Bokeh in a long time.
