### ISSUE TITLE
Setting meta tags?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#646]
Hi,

I have a standard `flx.App` that I don't know how to set the meta tags. The current `head` looks like this:
```html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>My App 1.0</title>
<link id="flexx-favicon" rel="shortcut icon" href=""></head>
```
How do I change the `viewport` meta tag to be `user-scalable=yes`?

Thanks

**Comment by almarklein** [comment]
At the momemt you can't. Unless if you change the template in `app/_assetstore.py`.

**Comment by matkuki** [comment]
Thanks.

Would you be willing to accept a PR to make this user specifiable, or is that maybe already in the works?

**Comment by almarklein** [comment]
If it does not convolute the API too much, sure!
