### ISSUE TITLE
How to focus a Widget from code?

### ISSUE THREAD

**Issue by caph1993** [flexxui/flexx#649]
I am searching for something like `self.my_widget.set_focus()`, but I could not find that in the documentation. Is this feature implemented?

**Comment by caph1993** [comment]
I found several ways to do it:
 + using `widget.node.focus()`
 + using `document.getElementById(widget.id).focus()`
 + using `global eval`, `get = eval("(x)=>document.getElementById(x)")` and `get(widget.id).focus()`

However, it will not work if the app is not focused. And by default, the app is not focused when started from command line :(

**Comment by almarklein** [comment]
> using `widget.node.focus()`

That would be the way to focus a widget.

But indeed, as you've already found out, it is not possible to focus the (browser) window.
