### ISSUE TITLE
Digest authentitaction for a camera?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#651]
Hi,

I have an IP camera which supports digest authentication.
Does anyone have an idea of how to login using digest authentication and then display the stream url?

The camera has a standard mjpg stream url:
`http://<server_ip>/cgi-bin/mjpg/video.cgi?channel=1&subtype=1`
... but if I directly show the url in a `flx.IFrame`, the standard username/password box pops up in the browser.
Can I somehow use digest authentication on the current session, so that the browser won't ask me for credentials?

I am not knowledgable in sessions, cookies, ... so if I'm misunderstanding something or am picturing something completely wrong, please tell me.

Thanks,
Matic

**Comment by almarklein** [comment]
I think that normally the browser will remember the credentials while the browser is open (and maybe for a certain period of time?). So you should be able to login once, and then watch the stream while the browser is open.

But maybe I am misunderstanding the question? :)

**Comment by matkuki** [comment]
Hey @almarklein,
You are right, I had to wrap the JS code into a `flx.Widget`, and then it works.
But now the problem is that this library: https://github.com/inorganik/digest-auth-request
doesn't work with a `DAHUA` camera. I get an `Access-Control-Expose-Headers` error.

I'll leave this open for a few day, so that if anyone knows how to do digest authentication with a `DAHUA` camera, can let me know.

Thanks
