### ISSUE TITLE
Timers (as in QT)

### ISSUE THREAD

**Issue by TomDeRybel** [flexxui/flexx#652]
I'm writing a program to capture instrument data and update plots at a regular interval. In QT, there are timers available to make this straight-forward. 

I am now trying to do the same in Flexx, and made some progress using the APScheduler framework, which can integrate with Tornado and AsyncIO.

However, the last step in the process (using the emitted event at each timer tick) goes wrong and I'm not sure how to continue. 

A small program that illustrates the problem is included. The error message is included below.

Thank you for your time,
Tom

---
Job "Emitter (trigger: interval[0:00:01], next run at: 2020-06-23 13:55:37 CEST)" raised an exception
Traceback (most recent call last):
  File "/home/tomr/anaconda3/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/tomr/anaconda3/lib/python3.7/site-packages/flexx/event/_emitter.py", line 98, in __call__
    ob.emit(self._name, ev)
  File "/home/tomr/anaconda3/lib/python3.7/site-packages/flexx/app/_component2.py", line 413, in emit
    ev = super().emit(type, info)
  File "/home/tomr/anaconda3/lib/python3.7/site-packages/flexx/event/_component.py", line 469, in emit
    loop.add_reaction_event(reaction, ev)
  File "/home/tomr/anaconda3/lib/python3.7/site-packages/flexx/event/_loop.py", line 182, in add_reaction_event
    self._thread_match(True)
  File "/home/tomr/anaconda3/lib/python3.7/site-packages/flexx/event/_loop.py", line 262, in _thread_match
    raise RuntimeError('Flexx is supposed to run a single event loop a once.')
RuntimeError: Flexx is supposed to run a single event loop a once.

[APScheduler_Example.txt](https://github.com/flexxui/flexx/files/4819162/APScheduler_Example.txt)

**Comment by matkuki** [comment]
Maybe something like this:
```python
import asyncio

class TimerGUI(flx.PyWidget):
  def init(self):
    ...
    # Usage (this is a non-repeating call)
    asyncio.get_event_loop().call_later(1.0, self.tim1_tick)

    @flx.emitter
    def tim1_tick(self):
        asyncio.get_event_loop().call_later(1.0, self.tim1_tick)
        return dict(tick=True)
```

**Comment by TomDeRybel** [comment]
Hello Matkuki,
Thanks for your reply. Unfortunately, that approach won't work for me, as it results in timer drift. With each iteration, the bit of overhead time accumulates. This is why I choose the APScheduler framework, which handles this all nicely. The timers in QT also handle this well.

In the application I have in mind, the program will be running for days or weeks on end, and I need the timer to be pretty dead-on wrt the system wall clock. Though, I suppose I could modify your proposed solution so it reads the wall clock time, computes the drift, and modifies the call_later delay to keep it all synchronised. Definitely a valid back-up plan.

In the original code (when the troublesome reaction is commented-out), the print command in the emitter do show up nicely in the console. I'm wondering if there is some way to bride these waters and bring this back into the Flexx event handling.

Best regards,
Tom

**Comment by almarklein** [comment]
I don't know about APScheduler, but I assume there should be a way to make it use the same event loop as Flexx.

>  I could modify your proposed solution so it reads the wall clock time, computes the drift, and modifies the call_later delay to keep it all synchronised. 

That's what I would suggest as a second option :)

**Comment by TomDeRybel** [comment]
Hello Almar,

Thank you for your reply. 
There is indeed such a way: self.TimerScheduler = AsyncIOScheduler(event_loop=flx.Loop)

BUT, it requires the function "call_soon_threadsafe" to be defined, which is not the case in the Flexx event loop object. It can probably be derived from "call_soon", which in the docs is explained to be threadsafe.

The code relevant code in APScheduler is:

> def run_in_event_loop(func):
    @wraps(func)
    def wrapper(self, *args, **kwargs):
        wrapped = partial(func, self, *args, **kwargs)
        self._eventloop.call_soon_threadsafe(wrapped)
    return wrapper

I've tried to go the other way round, and explicitly integrate the Flexx event loop in an asyncio one, but didn't manage to get the flx.Loop.integrate() call to work. (don't know how to deal with the arguments. Which "self" do I need?)
> self.event_loop = asyncio.get_event_loop()
flx.Loop.integrate(loop=self.event_loop)

results in: TypeError: integrate() missing 1 required positional argument: 'self'

Before I give up and roll my own, do you think there is a reasonable way forward to integrate the event loop?

Best regards,
Tom

**Comment by almarklein** [comment]
The `flx.Loop` is a class for Flexx' internal event system. There is one instance of this calss: `flx.loop` (lowercase). This is not an asyncio event loop. It is a flexx-specific object that has ways to integrate with the asyncio event loop. By default. it will use `asyncio.get_event_loop()`. So if you'd do `self.TimerScheduler = AsyncIOScheduler(event_loop=asyncio.get_event_loop())` I would expect/hope things to just work ...

For going the other way around, you'd need the instance, not the class: `flx.loop.integrate(loop=self.event_loop)`

**Comment by TomDeRybel** [comment]
Hello Almar,

Thanks again for your quick answer. It's getting closer to working now. It seems I have to take both actions, and explicitly link both Flexx and APScheduler to one asyncio event loop.

And now I'm starting to feel like Alice in Wonderland, because the next floor down the rabbit hole brings a new curiosity.

After both libraries are placed in the same event loop, the state store I had declared seems to have gone missing. In the code attached, the declaration is at L44, and the program fails at the _mutate_store() on L58 with: "RuntimeError: Store4 needs a session!"

If I set the Flexx event loop in __main__ instead, just before flx.run() (L115), the program starts, but there are no GUI responses (I can click on the buttings, and the timer generates ticks, but the GUI doesn't change). I presume the issue is that something is lost when the event loop changes?

[APScheduler_Example.txt](https://github.com/flexxui/flexx/files/4840099/APScheduler_Example.txt)

Any further advise would be much appreciated!

**Comment by almarklein** [comment]
I tried to run your code and played with it a bit.

I would set the Flexx event loop as early as possible, probably even before launching the app. 

That said, I now suspect this is not related to the event loop. Flexx integrates with `asyncio.get_event_loop()` by default, and I would expect APScheduler to do to. That original error message (*Flexx is supposed to run a single event loop a once.*) actually checks thread id's. It looks like APScheduler uses threads, and is trying to emit a Flexx event from a different thread.

**Comment by TomDeRybel** [comment]
Hello Almar,

Thank you for your time and replies. I've got a feeling that trying to work around the multi-threading issue (and perhaps variable time delays in the inter-thread signalling?) you've identified will become more convoluted than rolling my own. I'll go ahead and do that instead.

Best regards,
Tom
