### ISSUE TITLE
Need to call check_real_size on fullscreenchange?

### ISSUE THREAD

**Issue by Konubinix** [flexxui/flexx#656]
Hi,

I am trying to write an application that contains a header, a body and a footer. When clicking on a fullscreen button, I want the application to enable fullscreen of the body (hiding the header and the footer). Doing so, I want the body to fill all the screen space.

On chromium on desktop, everything works fine.

But, I observe that on chromium for android as well as chromium inspector emulating mobile phone, the body does not fill the available space.

For example, consider the following example, where the footer intentionally takes half the space to show the issue.

    #!/usr/bin/env python3
    # -*- coding:utf-8 -*-
    
    from flexx import flx, config
    config.tornado_debug = True
    config.hostname = "0.0.0.0"
    
    
    class TestApp(flx.VFix):
        CSS = """
    .stretch, .stretch > img {
        height: 100%;
    }
    
    .centered, .centered > img {
        margin: auto;
        position: absolute;
        left: 0;
        right: 0;
        text-align: center;
    }
    
    .white-on-black {
       color: white;
       background-color: black;
    }
    """
    
        state = flx.ComponentProp()
        frontend = flx.ComponentProp()
    
        def init(self):
            with flx.VFix(flex=0.5, css_class="white-on-black") as self.body:
                flx.ImageWidget(
                    source="https://upload.wikimedia.org/wikipedia/commons/a/a3/Aptenodytes_forsteri_-Snow_Hill_Island%2C_Antarctica_-adults_and_juvenile-8.jpg",
                    flex=0.9,
                    css_class="stretch centered",
                )
                flx.Label(text="Ceci n'est pas un pingouin", flex=0,
                          css_class="centered white-on-blue")
            self.fullscreen_button = flx.Button(text="Fullscreen", flex=0.5)
    
        @flx.reaction("fullscreen_button.pointer_click")
        def enable_fullscreen(self, *events):
            elem = self.body.node
            for method in [
                    "requestFullscreen",
                    "mozRequestFullScreen",
                    "webkitRequestFullscreen",
                    "msRequestFullscreen",
            ]:
                if hasattr(elem, method):
                    # to understand why the need for bind -> https://code-examples.net/en/q/a3ef2c
                    getattr(elem, method).bind(elem)()
                    break
    
    
    def main():
        flx.App(TestApp).serve()
        flx.start()
    
    
    if __name__ == "__main__":
        main()
    
![chrome_window](https://user-images.githubusercontent.com/1181438/87909860-4e2a6700-ca69-11ea-8c75-7d1e26103bb1.png)

On chromium, when I click on the fullscreen button, the body correctly fill all the space.
But, when I use the mobile phone emulator, the body still uses only half the screen space.

![phone_fullscreen](https://user-images.githubusercontent.com/1181438/87909962-7d40d880-ca69-11ea-91fe-a072c0ab18fa.png)

When resizing the emulated mobile screen, the body is correctly resized.

I infer that, for some reason, flexx did not find a way to call check_real_size when the fullscreen mode was enabled.

I tried adding in flexx/ui/_widget.py:_init_events the line `self._addEventListener(self.node, 'fullscreenchange', self.check_real_size, 0)`.

Doing so produced the expected behavior: on chromium on android and the chromium mobile emulator, enabling fullscreen mode makes the body fill all the space. Because I don't know whether this is a work around or a correct solution, I did not submit yet a pull request.

What do you think of this?

**Comment by almarklein** [comment]
Yes, I think we should add that event. But the better place is probably `_clientcore.py`. Here we already check for the `resize` event.

**Comment by Konubinix** [comment]
I am not sure to understand. Do you suggest that, in JsSession, we listen on `fullscreenchange` with a callback that would iterate over all the instances to call `check_real_size`. Is that so?
Something like

    class JsSession:

        def __init__(self...):
            ...
            window.addEventListener('fullscreenchange', self._check_real_size_of_insances, False)
            ...

        def _check_real_size_of_insances(self):
            for instance in self.instances.values():
                if instance._disposed is False:
                    instance.check_real_size()

**Comment by almarklein** [comment]
No, I think you can simply add `window.addEventListener('fullscreenchange', self._check_size_of_objects, False)`. Flexx keeps track of the toplevel widgets, and only those are checked.

**Comment by Konubinix** [comment]
Almar Klein <notifications@github.com> writes:

> No, I think you can simply add `window.addEventListener('fullscreenchange', self._check_size_of_objects, False)`. Flexx keeps track of the toplevel widgets, and only those are checked.

I tried with the example above, but it did not work. I'm guessing that
because the window size did not change, there is no cascading of
"parent.size" events and the VFix widget never calls `check_real_size`.

I guess that the good design compromise − to avoid unnecessary event
handler in all the widgets − is to add the event handler only in the
widget that I know will have fullscreen enabled.
-- 
Konubinix
GPG Key    : 7439106A
Fingerprint: 5993 BE7A DA65 E2D9 06CE  5C36 75D2 3CED 7439 106A

**Comment by Konubinix** [comment]
Just guessing here. Actually, I added some code to trigger the fullscreen, I may just add the `check_real_size` after calling `requestFullScreen`.

This brings me to think that it could be great if flexx natively supported fullscreen with a dedicated method in widget.

For instance, it could look like 

    class Widget(app.JsComponent):
        def enable_fullscreen(self):
            for method in [
                "requestFullscreen",
                "mozRequestFullScreen",
                "webkitRequestFullscreen",
                "msRequestFullscreen",
            ]:
                if hasattr(self.node, method):
                    # to understand why the need for bind -> https://code-examples.net/en/q/a3ef2c
                    getattr(elem, method).bind(elem)()
                    break
            # enabling fullscreen most likely changed the size of the widget, let it acknoledge that
            self.check_real_size()

Then, the user could simply run

    @flx.reaction("some_button.pointer_click")
    def _enable_fullscreen(self):
        self.enable_fullscreen()

**Comment by almarklein** [comment]
> This brings me to think that it could be great if flexx natively supported fullscreen with a dedicated method in widget.

That's interesting. Though the code is small, so ppl who want full screen apps can easily copy the code. An example that demonstrates this would be really nice though!

**Comment by Konubinix** [comment]
Actually, even adding check_real_size won't fix the issue is some cases. I have a tablet showing 24h/24 photographs and clicking on fullscreen from time to time results in the issue.

I will close this issue as I still don't know how to fix this properly.
