### ISSUE TITLE
Adding a heartbeat to keep the websocket alive

### ISSUE THREAD

**Issue by Konubinix** [flexxui/flexx#657]
Hi,

I tried putting my flexx application behind haproxy and realized that the connection got close when the haproxy `client timeout` was reached.

I think I could ask haproxy not to have no timeout for this connection, but as the documentation says, [it is not recommended](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#timeout%20client).

    An unspecified timeout results in an infinite timeout, which
    is not recommended. Such a usage is accepted and works but reports a warning
    during startup because it may results in accumulation of expired sessions in
    the system if the system's timeouts are not configured either.

I then added a heartbeat propery in the state, with the current date (including the number of seconds), added in the frontend a `setInterval` to update this value every 30s (my `client timeout` being 1m, I guessed that half that time would be a good value) and react to it in the backend. That way, the annoying closing of the application when I don't touch it disappears.

Have you already had a similar issue? If so, how did you solve it? What is your opinion about the heartbeat solution?
Finally, do you think flexx could have such a mechanism internally, maybe disabled by default and enabled with an option?

My best,

**Comment by Konubinix** [comment]
While writing the issue, I realized that haproxy has a mechanism dedicated to long running websocket, [timeout tunnel](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#4.2-timeout%20tunnel).

    this timeout is usually used in conjunction with long-lived connections

**Comment by gwingnhbc** [comment]
Thanks for the work on this.

FWIW I have the same problem with firewall timeouts on many applications (not currently any written in Flexx). For these I have to set some sort of keepalive/heartbeat  going as the firewalls are disparate and therefore not something that can be set within haproxy, especially as  I don’t even have access to all of those firewalls.

Your suggestion of an inbuilt heartbeat would have value to us, probably.

Rgds,
Rob.

**Comment by almarklein** [comment]
Flexx should actually use a heartbeat: https://github.com/flexxui/flexx/blob/master/flexx/app/_tornadoserver.py#L568-L606

**Comment by Konubinix** [comment]
:thinking: I think I understand what is going on. I put a ws_config value very high, guessing that it would allow the application to stay alive even when the user did not interact with it. This caused a big time between pings (its value it ws_timeout / 5), and it migh be the reason why haproxy timed-out.

**Comment by Konubinix** [comment]
I can confirm the issue is gone when I leave the default value of ws_config. Thank you for the answer.

**Comment by almarklein** [comment]
That's a relief; I was half-afraid that the heartbeat logic was broken :)
