### ISSUE TITLE
using material design in flex

### ISSUE THREAD

**Issue by keinagae** [flexxui/flexx#660]
can you some one tell me how can i go on adding material design web in flexx of user interface design

**Comment by almarklein** [comment]
Sorry, I do not understand the question. What do you mean with material design?

**Comment by keinagae** [comment]
while going though flexx doc i saw on how can i use jquery and bootstrap but i was trying to use google material design in flexx app and i am inckude css but i was trying to include javascript as well in pyscript or in flexx doc i did not see on how to use javascript modules in flexx app if you look at material design [doc ](https://material.io/develop/web/docs/getting-started) you will fin in button javascript for enabling ripple effect i need to use following code
`mdc.ripple.MDCRipple.attachTo(document.querySelector('.foo-button'));`
but i dont see any doc info on how can i use direct classes defined in js file and on where should i initialize these thing

**Comment by almarklein** [comment]
The `document.querySelector('.foo-button')` is JS to select the first DOM element that has the class `.foo-bitton`.
I think you can simply do something like:

```py
class MyButton(flx.Button):
    def init(self):
        super().init()
        mdc.ripple.MDCRipple.attachTo(self.node)
```

**Comment by keinagae** [comment]
what if i am using more html like approach where for rendering i am using _create_dom(self)  and _render_dom(self) 
and one more thing i am curious are there any life cycle hooks like created or rendered or updated
and best place where i should initialize such javascript
`mdc.ripple.MDCRipple.attachTo(self.node)`

**Comment by almarklein** [comment]
`_create_dom()` is allowed to return actual DOM nodes (as opposed to virtual ones), so I think this is where you'd add that code. See e.g. the `_create_dom()` method for the [toggle button](https://github.com/flexxui/flexx/blob/master/flexx/ui/widgets/_button.py#L138).
