### ISSUE TITLE
Flexx doesn't work on Windows 10

### ISSUE THREAD

**Issue by Telcrome** [flexxui/flexx#661]
Starting apps doesn't work for me on Windows 10.

However, using the same code, it works on ubuntu (wsl2).

This is the code:

```python
from flexx import flx


class Example(flx.Widget):
    def init(self):
        flx.Label(text='hello world')


if __name__ == "__main__":
    app = flx.App(Example, title='Test')
    app.launch()
    flx.run()
```

Using Python 3.8 the `app.launch()` line raises a NotImplementError, using Python 3.7 I get the following error:

![image](https://user-images.githubusercontent.com/4445277/90148962-3b633380-dd84-11ea-88d1-63da5d118e01.png)

Is there a fix?

**Comment by ceprio** [comment]
Just a note: Your code works perfectly with Python 3.6 and Windows 10. 

I do not have 3.8 to test. Maybe someone else can try.

**Comment by almarklein** [comment]
@Telcrome what version of webruntime are you using? You could try `pip install -U webruntime` to get the latest.

**Comment by LewisNeal** [comment]
Update code around the first line to:

`import sys
import asyncio
from flexx import flx
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
`

The problem is discussed in #619

**Comment by Telcrome** [comment]
This solved the NotImplementedError and the event loop starts and the application works as expected.

In the documentation the way to run as a desktop app is described as `app.launch('app')`.

This (and using `app.launch()`) yields the error message from my initial post along with the warning:

`Using the Firefox web runtime and Qt (PySide/PyQt4/PyQt5) together may cause problems.`

Which is weird to someone experimenting with flexx,
because I never specified any of those frameworks, nor do I use firefox to run the app.

**Still, uninstalling Firefox solves both issues for me**

**Comment by Telcrome** [comment]
> @Telcrome what version of webruntime are you using? You could try `pip install -U webruntime` to get the latest.

If someone runs into the same issues: I did not test this, because uninstalling firefox and the workaround of @LewisNeal worked for me
