### ISSUE TITLE
Better way to call a jquery initialisation function?

### ISSUE THREAD

**Issue by ceprio** [flexxui/flexx#662]
Hi, I think I'm falling in love with this library: Being able to code an application with only one language and code both client and server in one file is great. No more Python/Javascript spaghetti!

I started by creating a Widget for my workhorse JS library: __datatables__. I'm using this library a lot for database interfaces. My code seem a bit hacky and I would like to get feedback. Especially about the code injection done in the `_render_dom` function (the script that gets injected by `flx.create_element('script', ...)` after the table creation). There must be a cleaner way to execute something like this in the page (the recommended way for initialization by datatables.net):

	$(document).ready( function () {
			    $('#table_id').dataTable(options);

Here is my demo code for datatables (from datatables.net):

```py
# doc-export: DataTableWidgets
"""
This example demonstrates a table widget based on datatables (see datatables.js). 
"""

from flexx import flx
from pscript import RawJS, window, py2js

# Associate datatables's assets with this module so that Flexx will load
# them when (things from) this module is used.
flx.assets.associate_asset(__name__, "https://code.jquery.com/jquery-2.2.4.js")
datatables_base_url = 'https://cdn.datatables.net/1.10.21/'
flx.assets.associate_asset(__name__, datatables_base_url + 'css/jquery.dataTables.css')
flx.assets.associate_asset(__name__, datatables_base_url + 'js/jquery.dataTables.js')

class DataTableWidget(flx.Widget):
    """ A DataTableWidget widget based on datatables.
    """

    options = flx.DictProp(settable=True, doc="""
        Options of the datatable
        args:
        columns: Minimum format: [{{"title": "Column 1"}},]
        data: list of list (list of rows)
        """)

    CSS = """
        .flx-DataTableWidget tr:nth-child(even) {
            background: #99BCDB;
        }
         
        .flx-DataTableWidget tr:nth-child(odd) {
            background: #EBF2F8;
        }
        .flx-DataTableWidget tr td {
            padding-top: 0px;
            padding-bottom: 0px;
        }
    """

    def init(self):
        global window

    def _create_dom(self):
        return flx.create_element('div', None, '')

    def _render_dom(self):
        global JSON
        s = flx.create_element("script", {"type": "text/javascript"}, 
            f'''
                $("#{self.id}").dataTable({JSON.stringify(self.options)});
            ''')
        return flx.create_element('div', None, [flx.create_element('table', {'id': self.id }, ''), s])


headers = [{"title": "Country"}, {"title": "Australia"}, {"title": "New Zealand"}]
data = [["gdpPercap_1952", 10039.59564, 10556.57566],
["gdpPercap_1957", 10949.64959, 12247.39532],
["gdpPercap_1962", 12217.22686, 13175.67800],
["gdpPercap_1967", 14526.12465, 14463.91893],
["gdpPercap_1972", 16788.62948, 16046.03728],
["gdpPercap_1977", 18334.19751, 16233.71770],
["gdpPercap_1982", 19477.00928, 17632.41040],
["gdpPercap_1987", 21888.88903, 19007.19129],
["gdpPercap_1992", 23424.76683, 18363.32494],
["gdpPercap_1997", 26997.93657, 21050.41377],
["gdpPercap_2002", 30687.75473, 23189.80135],
["gdpPercap_2007", 34435.36744, 25185.00911]]

class DataTableDemo(flx.HBox):

    def init(self):
        DataTableWidget(options = {"pageLength": 100, 'data':data, 'columns':headers})


if __name__ == '__main__':
    flx.launch(DataTableDemo, 'default-browser')
    flx.run()
```

Thank you for this great library,

**Comment by almarklein** [comment]
Hi @ceprio 

I think you could use `RawJS('enter rawjs here')` to include that snippet of jquery (or maybe dataTable can be attached to a table element without jquery?)

If the table is static, you could create a `table` element in `_create_dom()`, dataTable-ify it with that JS snippet, and return it. The `_render_dom()` can then just return an empty list.

If the table is dynamic (as in your example), I think you could create a `table` element in `_render_dom()`, dataTable-ify it with that JS snippet, and return it. That js script element should not be needed.

**Comment by ceprio** [comment]
Hi @almarklein,

I tried the `RawJS("$(document).ready( function () {$('#table_id').dataTable(options);)}` but that code needs to be executed AFTER the call to _render_dom when the table exists. I do not know where to place that code within the DataTableWidget class. If there was a `on_widget_ready()` function, that would solve my problem. 

Yes datatables need JQuery.

Sadly, I do not understand your last paragraph, I am creating the table in `_render_dom()` as you are suggesting but to datatable-ify it, the table needs to exist in the DOM and because of that, I need to delay the execution of the JQuery call till after the table creation. That is why I need the js script element added after the table. The js script element could be skipped if I could call `$('#table_id').dataTable(options);` once the table is created in the DOM. Where can I put that call and keep the table dynamic?

Thank you for your support,

**Comment by almarklein** [comment]
> ... the table needs to exist in the DOM 

Right ...because of the `$('#table_id')` part. This seems a bit silly, since you have a direct reference to the table object there. I don't remember how jQuery works, but can you not "cast" the table element to its jQuery variant? Something like `$(element)`?

Otherwise, I think it would be best to use `window.setTimeout` to schedule a the datatable-ify it quickly after creating the new table element.

**Comment by ceprio** [comment]
Found a better way with events:

```
    @event.reaction('!tableify')
    def on_tableify(self, *events):
        global jQuery
        jQuery('#' + self.id).dataTable(self.options)

    def _render_dom(self):
        self.emit('tableify', {})
        return flx.create_element('div', None, flx.create_element('table', {'id': self.id }, ''))
```
Thank you for your help. 

BTW, I've made a ui widget for datatables, once tested in the different use cases (differents initialisation scenario's) would you be interested in a pull request?

**Comment by almarklein** [comment]
> would you be interested in a pull request?

Yes, that would be nice! For somewhat specific widgets like this, we usually create an example. These examples are organized such that they can *also* be used easily by others, e.g. `from flexxamples.howtos.leaflet import LeafletWidget`  ... or `from flexxamples.howtos.datatables import DatatablesWidget` :)
