### ISSUE TITLE
Wrapper for 'Tabulator' weird behaviour

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#665]
Hi,

I have a wrapped JS object (table: http://tabulator.info/) which has a function:
```python
class TabulatorTableJS(flx.Widget):
    
    # More code

    @flx.action
    def write_cell(self, row_number, column_index, value):
        row = self.table.getRows()[row_number]
        cell = row.getCell(column_index)
        cell.setValue(value, True)
```
... which works great.
But when calling the function/action in a loop of let's say 100 repetitions, after 40-60 repetitions, `flexx` throws this:
`[E 12:28:48 flexx.app] JS: TypeError: cell.setValue is not a function - stack trace in browser console (hit F12).`

I have no idea why this is happening. It feels like some things are executed too fast on the `Python` side in order for the `JS`, but I'm just guessing here.
Does anyone have an idea of what is going on or how to fix this?

Thanks,
Matic

**Comment by almarklein** [comment]
Could it be that that table cell does not yet exist (not sure what `row.getCell()` would do in such a case)?

**Comment by matkuki** [comment]
Thanks for the quick reply @almarklein,

The cells exists, I create them beforehand in another function.
Then with a separate function which is triggered by a flx.Button runs. The function is:
```python
    @flx.reaction("button1.pointer_click")
    def button_press1(self, *events):
        for r in range(self.table.get_row_count()):
            for c in range(self.table.get_column_count()):
                self.table.write_cell(r, c, str(r))
```
The thing is I do some stuff in the table's callback, which gets called for every call to `cell.setValue`. Could it be that the callback takes too long and messes with the flow on the JS side?
I'm really just guessing in the dark now.

**Comment by matkuki** [comment]
Yes, if I don't connect the `cell_changed` callback when initializing the table, then the error doesn't appear.
The callback can be an empty function and the error still appears.
I have no idea what the problem is.

**Comment by almarklein** [comment]
> Could it be that the callback takes too long and messes with the flow on the JS side?

I would not expect that to be the cause, no.

Is the error still the same? Something like "TypeError: xxxx write_cell is not a function"? And `write_cell` is a function of tabulator, right? This error is common when you call a method of an object, but that object is not what you expect.

**Comment by matkuki** [comment]
You were absolutely right @almarklein 
When testing the type of `cell`, when the error happens, it is `Boolean` instead of `Cell component`.
So this has nothing to do with `flexx`.

Thank you

**Comment by matkuki** [comment]
Hey again @almarklein ,

I just did some more testing and the conclusion is:
there is a difference if the base table JS widget is wrapped in a `Widget` or `PyWidget`.
The hierarchy of the two widgets looks like this:
```python
class TabulatorTableJS(flx.Widget) # 
    # Widget's code that wraps a JS tabulator (http://www.tabulator.info/)
    def _create_dom(self):
        div = flx.create_element(
            'div',
            {
                "id": self.name,
            },
            []
        )
        return div

    def _render_dom(self):
        div = flx.create_element(
            'div',
            {
                "id": self.name,
            },
            []
        )
        return div

class CustomTabulatorStandard(flx.Widget)
    def init(...):
        self.tabulator = TabulatorTableJS( ... )
    
    # More CustomTabulatorStandard code

class CustomTabulatorJsonFile(flx.PyWidget)
    def init(...):
        self.tabulator = TabulatorTableJS( ... )
    
    # More CustomTabulatorJsonFile code
```
The difference between `CustomTabulatorStandard` and `CustomTabulatorJsonFile` is that the second one has additional python functionality that stores data to a JSON file when data in the tabulator changes.

Now, I tried the same code in both: insert 100 lines into the table one-by-one, then write into row 68 column 0 the value "SOMETHING".
With the `CustomTabulatorStandard` it works without problems, but with the `CustomTabulatorJsonFile` it throws the `JS: TypeError: cell.setValue ...` error. Then if I scroll to the bottom of the `CustomTabulatorJsonFile` table and again try to write the value "SOMETHING" again, it works! As if all of the table doesn't get rendered or buffered or ... Below is an animation of trying to write a cell before and after scrolling (rows have already been inserted):
![uKeOqH4rxb](https://user-images.githubusercontent.com/10289651/91550473-e2210580-e928-11ea-839e-0cd2e9d5a713.gif)


I found that removing all the functionality that writes or reads JSON files from disk `CustomTabulatorJsonFile` makes it work without scrolling (These are simple reads/writes using Python's `open` function). But I have no idea of how to add this functionality without the problem with cell writing.

Any solutions or ideas would be greatly appreciated!

Thanks

**Comment by almarklein** [comment]
Very interesting bug this, haha

One thing that comes to mind ... if you call an JS-action from Python, that action may not be send directly, but in the next event loop iteration. So if your Python code calls a JS-action, and then goes into a `sleep` or anything else that is not the asyncio event loop, then JS wont "receive" the action call.

**Comment by matkuki** [comment]
Hey @almarklein ,

Thanks for the hint. Could it be something `flexx` does in the background? For example, if I execute the `write_cell` function on the Python side in a loop of 1000 iterations instead of 100, after about 160 iterations `flexx` resets and throws:
```
[W 14:29:12 flexx.app] Closing connection due to lack of pong
[I 14:29:17 flexx.app] Session closed __main__ 61C682Tx0PsfzCLMEuuPINJB
```
This happens after the browser (Chromium) locks up completely and is processing like crazy. Note that the browser also locks up on a pure HTML/JS example of the table, so it's not out of the ordinary.

I'm just throwing every observation I can find in order to get any ideas of what the problem is.

**Comment by almarklein** [comment]
> Closing connection due to lack of pong

In that case, I think you're spamming the browser so hard that it does not get a chance to respond (in time) to the ping signal.

Another idea ... in general actions should be processed in-order, but maybe for some reason, the actions to add new rows have not finished yet when you try to update the cell? Try some print statements, maybe.

**Comment by matkuki** [comment]
Hey @almarklein ,

I tried two things:
- tried adding a `time.sleep(0.1)` delay between every `write_cell` call >> no changes
- tried adding a queue mechanism that queues all `write_cell` parameters, then adds them in one call (the JS `tabulator` widget can handle adding multiple cells in one call) >> no changes

Note that I added `print` statements inside the JS `write_cell` function:
- `row = self.table.getRows()[row_number]` returns a correct `row component`
- `cell = row.getCell(column_index)` returns `False`, which is where the problem lies. Scrolling down in the browser makes this return a correct `cell component`.

**Comment by matkuki** [comment]
Hey @almarklein 
New findings, please look at the complete example in the attachment:
[tabulator_flexx.zip](https://github.com/flexxui/flexx/files/5190751/tabulator_flexx.zip)

If you run it, first press the `INSERT ROWS` button, then press the `WRITE CELL` button and you should get an error in the console, but if you scroll the table even just for one row and press the `WRITE CELL` button, then it starts working.
But commenting out line `26` in `main.py`, rerun the application and repeat the button presses it works without scrolling!?!
So does it have something to the with the rendering of the widgets?

**Comment by matkuki** [comment]
I did some more testing and even splitting up the row insertion code from a `range(100)` loop and calling it on a button click once into a `range(50)` loop and call it twice on two button click, the same thing happens, after about row `63` the rows are empty until the table is scrolled, so it must be some kind of buffering issue.
I have no idea if this is a `flexx` thing or a `tabulator` thing. Any suggestions on what to try would be greatly appreciated, thanks.

**Comment by matkuki** [comment]
@almarklein 
It's as I thought (tested in `Chromium`):
![qYbTQS1ooA](https://user-images.githubusercontent.com/10289651/92930919-027db380-f443-11ea-9c7c-cfde6f303a78.gif)

Is this `flexx` behavior?

**Comment by matkuki** [comment]
@almarklein 
Can you take a look at the above problem? I'm quite desperate on how to fix this.

Thank you

**Comment by almarklein** [comment]
> If you run it, first press the INSERT ROWS button, then press the WRITE CELL button and you should get an error in the console,

Sorry, I cannot reproduce this. When I hit "insert rows", it will say `Row inserted after: 'null' /  '1'` ... until ... `Row inserted after: 'null' /  '99'`. This process takes a long time, and freezes the browser, but I can even press the "write button" while its doing that, and it will report `Success writing cell: row:68 / column:0 / value:SOMETHING`.

The fact that it takes so long makes me think that adding rows one by one is not very efficient. Is there not a way to add 100 rows at once?

**Comment by matkuki** [comment]
Hey @almarklein 

> This is regardless of commenting line 26

Really? And this is without scrolling first? Can you change the the row in line `50` to something higher like 97 and try again?
What browser are you using? I'm using `Iridium` (`Chromium` variant) and Firefox and get the error in both.

> The fact that it takes so long makes me think that adding rows one by one is not very efficient. Is there not a way to add 100 rows at once?

Yes there is, but it produces the same behaviour for me.

**Comment by matkuki** [comment]
Hey @almarklein ,
Have you tried changing the above mentioned row number?

**Comment by almarklein** [comment]
Tried again using row 97, and now I indeed get the error, regardless of line 26 being commented or not. I also tried hitting "insert rows", then read the news for 5 minutes, and then hit "write cell", same error. This makes me think that this has nothing to do with timing or events, but the cell simply not being created yet. It must be in some sort of pending state though, since it is created as you scroll down. I suspect that this is performance optimization by Tabulator, but they either did not consider the case of people writing content to pending cells, or for some reason that fails in combination with Flexx...

**Comment by matkuki** [comment]
Thank you for testing this!
I will contact the Tabulator people if they have any clue what's going on.

**Comment by almarklein** [comment]
You could try reproduce this on a page with tabulator but without Flexx to try and narrow it down.

**Comment by matkuki** [comment]
@almarklein
Tried it already copying the same visual structure with a couple of buttons and the `Tabulator` table inside a couple of nested `div`'s, but cannot reproduce it:
[tabulator_html.zip](https://github.com/flexxui/flexx/files/5254209/tabulator_html.zip)

**Comment by matkuki** [comment]
@almarklein 
New finding: in the last animated (https://github.com/flexxui/flexx/issues/665#issuecomment-691094303) it is shown that scrolling down makes new `div`'s appear (some kind of buffering/rendering). But if you insert a lot of rows (I tested with 1000), scrolling `UP` makes the `div`'s disappear again!!! I don't know what is going on here.

**Comment by matkuki** [comment]
@almarklein 
I tried removing all middle widgets like VFix-es and wrappers from the Tabulator table, So it's just a `PyWidget` or `Widget` (same behaviour on both) that contains a `TabulatorTableJS`.
![firefox_pFaVRf0n5F](https://user-images.githubusercontent.com/10289651/94906108-35452580-049e-11eb-8333-71c2148665c0.png)

So it must be something inside the `Flexx` code that creates this behaviour.

**Comment by almarklein** [comment]
Mmm ... I checked the code again, and saw that deep down you implement `def _render_dom(self):`. I tried to tweak that code to avoid the use of virtual dom elements (it should be ok, but who knows ...)
```py
    def _create_dom(self):       
        return document.createElement("div")
        
    def _render_dom(self):
        if self.name != self.node.id:
            self.node.setAttribute("id", self.name)
        return self.node
```

but ... it does not help :/

**Comment by matkuki** [comment]
@almarklein 
Thanks for trying. Anything else I could try?

**Comment by matkuki** [comment]
@almarklein 
I think a have a new discovery: if the `_render_dom` code is changed to:
```python
    def _render_dom(self):
        div = flx.create_element(
            'div',
            {
                "id": self.name + "-wrapper",
            },
            [
                flx.create_element(
                    'div',
                    {
                        "id": self.name,
                    },
                    []
                ),
            ]
        )
        return div
```
... and the `height` is not set for the `Tabulator` table initialization, then it works! This makes the entire table render.
But then the problem becomes for large tables, as the entire table is always shown and the table does not automatically show scrollbars, so the outer container has to do the scrolling. And this also introduces large memory usage for tables with more than 100 rows.

It seems that `Tabulator` needs to know the size of the container it's in or it does not like to be inside a `flexbox` container.
Does this give any clues: https://github.com/olifolkerd/tabulator/issues/1779#issuecomment-461890984 ?

**Comment by almarklein** [comment]
> The Tabulator element must have a height set on it otherwise it cannot enable the virtual DOM which enable classic render mode.

So ... this suggests that putting the table in an HBox or VBox won't work properly. Youcan try HFix / VFix instead. These should set the size explicitly.

**Comment by matkuki** [comment]
It already is in a `VFix` layout, even in the example I attached above.
It's weird because I also copied the `flx-Widget`, `flx-box`, `flx-split`, `flx-HVLayout`, ... CSS code into my raw JS tabulator example and still cannot get the same behaviour. In the raw example it always works.

**Comment by matkuki** [comment]
For anyone looking at this thread, the problem was in the wrapper code for the Tabulator, indexes of rows were not correctly referenced.
