### ISSUE TITLE
Using flx.create_element with raw html

### ISSUE THREAD

**Issue by ceprio** [flexxui/flexx#666]
In the flexx/iu/_widget.py file, function create_element: the documentation says: 
```
    The content of the widget may be given as a series/list of child nodes
    (virtual or real), and strings. Strings are converted to text nodes. To
    insert raw HTML, use the ``innerHTML`` prop, but be careful not to
    include user-defined text, as this may introduce openings for XSS attacks.
```
I'm trying to pass the children argument of create_element as raw html without success. I'm unable to figure out how to use the ``innerHTML`` property referenced above which may be the solution to my problem. Does anyone have a working example demonstrating how to pass raw html in an element within _render_dom()?

**Comment by ceprio** [comment]
So going through the code, I did not find anything about innerHTML used with create_element. I would propose to implement the following: create a html_string type that when used within the children pararameter of create_element would be rendered as html instead of string. This would allow html_string to be used within both create_element and Widgets that uses create_element.

Make sense?

**Comment by almarklein** [comment]
The `innerHTML` refers to a [property](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) of html elements. In flexx, you'd use it like so:
```py
            your_html = """
                          ...
            """
            flx.create_element("div", {"innerHTML": your_html}, []),
```

**Comment by ceprio** [comment]
I've implemented my html_string type as I felt it was a better solution for what I intended to do with it but I'm getting into other issues. I'll close this one and start another more appropriate thread to discuss it.
