### ISSUE TITLE
Questions about page title modification

### ISSUE THREAD

**Issue by 903935604** [flexxui/flexx#678]
![屏幕截图 2020-12-10 110747](https://user-images.githubusercontent.com/54740778/101716534-5ffebc00-3a95-11eb-95b5-aa38205a5da9.png)
I want to click the button to modify the content of the red long line. Can I modify it in real time? If not, I want to be able to change it after opening the page.

#This is the source code
from flexx import flx
class MainComponent(flx.Widget):
    def init(self):
        flx.Button(text="calc")
app = flx.App(MainComponent)
app.export('myapp.html', link=0)

**Comment by almarklein** [comment]
In JavaScript: `window.document.title = "foo"`
