### ISSUE TITLE
Use'style=' to modify the default value of'css'

### ISSUE THREAD

**Issue by 903935604** [flexxui/flexx#680]
![Image](http://chuantu.xyz/t6/741/1608198587x1700340463.png)

I used'style=' to modify the default value of the button'css', but a problem I found, I can only modify the value in'.flx-Button, .flx-ToggleButton', but not'.flx-Button: hover, .flx-ToggleButton:hover'. Simply put, when the button gains focus, change its background color. Use "css=" to modify all the buttons. I only want to modify one of them.

```py
from flexx import flx
class Tester(flx.Widget):
    def init(self):
        flx.Button(text='01',style='backgroundsdsd:#f99;border: 3px solid #f94;')
        flx.Button(text='02')
"""
    .flx-Button, .flx-ToggleButton{
        background: #e8e8e8;
        border: 1px solid #ccc;
        transition: background 0.3s;
    }
    .flx-Button:hover, .flx-ToggleButton:hover {
        background: #e8eaff;
    }
"""
if __name__ == '__main__':
    m = flx.launch(Tester)
    flx.run()
```

**Comment by almarklein** [comment]
You can use this pattern to add CSS:
```py
class MyWidget(flx.Widget):
    CSS="""
    """
```
