### ISSUE TITLE
Is there a way to use websockets?

### ISSUE THREAD

**Issue by AmalIrfan** [flexxui/flexx#681]
I am trying to make a chat application. I have heard that flask supports it, do flexx have support for it?

**Comment by almarklein** [comment]
If you goal is to create a chat application and play with websockets while doing that, then Flexx may not the right tool.

Flexx is a higher level library. It *does* use a websocket to communicate between server and client, but hides this from the user. If you'd create a chat application with Flexx, you'd use actions and reactions. There's actually [a simple chat application](https://github.com/flexxui/flexx/blob/master/flexxamples/demos/chatroom.py) in the examples.

**Comment by AmalIrfan** [comment]
Thank you very much, its nice to know. I am not completely through the documentation's guides and examples. I asked it because of my curiosity :)
