### ISSUE TITLE
Dynamic Init App Structure (renamed)

### ISSUE THREAD

**Issue by chaydenfowler** [flexxui/flexx#687]
[This part](https://flexx.readthedocs.io/en/stable/guide/assets_data.html) of the Guide describes how to store assets, but not how to access them within a Widget. 
It does mention requiring `PyComponent`s.
[This example](https://flexx.readthedocs.io/en/stable/examples/local_assets_src.html#local-assets-py) shows using associated assets for .css and .js files, being done outside widgets.

I'm looking for a way to pass a static chunk of data to the app to be read and used by the widgets.
However, this chunk of data is dynamically generated in some part of my code, **before the flx.App is instantiated and `.launch`ed**, but cannot be added literally to a Widget subclass.

Using one of the basic examples, here is the code I attempted to run:
```python
from flexx import flx

# Data comes from another part of my module.
testData = str({
    '1': 'red',
    '2': 'blue',
    '3': 'yellow',
}).encode()

#flx.assets.associate_asset(__name__, 'TestData', testData)
link = flx.assets.add_shared_data('TestData', testData)

class Example(flx.Widget):
    def init(self):
        with flx.HSplit():
            flx.Button(text='foo')
            with flx.VBox():
                flx.Widget(style='background:red;', flex=1)
                flx.Widget(style='background:blue;', flex=1)
                #temp_data = flx.assets.get_data('TestData')
                temp_data = flx.assets.get_data(link)
                flx.Label(text=temp_data)


app = flx.App(Example)
app.launch('browser')
flx.run()
```

However this produces the error:
`ValueError: JS in "c:/.../flexx_test/flexx_test2.py" uses 'flx.assets.get_data' but cannot convert <class 'method'> to JS.`
Which I assume means `flx.assets.get_data` is not intended to be used in a `JsComponent` ?

This problem doesn't seem like it should be difficult, so I feel I have overlooked something in the documentation.
Could I get a little help, please.

End Purpose: To dynamically generate static Flexx apps from a dictionary structure, using only `JsComponent`s for optional html standalone output.

**Comment by chaydenfowler** [comment]
Update: 
I've potentially found a solution to my 'End Purpose', 
The initial problem of passing data to the App after initialising is still unsolved.

The larger problem is to Dynamically generate an app structure (without generating a .py and running that, as that could conflict with compilation).
The general solution I found was that while assigning the Widget subclass as a `global` did not work, assigning the class as `sys.modules['__main__'].__dict__['Example']` does.

The basic example of this is:
```python
import sys

from flexx import flx, ui


def get_example(i=1):
    class Example(flx.Widget):
        def init(self):
            with flx.HSplit():
                flx.Button(text='foo')
                with flx.VBox():
                    flx.Widget(style='background:red;', flex=1)
                    for j in range(i):
                        flx.Widget(style='background:blue;', flex=1)
    # Assign variables to __main__ so that Flexx can see them.
    sys.modules['__main__'].__dict__['i'] = i
    sys.modules['__main__'].__dict__['Example'] = Example
    return Example

# Example = get_example()  # We no longer need this.


def run():
    app = flx.App(get_example(i=4))  # Make an example with 4 blue boxes.
    app.launch('browser')  # show it now in a browser
    flx.run()  # enter the mainloop


run()
```

Which successfully dynamically generates the app.
The caveat is that you have to assign every variable you use in the dynamic generation function, and that you could overwrite `__main__` attributes accidentally.
Modifying `__main__` directly (or any other module for that matter) is risky business and I hope there might be a better solution in the Flexx community, but for now this is the solution I'll use.
I could not figure out how to do this using PScript or otherwise.

While the title problem is unsolved, if there are no other comments this issue can be closed.

Cheers,

**Comment by almarklein** [comment]
> Which I assume means flx.assets.get_data is not intended to be used in a JsComponent ?

Indeed it's intended for use in module code.

I think in your case your could simply define the data in the module, and *just use* the data in the JSComponent. When that code is compiled, the data object is recognized, serialized, and produced as part as the compiled JS file. In other words, you should be able to use `testData` as you normally would, assuming that it can be serialized.

> The larger problem is to Dynamically generate an app structure.

Since some of the code is transpiled, Flexx must be able to *see* the code, which makes dynamic generation hard ... If your current solution works, that's fine. If things get more complex, you could consider generating .py files and loading these. Not great, but it should work.

**Comment by chaydenfowler** [comment]
So, I was investigating why `globals` behaved differently from `sys.modules[__name__].__dict__` and apparently they are exactly the same thing.
It appears I made a mistake somewhere with my `globals` test.
You can safely assign the widget to the module global and Flexx will pick it up.
This will allow you to pythonically (-ish) generate a dynamic app structure.
(renamed Issue from "Access Shared Assets" to reflect issue content)

Following the same example.
```python

from flexx import flx, ui

# import sys

iter_boxes = None
Example = None


def get_example(i=2):
    """Create example widget."""

    global iter_boxes
    global Example

    iter_boxes = i

    class Example(flx.Widget):
        def init(self):
            """Flexx Init."""
            with flx.HSplit():
                flx.Button(text="foo")
                with flx.VBox():
                    flx.Widget(style="background:red;", flex=1)
                    for _ in range(iter_boxes):
                        flx.Widget(style="background:blue;", flex=1)

    # sys.modules["__main__"].__dict__["iter_boxes"] = iter_boxes  # Identical to globals
    # sys.modules["__main__"].__dict__["Example"] = Example  # Identical to globals

    return Example


# Example = get_example()  # Don't need this.


def run():
    """Run Main."""
    # from example import Example
    app = flx.App(get_example(i=4))
    # app = flx.App(Example)

    app.launch("browser")  # show it now in a browser
    flx.run()  # enter the mainloop
    # app.export("example.html", link=0)  # Export to single file


run()
```

**Comment by almarklein** [comment]
Thanks for the update @chaydenfowler !
