### ISSUE TITLE
I can't import any not flexx module

### ISSUE THREAD

**Issue by Jeremi360** [flexxui/flexx#688]
I wanted to use markdown in my flexx app.
So I first tried python libs: _markdown_ then _mistune (pure python)_ and at last _MarkdownIt_.
But all filed on parsing.
So I try to use JS lib:
 ```python
 flx.assets.associate_asset(__name__, "https://github.com/markdown-it/markdown-it/blob/master/dist/markdown-it.js")
 ```
 I read docs, but I don't get it how use module added like this and I gets this error:
 `[E 13:49:21 flexx.app] JS: SyntaxError: expected expression, got '<' - stack trace in browser console (hit F12).`

**Comment by ceprio** [comment]
Have you tried this example?

[https://github.com/flexxui/flexx/blob/master/flexxamples/ui_usage/markdown.py](https://github.com/flexxui/flexx/blob/master/flexxamples/ui_usage/markdown.py)

It does seem to do exactly what you are looking for.

**Comment by Jeremi360** [comment]
> Have you tried this example?
> 
> https://github.com/flexxui/flexx/blob/master/flexxamples/ui_usage/markdown.py
> 
> It does seem to do exactly what you are looking for.

Thanks I only looked at docs and this example is not listed there.
I will check it thanks.

**Comment by Jeremi360** [comment]
> Have you tried this example?
> 
> https://github.com/flexxui/flexx/blob/master/flexxamples/ui_usage/markdown.py
> 
> It does seem to do exactly what you are looking for.

I try this example and I got this error:
```
Exception has occurred: RuntimeError
JS in "/home/jeremi/DevProjects/Python/Glexx/flexxamples/ui_usage/markdown.py" uses undefined variable 'ui.Markdown'.
  File "/home/jeremi/DevProjects/Python/Glexx/flexxamples/ui_usage/markdown.py", line 20, in <module>
    m = flx.launch(Example, 'default-browser')
```

**Comment by ceprio** [comment]
Oh, I see, this example will be part of the next flexx release. That is why ui.Markdown is not found. Either you wait for the next release or you download/clone the latest version from [https://github.com/flexxui/flexx](https://github.com/flexxui/flexx).
I'm working with my own github code, I had not noticed it was not released yet, sorry.

**Comment by Jeremi360** [comment]
Okey @ceprio I will try to clone the latest.
Where I can find planed date release of new version?

**Comment by almarklein** [comment]
There are no planned releases. We should probably first make sure that it's compatible with Python 3.9 (at least add a CI build for it. mmm, and I just realized this is still on Travis, so we should propably change CI to GH Actions too.

I'd recommend doing `pip install -U https://github.com/flexxui/flexx/archive/master.zip` I'll also make a note in the readme.

**Comment by Jeremi360** [comment]
Thanks @almarklein for info, I think, it issue can be close now.
