### ISSUE TITLE
Single secure connection between JS and Python

### ISSUE THREAD

**Issue by SyamGadde** [flexxui/flexx#693]
This is related to #546 but a different tack.  Is there a way to enforce a single connection between the JS side and the Python if running as a desktop app, and to ensure that the single connection is made from the actual thread that started the tornado server?  My use case is only a desktop app for now, but since the two flexx components communicate over a socket, some random person could potentially open a connection on the same port and do stuff independently.

Ideally, I'd love for the JS and Python components to communicate over a pipe (like from `os.pipe()` ) that is created by the main thread and is shared between the tornado thread and the JS code when running as a desktop app, so no one else can access it (putting aside the issue that on Windows the named pipe is not completely anonymous).  Is this possible?

**Comment by jrversteegh** [comment]
The client/JS side runs in a browser, even when the app runs as a desktop app. I am not aware of browsers that can connect to a pipe rather than to TCP/web sockets, but this may be lack of my knowledge. I can't think of reasons why Tornado couldn't serve on a pipe.

**Comment by almarklein** [comment]
No, browsers can only connect over http (thus TCP sockets). But if the server is running on `localhost`, the connection is not visible outside of your machine (the OS would skip some network layers).

I'm not sure if a process on the same machine would be able to connect to the same socket, but if an attacker managed to run a process on your machine you're screwed already anyway ;)

**Comment by SyamGadde** [comment]
Thanks for your comments.

I agree it's not likely with localhost for a malicious outsider to connect to it.  However, since I was planning on using the file browser widget, well, other users on the machine could potentially view the directory structure of the user who originally ran the app (and run some functions on their files).  My use case is read-only so the impact would be not so dire, but thought I would try to limit the attack surface area.  If I'm being paranoid I suppose I could write a shared secret in a private file and have the user type that in, but that might get annoying.

**Comment by gwingnhbc** [comment]
Hi,

FWIW I have a similar application, intended to be shared user, that does similar and the logic that works for me is that my app requires initial authentication, tested by logging onto a database, and then displays files relative to the home directory of the database user.  There are a whole load of associated privileges  and waiting tasks it determines from  the database at logon time as well but that’s probably irrelevant to your use case.

Good luck,
Rob.

**Comment by jrversteegh** [comment]
> I'm not sure if a process on the same machine would be able to connect to the same socket, but if an attacker managed to run a process on your machine you're screwed already anyway ;)

Not necessarily. We have moved on from the DOS era and multi-user systems do exist :p ;) Other users don't have access to my processes, but they do have access to tcp sockets listening on localhost in these processes, so I think there might be security issues if you expect some sort of user isolation.

**Comment by SyamGadde** [comment]
Playing off some of these thoughts -- I wonder how feasible it would be to have the launcher point to a "bootstrap" (in the conventional sense of the term, not the CSS framework) HTML page stored on the local disk that, when loaded, would redirect the browser to the normal app server with a hardcoded secret (generated at runtime) embedded into the URL.  The app server would only respond to requests with that secret, and any API calls embedded in the Javascript it returns would also contain this secret in the URL.  Since normal users should not be able to snoop local traffic, and the initial local HTML page permissions could be set to be only readable by the calling user, it should be relatively secure, right?

If this does sound feasible, whereabouts would I look to implement the URL rewriting and access control?

**Comment by almarklein** [comment]
> Not necessarily. We have moved on from the DOS era and multi-user systems do exist :p

I see, thanks for clarifying! I had overlooked that possibility :) 

> [...] it should be relatively secure, right?

My initial guess would be that you'd need https to prevent others from seeing the secret in the url, but frankly, I have no experience with security on localhost in multi-user environments.

**Comment by SyamGadde** [comment]
At least on UNIX-based machines, I wouldn't expect non-administrative users to be able to sniff localhost/loopback traffic.

So, it looks like the solution is a lot simpler than I had thought.  I did have to hack AppHandler to not advertise the app names:

```
# monkeypatch flexx to hide app path names
import flexx.app._tornadoserver
class SecretAppHandler(flexx.app._tornadoserver.AppHandler):
    def _get_index(self, app_name, path):
        self.write('Index of available apps: no apps')
flexx.app._tornadoserver.AppHandler = SecretAppHandler
```

but then all I have to do is to call serve() with a secret name:

```
    app = flx.App(MyGUI)
    app.serve(name=generate_super_secret_name())
    app.launch('app')
    flx.run()
```

I'd have to do some more verification that the app's name is not leaked in any other way (other than to those who already know the name), but hopefully this will address my concern, unless anyone sees a problem.  Thanks for letting me brainstorm here.
