### ISSUE TITLE
Calling sync functions in an async way?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#696]
Hi,

I have a couple of sync functions that create a few child `Widgets` and do a few calculations, that are called like so:
```python
def some_func():
  result_0 = my_func_0()
  result_1 = my_func_1(result_0)
  result_2 = my_func_2(result_1)
  ...
```
which works fine. Now I want to add a few calls that set a label to display some status, like so:
```python
def some_func():
  set_label_func("calling my_func_0")
  result_0 = my_func_0()
  set_label_func("finished my_func_0, calling my_func_1")
  result_1 = my_func_1(result_0)
  set_label_func("finished my_func_1, calling my_func_2")
  result_2 = my_func_2(result_1)
  ...
```
but only the last call to `set_label_func` is shown, as all the changes that `set_label_func` creates happen after `some_func` finishes.

Is there a way to add something after the `set_label_func` call to wait for the changes to happen and then continue execution?
Ideally it would be like so:
```python
def some_func():
  set_label_func("calling my_func_0")
  wait_for_label_changes()
  result_0 = my_func_0()
  set_label_func("finished my_func_0, calling my_func_1")
  wait_for_label_changes()
  result_1 = my_func_1(result_0)
  set_label_func("finished my_func_1, calling my_func_2")
  wait_for_label_changes()
  result_2 = my_func_2(result_1)
  ...
```
Or is rewriting all the `my_func`s to be `async` the only option?

Thanks

**Comment by almarklein** [comment]
This is something typically done via async code. Or perhaps by splitting it up into multiple actions/reactions.

**Comment by matkuki** [comment]
Thanks
