### ISSUE TITLE
Open new tab feedback?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#697]
Hi,

I have a simple way of opening new tabs from `flexx`, like so:
```python
class OpenNewTab(flx.JsComponent):
    destination = flx.StringProp("", settable=True)

    @flx.action
    def open(self):
        global window
        window.open(self.destination, '_blank')
```
This works most of the time, but sometimes it does not, meaning it doesn't open a new tab in the client's browser.

Is there a way to get feedback from the browser that a tab was actually opened?

Thanks

**Comment by almarklein** [comment]
It looks like it returns the new window object, which can be None: https://developer.mozilla.org/en-US/docs/Web/API/Window/open

**Comment by matkuki** [comment]
Didn't know that, thanks 👍
