### ISSUE TITLE
[Question] How to style TreeItem title and text

### ISSUE THREAD

**Issue by p-bogi** [flexxui/flexx#699]
I am attempting to modify the tree.py example from howtos. I changed HSplit() to VSplit(). I need to use longer strings in the text field (the right one).
![image](https://user-images.githubusercontent.com/84622472/120624492-0afa9c00-c461-11eb-9c91-a0b9effd1061.png)
From the documentation:
> Style classes for a TreeItem’s elements:
>     flx-TreeItem indicates the row of an item (its text, icon, and checkbox).
>     flx-TreeItem > collapsebut the element used to collapse/expand an item.
>     flx-TreeItem > checkbut the element used to check/uncheck an item.
>     flx-TreeItem > text the element that contains the text of the item.
>     flx-TreeItem > title the element that contains the title of the item.
>
I don't know how to change style of title and text . I was able to do it only on TreeItem level, but then it is applied to both title and text. I would like to make the title field shorter so the text field does not start in the middle. I would like also to set the initial window size because now it opens this way:
![image](https://user-images.githubusercontent.com/84622472/120625877-637e6900-c462-11eb-8baf-0f2f4d44a4c8.png)
Could you please give me advice how to style the example?

EDIT: I have yet one question, which is unrelated to the style. I tried to format the text field to simulate more columns, something like this: https://stackoverflow.com/a/9996049
I found that added spaces in the text string are automatically removed, so no formatting is possible. Is there any way to avoid that automatic behavior?

**Comment by p-bogi** [comment]
Thanks for hints. Dividing the TreeItem width between title and text worked.
When I replace all spaces with '&nbsp;':
![image](https://user-images.githubusercontent.com/84622472/121068232-4c29dd80-c7cc-11eb-9b93-672337d935d8.png)
I simply used mystring.replace(' ', '&nbsp;').

I have still 2 questions.
1) .hastitle
.flx-TreeWidget .flx-TreeItem > .text.hastitle {
    width: calc(100% - 200px);  /* 200px for the left side */
}
How could I know about existence of .hastitle ? I searched the flexx doc and googled for 'CSS hastitle' but no results. Why it does not function without that .hastitle? I tried only
.flx-TreeWidget .flx-TreeItem > .text {
and it didin't work.

2) How could I set initial size of window in which the application is opened? It opens in small window despite I have long strings in TreeItem text.
When I set size for .flx-Example, the app window does not reflect it and remains small:
    .flx-Example {
        width: 1000px;
        height: 600px;
    }
![image](https://user-images.githubusercontent.com/84622472/121071261-0111c980-c7d0-11eb-9e87-cb8a4e721e05.png)

**Comment by almarklein** [comment]
1. mmm, not sure what it does not work without `hastitle`, maybe the width gets set with `hastitle` so that rule is more precise and gets priority by css. Things like this are best investigated via the dev mode of the browser. Hit F12, then click the little element-picker button and click on the element. You can then inspect (and change) the CSS rules.

2. The windows size cannot be set using styling, but should be set when you launch your app: `launch( ..., size=(1000, 1000))`. It's documented [here](https://webruntime.readthedocs.io/en/latest/#webruntime.DesktopRuntime) but I agree that's a bit hard to find.

**Comment by almarklein** [comment]
Ah right. The text is plain text, not html. In that case the easiest way is to use this *en quad space* right here: " ". Not sure if that works, but you can definitely copy the spaces from [here](https://jkorpela.fi/chars/spaces.html).

**Comment by p-bogi** [comment]
The Unicode trick worked! :)
```
tree_list_dict = {
    'key1': ['a', 'b', 'cccccc cccccccccc ccccccccccc ccccccccccc ccc'],
    'key2': ['aaaaaaaa', 'b', 'cccccccccc ccccccccccc ccccc cc'], 
    'key3': ['a', 'bbbbbbbb', 'c cccccc ccccccccccccccc']
}
tree_string_dict = { key: u"{:<15} {:<15} {}".format(*tree_list_dict[key]).replace(' ', '\xA0') for key in tree_list_dict }
```
With proportional font `font-family: Courier;` I reached what I wished:
![image](https://user-images.githubusercontent.com/84622472/121548291-335c3a80-ca0d-11eb-886f-0fca67eda582.png)
Many thanks!
