### ISSUE TITLE
Integration with tools like Blaze, Bokeh, Vispy

### ISSUE THREAD

**Issue by datnamer** [flexxui/flexx#7]
Have you considered [Blaze](http://blaze.pydata.org/en/latest/) or [Bokeh](http://bokeh.pydata.org/en/latest/) integration? Not sure if this is to be data focused, but integration with those tools could be really cool, ala R's shiny but more flexible and powerful. 

[Escher](https://shashi.github.io/Escher.jl/) is a similar Julia project, using reactive programming, that might yield some ideas.

**Comment by almarklein** [comment]
Yes, these might eventually be integrated in some way. Especially for visualization it would be nice to have e.g. a `BokehWidget`, a `VispyWidget` and a `MatplotlibWidget`.

**Comment by datnamer** [comment]
Sounds cool. Another idea would be facilities for wrapping as widgets other JS libraries, like R's HTML widgets: http://www.htmlwidgets.org/

**Comment by almarklein** [comment]
Actually, based on the Mirrored class, it should be fairly easy to create a UI toolkit based on an existing JS ui library. Worth investigating whether to go down that route.

**Comment by datnamer** [comment]
I think that would be a great idea. Bokeh is awesome, but it will never be able to cover all the territory of the burgeoning javascript package landscape.  Boostrapping off that momentum would be very helpful.

**Comment by datnamer** [comment]
@almarklein do you think Pyscript can be used to write bokeh JS callbacks?

**Comment by almarklein** [comment]
I don't see why not. I think you already could if you do some manual plumbing. Maybe Bokeh could use PyScript to make it really easy. Next week I'm presenting at EuroScipy and Bryan is there too, so we'll probably discuss this.

**Comment by datnamer** [comment]
Yes that would be really cool!  I think others would echo my sentiments given the bokeh feature requests concerning client side capabilities and  callbacks.

**Comment by almarklein** [comment]
We have a BokehWidget now!

**Comment by almarklein** [comment]
Closing this. Flexx is now quite flexible in integrating with 3d party JS/CSS frameworks. See e.g. the examples for Bokeh, bootstrap, and leaflet.
