### ISSUE TITLE
Flexx running on RPi with static IP address?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#712]
Hi,

I have a **Raspberry Pi 3** (Raspberry Pi OS) running a **flexx** application with **Python 3.7** on port **80**.
The application runs without problems when I'm using DHCP to get the IP address, but when I set the Raspberry to a static IP address in */etc/dhcpcd.conf*, the application doesn't seem to remember session cookies. The application only remembers cookies on the Raspberry itself if I open the application in Chromium browser and navigate to it (**http://localhost**), but when trying to connect from a remote machine in a Chromium browser at **http://192.168.11.11** that is in the same LAN, the cookies are always **None**.

I have a simple login page (a **PyWidget** at **http://localhost**) that if a user logs in correctly some cookies are set (using **self.session.set_cookie**), then a redirection opens a second page (another **PyWidget** at **http://localhost/mainpage**), then the cookies are read and used for a few things (using **self.session.get_cookie**).
The problem is that all cookies are **None** on the second page where they are read when the Raspberry has a static IP address, and I have no idea why.

Any help would be greatly appreciated, as I'm not that knowledgable in this stuff. I may even be doing something wrong, so please correct me, if that is the case.

Thank you
Matic

**Comment by almarklein** [comment]
Are the page that sets the cookies, and the page that tries to load them, both on http://192.168.11.11/?

**Comment by matkuki** [comment]
Yes, they are **http://192.168.11.11/** and **http://192.168.11.11/mainpage**.

**Comment by almarklein** [comment]
And both on port 80, and http (not https), right? In that case I don't see why the cookies should not work. But it looks like a networking issue, not specific to Flexx.

**Comment by matkuki** [comment]
> And both on port 80, and http (not https), right?
Yes

I did some further testing and found that setting a static IP in the router's network (**192.168.1.X**) does not have this problem, it's only when I set it to a different subnet (in my example **192.168.11.X**) is when the cookies stop working.

**Comment by matkuki** [comment]
**CONCLUSION:**
This is not a Raspberry Pi problem, it is a date/time problem:
- *The problem:* cookies do not get stored when using `Widget.set_cookie`
- *The reason:* Date-and-time difference between RaspberryPi and client are too large
- *The solution:* Update date-and-time on both RaspberryPi and client to be the same, or at least in the cookie expiration time window

**Comment by almarklein** [comment]
Thans for the update. I learned from it as well :)
