### ISSUE TITLE
accent-color not effective in progressbar

### ISSUE THREAD

**Issue by rwang0417** [flexxui/flexx#724]
Hi, I was trying to change the color of a progressbar. The background color changed correctly but the accent color didn't. Is this a bug or did I miss something? Here is the code:
```
self.bar_quality = flx.ProgressBar(flex=1, value=0, text='{percent} accurate')
self.bar_quality.apply_style('background: #FC5A50; accent-color: #FF4500')
```
Thanks for your time!

**Comment by almarklein** [comment]
I don't see `accent-color` anywhere in the source, how did you come by that name?

**Comment by rwang0417** [comment]
I found it here: https://www.w3schools.com/cssref/css4_pr_accent-color.asp
I thought I can use any CSS property in this reference in the apply_style function. I am very new to both flexx and css, any explanation will be much appreciated!

**Comment by almarklein** [comment]
Ah, I see. No it does not work for (most?) flexx widgets.

**Comment by rwang0417** [comment]
Got it, thanks for the clarification!
