### ISSUE TITLE
the pycomponents has conflicts with js?

### ISSUE THREAD

**Issue by TaucherLoong** [flexxui/flexx#729]
[I 13:19:34 flexx.app] Asset store collected 2 new modules.
[I 13:19:35 flexx.app] Serving apps at http://localhost:49190/
[I 13:19:35 flexx.app] Asset store collected 29 new modules.
[I 13:19:35 flexx.app] Starting Flexx event loop.
[I 13:19:38 flexx.app] New session Demo 8yLzzODbeeBOYx8EWI8WrLac
[E 13:19:38 flexx.app] JS: RuntimeError: RuntimeError: Cannot instantiate a PyComponent from JS. - stack trace in browser console (hit F12).  
[I 13:37:26 flexx.app] Session closed Demo 8yLzzODbeeBOYx8EWI8WrLac
[I 13:37:26 flexx.app] Stopping Flexx event loop.

**Comment by TaucherLoong** [comment]
when run scrollable_n.py, it runs well. However run it as a tab branch, it stuck
[cartapp.py.txt](https://github.com/flexxui/flexx/files/8937996/cartapp.py.txt)
[scollable_n.py.txt](https://github.com/flexxui/flexx/files/8937998/scollable_n.py.txt)
.

**Comment by almarklein** [comment]
The error says it:

> Cannot instantiate a PyComponent from JS.

A TabWidget is a JSWidget, so it cannot contain a PyWidget.

**Comment by TaucherLoong** [comment]
> The error says it:
> 
> > Cannot instantiate a PyComponent from JS.
> 
> A TabWidget is a JSWidget, so it cannot contain a PyWidget.

do you know any substitution of  TabWidget? or does the tabwidget have PyWidget version?

**Comment by TaucherLoong** [comment]
Hi, almarklein:
thx a lot first. I am some new to flexx, I couldn't differ which part is js widget and PyWidget. Could you give me some advice?

**Comment by almarklein** [comment]
Ah, I see what's going on: your `ScrollExample` inherits from `PyComponent`, not `PyWidget`.

Another approach could be to keep it a `PyComponent`, instantiate it in your `Demo.init` like you do now, but set the title of the `scrollexample.ui` widget.
