### ISSUE TITLE
Run as a desktop app, how to close the incognito window？

### ISSUE THREAD

**Issue by chinaericgithub** [flexxui/flexx#730]
if __name__ == '__main__':
    app = flx.App(‘MywidgetApp’)
    app.launch("chrome-app") #chrome-app,firefox-app https://webruntime.readthedocs.io/en/latest/
    flx.run()

how to close the incognito window？
When launching as a desktop program, the google incognito window is always enabled by default, how to enable the normal google browser?

<img width="778" alt="jp" src="https://user-images.githubusercontent.com/10645868/177072192-fdc2b6b2-485c-481e-be31-fbe1b82d8a00.png">

**Comment by almarklein** [comment]
Use ``app.launch("chrome-browser")``, see https://webruntime.readthedocs.io/en/latest/#webruntime.launch.
