### ISSUE TITLE
How to Change the "Starting Flexx App"?

### ISSUE THREAD

**Issue by chinaericgithub** [flexxui/flexx#731]
![starting flexx app](https://user-images.githubusercontent.com/10645868/177116179-aad1bbad-dc69-4f4c-9986-5e82aac30042.png)
Hello,
How to Change the "Starting Flexx App"?

**Comment by matkuki** [comment]
In Python's `site-packages/flexx/app` directory, file `_assetstore.py` line `36`:
![image](https://user-images.githubusercontent.com/10289651/177133944-0637c1c1-84e9-45b0-b436-1fbf9272b847.png)

**Comment by almarklein** [comment]
Indeed. Other than changing the source, this text cannot be changed.
