### ISSUE TITLE
Run as a desktop app, how to hide or remove the close button on the browser ？

### ISSUE THREAD

**Issue by chinaericgithub** [flexxui/flexx#732]
Hello,

Run as a desktop app, how to hide or remove the close button on the browser  ？@[almarklein](https://github.com/almarklein)
<img width="146" alt="close window" src="https://user-images.githubusercontent.com/10645868/177151722-cd055e86-6f43-4246-a5e2-413a986d92dc.png">

**Comment by almarklein** [comment]
That button is out of control of Flexx.
