### ISSUE TITLE
PlotlyWidget in offline mode

### ISSUE THREAD

**Issue by bjarnekvae** [flexxui/flexx#737]
Hi,

First of all thank you for developing this awesome Python module, this has been super useful for developing slick GUIs for controlling my Python apps.

I have implemented the PlotlyWidget in my GUI, but the flexx server crashes when I try to start it without access to the internet, it seems that Plotly is dependent on internet, is there a way around this? It is kind of critical that my app works without internet.

Thanks!

**Comment by almarklein** [comment]
Could you post the error with which the server crashes? That might help determine what's going on.

**Comment by bjarnekvae** [comment]
Seems like you already posted the solution for this here: 
https://github.com/flexxui/flexx/issues/618#issuecomment-591838269

I have implemented this solution, and the my flexx app now works offline :+1:  

Thank you for the quick response though!
