### ISSUE TITLE
Is there a way to send data from my client side js widget to server side (for example images, videos)?

### ISSUE THREAD

**Issue by korayoezdemir** [flexxui/flexx#739]
Hi, 

im pretty new to flexx and python, I was wondering if there is a way to send data from my client side (which is  a jsComponent) to a server side (PyComponent). I saw the send_data and serve_data flexxamples, but its only mentioned that you can serve data to the client, but the client cant "upload" to the server side. 

The same goes on for the docs and the sessions and assets section.

**Comment by almarklein** [comment]
There are two ways:
* Create an action on the PyComponent. You can then call the action from the JS side.
* Create a reaction on the PyComponents that listens to events on the JS side.

Also see https://flexx.readthedocs.io/en/stable/guide/patterns.html

**Comment by korayoezdemir** [comment]
class Upload(flx.PyComponent):
    CSS = "body {background-color: #F5F5DC;}"

    def init(self):
        self.input = Input()

    @flx.action
    def send(self, msg):
        print("send", msg)


class Input(flx.Widget):
    CSS = "body {background-color: #F5F5DC;}"

    def _create_dom(self):
        return flx.create_element("div")

    def _render_dom(self):
        return [
            flx.create_element(
                "input",
                {
                    "type": "file",
                    "onchange": lambda e: <callAnotherFunctionhere>(e.target.files[0]),
                },
            ),
        ]

these are my widgets, I want to upload a picture and then get the raw bytes of it and use it  on my server side, how can i achieve this, when a call the send action with the onchange attribute, it does not work since it cant compile py to js, so far so good, you basically said what I have to do  earlier, but I still cant figure out how to do this.

**Comment by Konubinix** [comment]
[example.zip](https://github.com/flexxui/flexx/files/11432601/example.zip)

Here is a working example.

The content of the uploaded file is printed on the server part.

I think that this should work for small text files.

But if you need to send big files or binary files, you would rather want to show some upload progression, and the action/reaction mecanism seems not to be well suited for that.

**Comment by Konubinix** [comment]
The initialization is a bit tricky as I use a class dedicated to emit events and I use a workaround to make sure things get loaded at the appropriate time with `self.session.call_after_roundtrip(self.init_widgets)`

There may be a simpler way to put things together, but at least, this example contains what you should need.

**Comment by Konubinix** [comment]
To upload big files, I would create a websocket handler in the tornado app, based on the implementation of flexx.app._tornadoserver.WSHandler and registered using `flx.current_server().app.add_handlers("someurl", MYWSHandler)` in the main before calling flx.start

That way, the client code could open the connection and send data while showing a nice upload progressbar.

I don't have time to write a simple example of this, so this is just an (hopefully useful) food for thoughts.
