### ISSUE TITLE
_mutate_xxx‘s bug or for some other reason

### ISSUE THREAD

**Issue by 1751660300** [flexxui/flexx#743]
hello,
I want to update the ListProp and print its value, but the console outputs the initial value instead of the updated value for the first time. Is he a bug or for some other reason?

The result is :
JS: 
JS: D,E,F

my code:
```py
from flexx import flx

class Test(flx.Widget):
    str_list = flx.ListProp(settable=True)

    def init(self):
        self.btn = flx.Button(text='测试')

    @flx.action
    def replace_str_list(self, items):
        # 替换值
        self._mutate_str_list(items, 'set')

    @flx.reaction('btn.pointer_click')
    def main(self, *events):
        self.replace_str_list(['D', 'E', 'F'])
        print(self.str_list)
```

**Comment by almarklein** [comment]
Do you mean that on the first click the result is `[]`, and only on the second click it shows the updated value?

In the docs (https://flexx.readthedocs.io/en/stable/event/api.html#actions) it says:

> Actions are asynchronous and thread-safe. Invoking an action will not apply the changes directly; the action is queued and handled at a later time. The one exception is that when an action is invoked from anoher action, it is handled directly.

**Comment by 1751660300** [comment]
OK，thanks。
