### ISSUE TITLE
No certificate found

### ISSUE THREAD

**Issue by 1751660300** [flexxui/flexx#744]
hello, i create a app and run it, but it have a bug, i do not know how to deal this problem

error args:
No certificate found at D:\code\roc\UpdateToDoList\dist\mainview\hyper\certs.pem. 
Either ensure the default cert.pem file is included in the distribution or provide a custom certificate when creating the connection.

**Comment by almarklein** [comment]
Are you using the `ssl_keyfile` in the config, or passing ssl-related params to the server instance? Flexx does not do much with certificates by itself, it only facilitates configuring them, so there is likely something wrong with your config.

**Comment by 1751660300** [comment]
thank you , i use ssl_keyfile, so i need hyper moudle, this config in hyper
