### ISSUE TITLE
Use flx.create_element to create a label in the for loop, bind the onclick event, and dynamically transfer parameters. lambda fun error

### ISSUE THREAD

**Issue by 1751660300** [flexxui/flexx#748]
hello，i find a problem when used flx.create_element，i want to create element by this code:

```
def _render_dom(self):
    for index, data in enumerate(self.table_data):
        tds = []
        check_id = data.get("id")
        index_id = flx.create_element('input', {"type": "checkbox", "id": check_id, "value": check_id, "name": "checked",
                                                "onclick": lambda e: self.checkd_fun(check_id)}, )
        tds.append(index_id)
        return flx.create_element('div', {}, tds)
```
then i run this code and click input，lambda fun always trans check_id value is last data

 How do I dynamically generate onclick function?
Please pay attention to my question, thank you.

**Comment by almarklein** [comment]
This is a consequences of how closures work; the lambda loads the `check_id` from the outer scope, which will be left at whatever was its last value.

There are a few ways to fix this:
* Classic closure solution: use a helper function to create a scope that holds `check_id`. E.g. a function `create_my_element(check_id)` that produces `index_id`.
* Store `self.checkd_fun` on something like `window.my_app_checkd_fun`, and then `"onclick": f"window.my_app_checkd_fun('{check_id}')"`. This works well when `self` is some sort of global object, but may get tricky if its not.
* Use `lambda e: self.checkd_fun(e)`, in   `checkd_fun` check `e.target` to get the element. Store `check_id` on the element.
